// <auto-generated>
//   Generated by Xantham.Generator from cross-package-dep.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CrossPackageDep

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// An interface a dependent package references by name.
/// </summary>
[<Interface>]
type Widget =
    abstract id: string with get, set
    abstract label: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (id: string, label: string) : Widget = jsNative

/// <summary>
/// A generic of arity 1: the templated name has to carry the argument the reference applies.
/// </summary>
[<Interface>]
type Box<'T> =
    abstract value: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T) : Box<'T> = jsNative

/// <summary>
/// An object alias, declared under its own name rather than expanded at each use.
/// </summary>
[<Interface>]
type WidgetPair =
    abstract left: Widget with get, set
    abstract right: Widget with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (left: Widget, right: Widget) : WidgetPair = jsNative
