// <auto-generated>
//   Generated by Xantham.Generator from optional-array-shared-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec OptionalArraySharedLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Shared =
    abstract values: string[] option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?values: string[]) : Shared = jsNative
