// <auto-generated>
//   Generated by Xantham.Generator from catalog-source-projection-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CatalogSourceProjectionLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

type ScalarProjection = U2<string, float>

type ArrayProjection = U2<string, string[]>

type NullableProjection = string option

type TupleProjection = string * float

[<Interface>]
type ObjectProjection =
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string) : ObjectProjection = jsNative

[<Interface>]
type Scalar =
    abstract content: ScalarProjection with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (content: ScalarProjection) : Scalar = jsNative

[<Interface>]
type ArrayContent =
    abstract content: ArrayProjection with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (content: ArrayProjection) : ArrayContent = jsNative

[<Interface>]
type Nullable =
    abstract content: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?content: string) : Nullable = jsNative

[<Interface>]
type TupleContent =
    abstract content: TupleProjection with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (content: TupleProjection) : TupleContent = jsNative

[<Interface>]
type ObjectContent =
    abstract content: ObjectProjection with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (content: ObjectProjection) : ObjectContent = jsNative

[<Interface>]
type Named =
    abstract content: U2<string, bool> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (content: U2<string, bool>) : Named = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("scalar", "catalog-source-projection-lab")>]
    static member scalar (value: Scalar) : Scalar = jsNative
    [<Import("array", "catalog-source-projection-lab")>]
    static member array (value: ArrayContent) : ArrayContent = jsNative
    [<Import("nullable", "catalog-source-projection-lab")>]
    static member nullable (value: Nullable) : Nullable = jsNative
    [<Import("tuple", "catalog-source-projection-lab")>]
    static member tuple (value: TupleContent) : TupleContent = jsNative
    [<Import("object", "catalog-source-projection-lab")>]
    static member ``object`` (value: ObjectContent) : ObjectContent = jsNative
    [<Import("named", "catalog-source-projection-lab")>]
    static member named (value: Named) : Named = jsNative
