// <auto-generated>
//   Generated by Xantham.Generator from noinfer-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec NoinferLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

type NoInfer = obj

[<Interface>]
type Options<'T> =
    abstract value: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T) : Options<'T> = jsNative

type FirstOf = obj

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("widen", "noinfer-lab")>]
    static member widen<'T> (seed: 'T, guard: 'T) : 'T = jsNative
    [<Import("first", "noinfer-lab")>]
    static member first<'T> (value: 'T) : obj = jsNative
