// <auto-generated>
//   Generated by Xantham.Generator from nominal-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec NominalLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Interface>]
type Attr =
    abstract kind: string
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string) : Attr = jsNative

[<Interface>]
type GLAttr =
    abstract kind: string
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string) : GLAttr = jsNative

type Narrow =
    [<EmitIndexer>]
    abstract Item: string -> Attr with get, set

type Wide =
    [<EmitIndexer>]
    abstract Item: string -> U2<Attr, GLAttr> with get, set

[<Interface>]
type Geometry<'Attributes> =
    abstract attributes: 'Attributes with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (attributes: 'Attributes) : Geometry<'Attributes> = jsNative

[<Interface>]
type Base =
    abstract tag: string
    [<ParamObject; Emit("$0")>]
    static member Create (tag: string) : Base = jsNative

[<Interface>]
type Derived =
    inherit Base
    abstract extra: float
    abstract tag: string
    [<ParamObject; Emit("$0")>]
    static member Create (extra: float, tag: string) : Derived = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("Geometry", "nominal-lab"); EmitConstructor>]
    static member Geometry<'Attributes> () : Geometry<'Attributes> = jsNative
    [<Import("g", "nominal-lab")>]
    static member g: Geometry<Narrow> = jsNative
    [<Import("exact", "nominal-lab")>]
    static member exact<'T when 'T :> Base> (value: 'T) : 'T = jsNative
    [<Import("derived", "nominal-lab")>]
    static member derived: Derived = jsNative
