// <auto-generated>
//   Generated by Xantham.Generator from dollar-name-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec DollarNameLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

/// <summary>
/// An interface: declared <c>Shape</c>, a plain name, zod v4's <c>$ZodType</c> shape.
/// </summary>
[<Interface>]
type Shape =
    abstract a: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (a: string) : Shape = jsNative

/// <summary>
/// An alias: declared <c>Alias</c>.
/// </summary>
[<Interface>]
type Alias =
    abstract b: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (b: float) : Alias = jsNative

/// <summary>
/// A class: declared <c>Cls</c>, imported as <c>$Cls</c>.
/// </summary>
[<Interface>]
type Cls =
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string) : Cls = jsNative

/// <summary>
/// A type parameter: written <c>'_T</c>.
/// </summary>
[<Interface>]
type Box<'_T> =
    abstract v: '_T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (v: '_T) : Box<'_T> = jsNative

/// <summary>
/// Negative: the verbatim <c>Taken</c> keeps its name, and <c>$Taken</c> yields to it.
/// </summary>
[<Interface>]
type Taken =
    abstract c: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (c: string) : Taken = jsNative

[<Interface>]
type Taken2 =
    abstract d: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (d: string) : Taken2 = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A class: declared <c>Cls</c>, imported as <c>$Cls</c>.
    /// </summary>
    [<Import("$Cls", "dollar-name-lab"); EmitConstructor>]
    static member ``$Cls`` (value: string) : Cls = jsNative
    /// <summary>
    /// A trailing <c>$</c> on a method's own type parameter: written <c>'K_</c>.
    /// </summary>
    [<Import("pick", "dollar-name-lab")>]
    static member pick<'K_> (key: 'K_) : 'K_ = jsNative
    /// <summary>
    /// References each sanitised name, so the reference positions are gated too.
    /// </summary>
    [<Import("use", "dollar-name-lab")>]
    static member ``use`` (shape: Shape, alias: Alias, cls: Cls, box: Box<string>, taken: Taken2) : Taken = jsNative
