// <auto-generated>
//   Generated by Xantham.Generator from catalog-constructor-bounds-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CatalogConstructorBoundsLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Base =
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string) : Base = jsNative

[<Interface>]
type Derived =
    inherit Base
    abstract extra: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (extra: float, value: string) : Derived = jsNative

type Factory<'T when 'T :> Base> =
    [<EmitConstructor>]
    abstract Create: unit -> 'T

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("create", "catalog-constructor-bounds-lab")>]
    static member create<'T when 'T :> Derived> (factory: Create.FactoryConstructor<'T>) : 'T = jsNative

module Create =
    type FactoryConstructor<'T when 'T :> Derived> =
        [<EmitConstructor>]
        abstract Create: unit -> 'T
