// <auto-generated>
//   Generated by Xantham.Generator from member-shape-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec MemberShapeLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// An intersection over a compiler-lib type: <c>then</c> / <c>catch</c> / <c>finally</c> arrive as method
/// symbols, and each is a callback rather than a declaration.
/// </summary>
type Deferred =
    /// <summary>
    /// Attaches callbacks for the resolution and/or rejection of the Promise.
    /// </summary>
    /// <remarks>@param onfulfilled The callback to execute when the Promise is resolved.</remarks>
    /// <remarks>@param onrejected The callback to execute when the Promise is rejected.</remarks>
    /// <remarks>@returns A Promise for the completion of which ever callback is executed.</remarks>
    abstract ``then``<'TResult1, 'TResult2>: ?onfulfilled: Func<string, U2<'TResult1, JS.Promise<'TResult1>>> * ?onrejected: Func<obj, U2<'TResult2, JS.Promise<'TResult2>>> -> JS.Promise<U2<'TResult1, 'TResult2>>
    /// <summary>
    /// Attaches a callback for only the rejection of the Promise.
    /// </summary>
    /// <remarks>@param onrejected The callback to execute when the Promise is rejected.</remarks>
    /// <remarks>@returns A Promise for the completion of the callback.</remarks>
    abstract catch<'TResult>: ?onrejected: Func<obj, U2<'TResult, JS.Promise<'TResult>>> -> JS.Promise<U2<string, 'TResult>>
    /// <summary>
    /// Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
    /// resolved value cannot be modified from the callback.
    /// </summary>
    /// <remarks>@param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).</remarks>
    /// <remarks>@returns A Promise for the completion of the callback.</remarks>
    abstract ``finally``: ?onfinally: Action -> JS.Promise<string>
    abstract tag: string

/// <summary>
/// The same reach by heritage rather than intersection.
/// </summary>
type Recorder =
    abstract channel: string
    /// <summary>
    /// The **<c>addEventListener()</c>** method of the EventTarget interface sets up a function that will be called whenever the specified event is delivered to the target.
    ///
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/EventTarget/addEventListener)
    /// </summary>
    abstract addEventListener: ``type``: string * ?callback: obj * ?options: U2<bool, Browser.Types.AddEventListenerOptions> -> unit
    /// <summary>
    /// The **<c>dispatchEvent()</c>** method of the EventTarget sends an Event to the object, (synchronously) invoking the affected event listeners in the appropriate order. The normal event processing rules (including the capturing and optional bubbling phase) also apply to events dispatched manually with dispatchEvent().
    ///
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/EventTarget/dispatchEvent)
    /// </summary>
    abstract dispatchEvent: ``event``: Browser.Types.Event -> bool
    /// <summary>
    /// The **<c>removeEventListener()</c>** method of the EventTarget interface removes an event listener previously registered with EventTarget.addEventListener() from the target. The event listener to be removed is identified using a combination of the event type, the event listener function itself, and various optional options that may affect the matching process; see Matching event listeners for removal.
    ///
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/EventTarget/removeEventListener)
    /// </summary>
    abstract removeEventListener: ``type``: string * ?callback: obj * ?options: obj -> unit

/// <summary>
/// A lib declaration at a reference position: a shipped package binds it, and the binding stands
/// for the whole type.
/// </summary>
[<Interface>]
type Stamped =
    abstract at: JS.Date
    [<ParamObject; Emit("$0")>]
    static member Create (at: JS.Date) : Stamped = jsNative

/// <summary>
/// A lib declaration at a reference position outside every shipped package: it widens under its
/// own name, with its members left unread.
/// </summary>
[<Interface>]
type Located =
    abstract matrix: obj
    [<ParamObject; Emit("$0")>]
    static member Create (matrix: obj) : Located = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("deferred", "member-shape-lab")>]
    static member deferred: Deferred = jsNative
    [<Import("recorder", "member-shape-lab")>]
    static member recorder: Recorder = jsNative
    [<Import("stamped", "member-shape-lab")>]
    static member stamped: Stamped = jsNative
    [<Import("located", "member-shape-lab")>]
    static member located: Located = jsNative
