// <auto-generated>
//   Generated by Xantham.Generator from statics-collision-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec StaticsCollisionLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// A global interface holding the name the exported class below also carries. The class's
/// instance side is declared under a renamed name, and its statics have to reach *that*
/// declaration rather than this one.
/// </summary>
[<Interface>]
type Depot =
    abstract slot: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (slot: string) : Depot = jsNative

/// <summary>
/// An exported class sharing its name with the global interface above.
/// </summary>
[<Interface>]
type Depot2 =
    abstract slot: string
    [<ParamObject; Emit("$0")>]
    static member Create (slot: string) : Depot2 = jsNative
    [<Import("Depot.LIMIT", "statics-lab:depot")>]
    static member LIMIT: float = jsNative
    [<Import("Depot.open", "statics-lab:depot")>]
    static member ``open`` (slot: string) : Depot2 = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// An exported class sharing its name with the global interface above.
    /// </summary>
    [<Import("Depot", "statics-lab:depot"); EmitConstructor>]
    static member Depot (slot: string) : Depot2 = jsNative
