// <auto-generated>
//   Generated by Xantham.Generator from default-intersection-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec DefaultIntersectionLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS

[<Interface>]
type ImportedAgent =
    abstract onConnect: connection: Connection<obj> -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (onConnect: (Connection<obj> -> unit)) : ImportedAgent = jsNative

[<Interface>]
type Socket =
    abstract send: message: string -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (send: (string -> unit)) : Socket = jsNative

[<Erase>]
type State<'T> = private State__ of obj

[<Interface>]
type Connection<'T> =
    inherit Socket
    abstract state: obj option with get, set
    abstract setState: value: U2<'T, (obj option -> 'T)> -> obj option
    [<ParamObject; Emit("$0")>]
    static member Create (send: (string -> unit), setState: (U2<'T, (obj option -> 'T)> -> obj option), ?state: obj) : Connection<'T> = jsNative

[<Interface>]
type Agent =
    abstract onConnect: connection: Connection<obj> -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (onConnect: (Connection<obj> -> unit)) : Agent = jsNative
