// <auto-generated>
//   Generated by Xantham.Generator from pattern-parameter-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec PatternParameterLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Keys =
    abstract None: string
    abstract _None: string
    abstract Error: string option
    [<Emit("({\"None\": $0, \"_None\": $1, ...($2 === undefined ? {} : {\"Error\": $2})})")>]
    static member Create (__None: string, _None: string, ?_Error: string) : Keys = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("inspect", "pattern-parameter-lab")>]
    static member inspect (value: Keys) : string = jsNative
    [<Import("join", "pattern-parameter-lab")>]
    static member join (_None: string, _Error: string) : string = jsNative
