// <auto-generated>
//   Generated by Xantham.Generator from static-reexport-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec StaticReexportLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Certificate =
    abstract verify: spkac: string -> bool
    [<ParamObject; Emit("$0")>]
    static member Create (verify: (string -> bool)) : Certificate = jsNative
    [<Import("Certificate.exportChallenge", "node:static-reexport-lab")>]
    static member exportChallenge (spkac: string) : string = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("Certificate", "static-reexport-lab"); EmitConstructor>]
    static member Certificate () : Certificate = jsNative

module Node =
    module StaticReexportLab =
        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            [<Import("Certificate", "node:static-reexport-lab"); EmitConstructor>]
            static member Certificate () : Certificate = jsNative
