// <auto-generated>
//   Generated by Xantham.Generator from callable-hybrid-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CallableHybridLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

/// <summary>
/// A hybrid reached at a member position: the property's type is an anonymous object that is
/// both callable and carries a property.
/// </summary>
[<Interface>]
type Widget =
    abstract handler: Widget.Handler with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (handler: Widget.Handler) : Widget = jsNative

module Widget =
    [<Interface>]
    type Handler =
        abstract enabled: bool with get, set
        [<Emit("$0($1...)")>]
        abstract Invoke: ``event``: string -> string
        [<ParamObject; Emit("$0")>]
        static member Create (enabled: bool) : Handler = jsNative

/// <summary>
/// The same shape, written as a named declaration directly.
/// </summary>
[<Interface>]
type Trigger =
    abstract label: string with get, set
    [<Emit("$0($1...)")>]
    abstract Invoke: value: float -> float
    [<ParamObject; Emit("$0")>]
    static member Create (label: string) : Trigger = jsNative

/// <summary>
/// Two call signatures on one hybrid, distinguished by arity: both become <c>Invoke</c> overloads.
/// </summary>
[<Interface>]
type Multi =
    abstract tag: string with get, set
    [<Emit("$0($1...)")>]
    abstract Invoke: x: float -> float
    [<Emit("$0($1...)")>]
    abstract Invoke: x: float * y: float -> float
    [<ParamObject; Emit("$0")>]
    static member Create (tag: string) : Multi = jsNative

/// <summary>
/// Two call signatures that do not separate under F#'s overload rules - same parameter types,
/// different return types only. One <c>Invoke</c> overload survives; <c>dedupe-overloads</c> drops the
/// other the same way it drops any other colliding overload.
/// </summary>
[<Interface>]
type Ambiguous =
    abstract note: string with get, set
    [<Emit("$0($1...)")>]
    abstract Invoke: x: float -> float
    [<ParamObject; Emit("$0")>]
    static member Create (note: string) : Ambiguous = jsNative

/// <summary>
/// A generic call signature, where the interface itself owns no type parameters.
/// </summary>
[<Interface>]
type Identity =
    abstract calls: float with get, set
    [<Emit("$0($1...)")>]
    abstract Invoke<'T>: value: 'T -> 'T
    [<ParamObject; Emit("$0")>]
    static member Create (calls: float) : Identity = jsNative

/// <summary>
/// A generic interface whose call signature reads the interface's own type parameter.
/// </summary>
[<Interface>]
type Boxed<'T> =
    abstract value: 'T with get, set
    [<Emit("$0($1...)")>]
    abstract Invoke: unit -> 'T
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T) : Boxed<'T> = jsNative

/// <summary>
/// A hybrid whose own member is already called <c>Invoke</c>: emitting a second one would collide, so
/// the call signature stays a loss (SI001) rather than reaching Invoke (SI008).
/// </summary>
[<Interface>]
type Collides =
    abstract Invoke: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (Invoke: string) : Collides = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("widget", "callable-hybrid-lab")>]
    static member widget: Widget = jsNative
    [<Import("trigger", "callable-hybrid-lab")>]
    static member trigger (value: float) : float = jsNative
    [<Import("multi", "callable-hybrid-lab")>]
    static member multi (x: float) : float = jsNative
    [<Import("multi", "callable-hybrid-lab")>]
    static member multi (x: float, y: float) : float = jsNative
    [<Import("ambiguous", "callable-hybrid-lab")>]
    static member ambiguous (x: float) : float = jsNative
    [<Import("identity", "callable-hybrid-lab")>]
    static member identity<'T> (value: 'T) : 'T = jsNative
    [<Import("boxedNumber", "callable-hybrid-lab")>]
    static member boxedNumber () : float = jsNative
    [<Import("collides", "callable-hybrid-lab")>]
    static member collides (x: float) : float = jsNative
