// <auto-generated>
//   Generated by Xantham.Generator from parse-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec ParseLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Interface>]
type EventMap =
    abstract click: EventMapClick
    [<ParamObject; Emit("$0")>]
    static member Create (click: EventMapClick) : EventMap = jsNative

[<Interface>]
type EventMapClick =
    abstract at: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (at: float) : EventMapClick = jsNative

[<Interface>]
type Object3D<'TEventMap> =
    abstract id: float
    [<ParamObject; Emit("$0")>]
    static member Create (id: float) : Object3D<'TEventMap> = jsNative

[<Interface>]
type Intersection<'TIntersected> =
    abstract ``object``: 'TIntersected
    [<ParamObject; Emit("$0")>]
    static member Create (``object``: 'TIntersected) : Intersection<'TIntersected> = jsNative

[<Interface>]
type Caster =
    abstract intersectObject<'TIntersected when 'TIntersected :> Object3D<EventMap>> : ``object``: Object3D<EventMap> -> Intersection<'TIntersected>[]
    abstract intersectPair<'TFirst, 'TSecond when 'TFirst :> Object3D<EventMap> and 'TSecond :> Object3D<EventMap>> : first: 'TFirst * second: 'TSecond -> Intersection<'TFirst>[]
    [<ParamObject; Emit("$0")>]
    static member Create (intersectObject: Func<Object3D<EventMap>, Intersection<'TIntersected>[]>, intersectPair: Func<'TFirst, 'TSecond, Intersection<'TFirst>[]>) : Caster = jsNative

[<Interface>]
type Plain =
    abstract ping: at: float -> unit
    abstract echo<'T>: value: 'T -> 'T
    abstract on<'T when 'T :> EventMap>: handler: 'T -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (ping: Action<float>, echo: Func<'T, 'T>, on: Action<'T>) : Plain = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("Caster", "parse-lab"); EmitConstructor>]
    static member Caster () : Caster = jsNative
