<Project>
    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <FsDocsAllowExecutableProject>true</FsDocsAllowExecutableProject>
        <RepositoryUrl>https://github.com/shayanhabibi/Xantham</RepositoryUrl>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <FsDocsLicenseLink>https://github.com/shayanhabibi/Xantham/blob/master/LICENSE</FsDocsLicenseLink>
        <FsDocsReleaseNotesLink>https://github.com/shayanhabibi/Xantham/blob/master/RELEASE_NOTES.md</FsDocsReleaseNotesLink>
        <PackageProjectUrl>https://shayanhabibi.github.io/Xantham</PackageProjectUrl>
        <FsDocsLogoSource>content/assets/favicon-32x32.png</FsDocsLogoSource>
        <FsDocsFaviconSource>content/assets/favicon.ico</FsDocsFaviconSource>
    </PropertyGroup>
</Project>