// <auto-generated>
//   Generated by Xantham.Generator from ambient-module-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec AmbientModuleLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// A global type every module below refers to.
/// </summary>
[<Interface>]
type Payload =
    /// <summary>
    /// The payload's label.
    /// </summary>
    abstract label: string with get, set
    abstract at: Point with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (label: string, at: Point) : Payload = jsNative

[<Interface>]
type Point =
    abstract x: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (x: float) : Point = jsNative

[<Interface>]
type Telemetry =
    abstract level: float
    [<ParamObject; Emit("$0")>]
    static member Create (level: float) : Telemetry = jsNative

/// <summary>
/// A global class sharing its name with <c>ambient-lab:runtime</c>'s. Two declarations, two types.
/// </summary>
[<Interface>]
type Session =
    abstract kind: string
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string) : Session = jsNative

/// <summary>
/// An abstract class no specifier exports: <c>globalThis.Anvil</c> is not a module entrypoint, so it
/// keeps the interface form and its <c>Create</c>.
/// </summary>
[<Interface>]
type Anvil =
    abstract mass: float
    [<ParamObject; Emit("$0")>]
    static member Create (mass: float) : Anvil = jsNative

/// <summary>
/// A class exported from a specifier rather than from <c>globalThis</c>.
/// </summary>
[<Interface>]
type Hammer =
    abstract weight: float
    abstract strike: payload: Payload -> string
    [<ParamObject; Emit("$0")>]
    static member Create (weight: float, strike: Func<Payload, string>) : Hammer = jsNative
    [<Import("Hammer.LIMIT", "ambient-lab:tools")>]
    static member LIMIT: float = jsNative

/// <summary>
/// A type declared inside the module block.
/// </summary>
[<Interface>]
type Reading =
    abstract depth: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (depth: float) : Reading = jsNative

/// <summary>
/// A class written to be derived from: <c>abstract</c>, and exported from a specifier. F# reaches
/// this one as a class, because an interface admits no <c>inherit</c>.
/// </summary>
[<Import("Workbench", "ambient-lab:tools"); AbstractClass>]
type Workbench (label: string) =
    member _.label: string = jsNative
    /// <summary>
    /// The slot a derived class fills.
    /// </summary>
    abstract run: payload: Payload -> string

/// <summary>
/// A class with a base the compiler library owns. Not abstract, and still the class form:
/// <c>extends</c> is what says a consumer derives from it.
/// </summary>
[<Import("Snag", "ambient-lab:tools"); AbstractClass>]
type Snag (message: string) =
    inherit exn()
    member _.name
        with get (): string = jsNative
        and set (_: string): unit = jsNative
    member _.message
        with get (): string = jsNative
        and set (_: string): unit = jsNative
    member _.stack
        with get (): string option = jsNative
        and set (_: string option): unit = jsNative
    member _.cause
        with get (): obj option = jsNative
        and set (_: obj option): unit = jsNative

/// <summary>
/// A class whose base this run declares. An F# class reaches its base through a constructor
/// call, and an interface has none, so this keeps the interface form.
/// </summary>
[<Interface>]
type Vise =
    inherit Hammer
    abstract jaw: float
    abstract weight: float
    abstract strike: payload: Payload -> string
    [<ParamObject; Emit("$0")>]
    static member Create (jaw: float, weight: float, strike: Func<Payload, string>) : Vise = jsNative
    [<Import("Vise.LIMIT", "ambient-lab:tools")>]
    static member LIMIT: float = jsNative

[<Interface>]
type Session2 =
    abstract label: string
    [<ParamObject; Emit("$0")>]
    static member Create (label: string) : Session2 = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A namespace declaring a value: <c>globalThis.Telemetry</c> is real, so it keeps <c>[&lt;Global&gt;]</c>.
    /// </summary>
    [<Global("Telemetry")>]
    static member Telemetry: Telemetry = jsNative
    /// <summary>
    /// A global class sharing its name with <c>ambient-lab:runtime</c>'s. Two declarations, two types.
    /// </summary>
    [<Global("Session"); EmitConstructor>]
    static member Session () : Session = jsNative
    /// <summary>
    /// An abstract class no specifier exports: <c>globalThis.Anvil</c> is not a module entrypoint, so it
    /// keeps the interface form and its <c>Create</c>.
    /// </summary>
    [<Global("Anvil"); EmitConstructor>]
    static member Anvil () : Anvil = jsNative
    /// <summary>
    /// A class exported from a specifier rather than from <c>globalThis</c>.
    /// </summary>
    [<Import("Hammer", "ambient-lab:tools"); EmitConstructor>]
    static member Hammer (weight: float) : Hammer = jsNative
    /// <summary>
    /// A function exported from a specifier.
    /// </summary>
    [<Import("measure", "ambient-lab:tools")>]
    static member measure (payload: Payload) : float = jsNative
    /// <summary>
    /// A class written to be derived from: <c>abstract</c>, and exported from a specifier. F# reaches
    /// this one as a class, because an interface admits no <c>inherit</c>.
    /// </summary>
    [<Import("Workbench", "ambient-lab:tools"); EmitConstructor>]
    static member Workbench (label: string) : Workbench = jsNative
    /// <summary>
    /// A class with a base the compiler library owns. Not abstract, and still the class form:
    /// <c>extends</c> is what says a consumer derives from it.
    /// </summary>
    [<Import("Snag", "ambient-lab:tools"); EmitConstructor>]
    static member Snag (message: string) : Snag = jsNative
    /// <summary>
    /// A class whose base this run declares. An F# class reaches its base through a constructor
    /// call, and an interface has none, so this keeps the interface form.
    /// </summary>
    [<Import("Vise", "ambient-lab:tools"); EmitConstructor>]
    static member Vise (weight: float, jaw: float) : Vise = jsNative
    [<Import("connect", "ambient-lab:sockets")>]
    static member connect (label: string) : Payload = jsNative
    [<Import("version", "ambient-lab:runtime")>]
    static member version: string = jsNative
    [<Import("Session", "ambient-lab:runtime"); EmitConstructor>]
    static member Session (label: string) : Session2 = jsNative
