// <auto-generated>
//   Generated by Xantham.Generator from ambient-module-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec AmbientModuleLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// A global type every module below refers to.
/// </summary>
[<Interface>]
type Payload =
    /// <summary>
    /// The payload's label.
    /// </summary>
    abstract label: string with get, set
    abstract at: Point with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (label: string, at: Point) : Payload = jsNative

[<Interface>]
type Point =
    abstract x: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (x: float) : Point = jsNative

[<Interface>]
type Telemetry =
    abstract level: float
    [<ParamObject; Emit("$0")>]
    static member Create (level: float) : Telemetry = jsNative

/// <summary>
/// A global class sharing its name with <c>ambient-lab:runtime</c>'s. Two declarations, two types.
/// </summary>
[<Interface>]
type Session =
    abstract kind: string
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string) : Session = jsNative

/// <summary>
/// A class exported from a specifier rather than from <c>globalThis</c>.
/// </summary>
[<Interface>]
type Hammer =
    abstract weight: float
    abstract strike: payload: Payload -> string
    [<ParamObject; Emit("$0")>]
    static member Create (weight: float, strike: Func<Payload, string>) : Hammer = jsNative
    [<Import("Hammer.LIMIT", "ambient-lab:tools")>]
    static member LIMIT: float = jsNative

/// <summary>
/// A type declared inside the module block.
/// </summary>
[<Interface>]
type Reading =
    abstract depth: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (depth: float) : Reading = jsNative

[<Interface>]
type Session2 =
    abstract label: string
    [<ParamObject; Emit("$0")>]
    static member Create (label: string) : Session2 = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A namespace declaring a value: <c>globalThis.Telemetry</c> is real, so it keeps <c>[&lt;Global&gt;]</c>.
    /// </summary>
    [<Global("Telemetry")>]
    static member Telemetry: Telemetry = jsNative
    /// <summary>
    /// A global class sharing its name with <c>ambient-lab:runtime</c>'s. Two declarations, two types.
    /// </summary>
    [<Global("Session"); EmitConstructor>]
    static member Session () : Session = jsNative
    /// <summary>
    /// A class exported from a specifier rather than from <c>globalThis</c>.
    /// </summary>
    [<Import("Hammer", "ambient-lab:tools"); EmitConstructor>]
    static member Hammer (weight: float) : Hammer = jsNative
    /// <summary>
    /// A function exported from a specifier.
    /// </summary>
    [<Import("measure", "ambient-lab:tools")>]
    static member measure (payload: Payload) : float = jsNative
    [<Import("connect", "ambient-lab:sockets")>]
    static member connect (label: string) : Payload = jsNative
    [<Import("version", "ambient-lab:runtime")>]
    static member version: string = jsNative
    [<Import("Session", "ambient-lab:runtime"); EmitConstructor>]
    static member Session (label: string) : Session2 = jsNative
