// <auto-generated>
//   Generated by Xantham.Generator from constraint-closure-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec ConstraintClosureLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Box<'T> =
    abstract value: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T) : Box<'T> = jsNative

[<Interface>]
type Client =
    abstract accept<'T, 'E when 'E :> Box<'T>> : env: 'E -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (accept: ('E -> unit)) : Client = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("accept", "constraint-closure-lab")>]
    static member accept<'T, 'E when 'E :> Box<'T>> (env: 'E) : unit = jsNative
    [<Import("chain", "constraint-closure-lab")>]
    static member chain<'T, 'E, 'F when 'E :> Box<'T> and 'F :> Box<'E>> (env: 'F) : unit = jsNative
    [<Import("unused", "constraint-closure-lab")>]
    static member unused (value: string) : unit = jsNative
