// <auto-generated>
//   Generated by Xantham.Generator from fable-workaround-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec FableWorkaroundLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Interface>]
type Ok =
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string) : Ok = jsNative

[<Interface>]
type Err =
    abstract reason: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (reason: string) : Err = jsNative

type Outcome = U2<Err, Ok>

[<Interface>]
type Shape =
    abstract area: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (area: float) : Shape = jsNative

[<Interface>]
type Circle =
    inherit Shape
    abstract radius: float with get, set
    abstract area: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (radius: float, area: float) : Circle = jsNative

[<Interface>]
type Budget =
    abstract spent: float
    [<ParamObject; Emit("$0")>]
    static member Create (spent: float) : Budget = jsNative
    /// <summary>
    /// Assignable from JavaScript.
    /// </summary>
    [<Import("Budget.limit", "fable-workaround-lab")>]
    static member limit: float = jsNative

[<Interface>]
type Slot =
    abstract value: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?value: string) : Slot = jsNative

type Listener =
    abstract name: string with get, set
    abstract notify: count: float -> string

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// Returns an <c>Err</c> when <c>fail</c>, an <c>Ok</c> otherwise.
    /// </summary>
    [<Import("run", "fable-workaround-lab")>]
    static member run (fail: bool) : Outcome = jsNative
    /// <summary>
    /// One <c>Shape</c> that is a <c>Circle</c> and one that is not.
    /// </summary>
    [<Import("shapes", "fable-workaround-lab")>]
    static member shapes () : Shape[] = jsNative
    [<Import("Budget", "fable-workaround-lab"); EmitConstructor>]
    static member Budget (spent: float) : Budget = jsNative
    /// <summary>
    /// Three slots: a string, an explicit <c>null</c>, and an absent property.
    /// </summary>
    [<Import("slots", "fable-workaround-lab")>]
    static member slots () : Slot[] = jsNative
    /// <summary>
    /// <c>"string"</c>, <c>"null"</c> or <c>"absent"</c>, read off the property as JavaScript sees it.
    /// </summary>
    [<Import("describe", "fable-workaround-lab")>]
    static member describe (slot: Slot) : string = jsNative
    /// <summary>
    /// <c>JSON.stringify</c> of the listener, then its own enumerable keys, then <c>notify(1)</c>.
    /// </summary>
    [<Import("invite", "fable-workaround-lab")>]
    static member invite (listener: Listener) : string = jsNative
    /// <summary>
    /// A fresh object every call.
    /// </summary>
    [<Import("fresh", "fable-workaround-lab")>]
    static member fresh () : Ok = jsNative
    /// <summary>
    /// A fresh object every call, holding a reference to itself.
    /// </summary>
    [<Import("cyclic", "fable-workaround-lab")>]
    static member cyclic () : Ok = jsNative
