// <auto-generated>
//   Generated by Xantham.Generator from underscore-identifier-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec UnderscoreIdentifierLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Marker<'T> =
    abstract ``_``: 'T option with get, set
    abstract read: ``_``: string -> 'T
    abstract write: ?``_``: 'T -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (read: (string -> 'T), write: ('T option -> unit), ?``_``: 'T) : Marker<'T> = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("_", "underscore-identifier-lab")>]
    static member ``_`` (``_``: Marker<string>) : string = jsNative
