// <auto-generated>
//   Generated by Xantham.Generator from catalog-mapped-options-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CatalogMappedOptionsLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type LocaleMatcher =
    | [<CompiledName("best fit")>] BestFit
    | [<CompiledName("lookup")>] Lookup

[<Interface>]
type FirstOptions =
    abstract localeMatcher: LocaleMatcher option with get, set
    abstract other: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?localeMatcher: LocaleMatcher, ?other: string) : FirstOptions = jsNative

[<Interface>]
type SecondOptions =
    abstract localeMatcher: LocaleMatcher option with get, set
    abstract other: float option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?localeMatcher: LocaleMatcher, ?other: float) : SecondOptions = jsNative

[<Interface>]
type First =
    abstract supportedLocalesOf: ?options: First.SupportedLocalesOf.Options -> string[]
    [<ParamObject; Emit("$0")>]
    static member Create (supportedLocalesOf: (First.SupportedLocalesOf.Options option -> string[])) : First = jsNative

[<Interface>]
type Second =
    abstract supportedLocalesOf: ?options: Second.SupportedLocalesOf.Options -> string[]
    [<ParamObject; Emit("$0")>]
    static member Create (supportedLocalesOf: (Second.SupportedLocalesOf.Options option -> string[])) : Second = jsNative

module First =
    module SupportedLocalesOf =
        [<Interface>]
        type Options =
            abstract localeMatcher: LocaleMatcher option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?localeMatcher: LocaleMatcher) : Options = jsNative

module Second =
    module SupportedLocalesOf =
        [<Interface>]
        type Options =
            abstract localeMatcher: LocaleMatcher option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?localeMatcher: LocaleMatcher) : Options = jsNative
