// <auto-generated>
//   Generated by Xantham.Generator from inherit-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec InheritLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// A base this run declares.
/// </summary>
[<Interface>]
type Base =
    abstract name: string with get, set
    abstract at: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (name: string, at: float) : Base = jsNative

/// <summary>
/// Inherits <c>Base</c> and still declares its members: F# admits the redeclaration, and it is what
/// keeps the member list and a synthesized <c>Create</c> exact.
/// </summary>
[<Interface>]
type Derived =
    inherit Base
    abstract extra: bool with get, set
    abstract name: string with get, set
    abstract at: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (extra: bool, name: string, at: float) : Derived = jsNative

/// <summary>
/// A member redeclared at a narrower type. The checker reports the narrowed one, and the
/// <c>inherit</c> stands beside it.
/// </summary>
[<Interface>]
type Narrowed =
    inherit Base
    abstract name: string with get, set
    abstract at: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (name: string, at: float) : Narrowed = jsNative

/// <summary>
/// The diamond: <c>Both</c> extends an interface that already extends the other, and both operands
/// declare <c>volume</c>. F# admits both inherits and the shared member.
/// </summary>
[<Interface>]
type Loud =
    abstract volume: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (volume: float) : Loud = jsNative

[<Interface>]
type Pitched =
    inherit Loud
    abstract pitch: float with get, set
    abstract volume: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (pitch: float, volume: float) : Pitched = jsNative

[<Interface>]
type Both =
    inherit Loud
    inherit Pitched
    abstract label: string with get, set
    abstract volume: float with get, set
    abstract pitch: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (label: string, volume: float, pitch: float) : Both = jsNative

/// <summary>
/// A generic base: the argument is applied at the <c>inherit</c>, not dropped.
/// </summary>
[<Interface>]
type Box<'T> =
    abstract value: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T) : Box<'T> = jsNative

[<Interface>]
type Labelled<'T> =
    inherit Box<'T>
    abstract label: string with get, set
    abstract value: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (label: string, value: 'T) : Labelled<'T> = jsNative

/// <summary>
/// A generic base at a fixed argument.
/// </summary>
[<Interface>]
type Tagged =
    inherit Box<string>
    abstract tag: string with get, set
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (tag: string, value: string) : Tagged = jsNative

/// <summary>
/// A class base: the instance side inherits the base class's instance side.
/// </summary>
[<Interface>]
type Node =
    abstract id: float
    [<ParamObject; Emit("$0")>]
    static member Create (id: float) : Node = jsNative

[<Interface>]
type Leaf =
    inherit Node
    abstract leafy: bool
    abstract id: float
    [<ParamObject; Emit("$0")>]
    static member Create (leafy: bool, id: float) : Leaf = jsNative

/// <summary>
/// Not inherited: <c>Error</c> is the compiler lib's, and nothing shipped binds it, so the base has
/// no F# name at this position at all and only its members survive.
/// </summary>
[<Interface>]
type Failure =
    abstract code: float with get, set
    abstract name: string with get, set
    abstract message: string with get, set
    abstract stack: string option with get, set
    abstract cause: obj option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (code: float, name: string, message: string, ?stack: string, ?cause: obj) : Failure = jsNative

/// <summary>
/// Not inherited: <c>Promise</c> is the compiler lib's too, but a shipped Fable package does bind
/// it - under a name this run did not declare, so the members flatten and say so.
/// </summary>
[<Interface>]
type Deferred =
    abstract tag: string with get, set
    /// <summary>
    /// Attaches callbacks for the resolution and/or rejection of the Promise.
    /// </summary>
    /// <remarks>@param onfulfilled The callback to execute when the Promise is resolved.</remarks>
    /// <remarks>@param onrejected The callback to execute when the Promise is rejected.</remarks>
    /// <remarks>@returns A Promise for the completion of which ever callback is executed.</remarks>
    abstract ``then``: obj with get, set
    /// <summary>
    /// Attaches a callback for only the rejection of the Promise.
    /// </summary>
    /// <remarks>@param onrejected The callback to execute when the Promise is rejected.</remarks>
    /// <remarks>@returns A Promise for the completion of the callback.</remarks>
    abstract catch: obj with get, set
    /// <summary>
    /// Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
    /// resolved value cannot be modified from the callback.
    /// </summary>
    /// <remarks>@param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).</remarks>
    /// <remarks>@returns A Promise for the completion of the callback.</remarks>
    abstract ``finally``: obj with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (tag: string, ``then``: obj, catch: obj, ``finally``: obj) : Deferred = jsNative

/// <summary>
/// A utility-type base: TypeScript's surgery over <c>Base</c> rather than a name it can inherit.
/// </summary>
[<Interface>]
type Slim =
    inherit SlimBase
    abstract slim: bool with get, set
    abstract name: string option with get, set
    abstract at: float option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (slim: bool, ?name: string, ?at: float) : Slim = jsNative

[<Interface>]
type SlimBase =
    abstract name: string option with get, set
    abstract at: float option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?name: string, ?at: float) : SlimBase = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A class base: the instance side inherits the base class's instance side.
    /// </summary>
    [<Import("Node", "inherit-lab"); EmitConstructor>]
    static member Node (id: float) : Node = jsNative
    [<Import("Leaf", "inherit-lab"); EmitConstructor>]
    static member Leaf (id: float) : Leaf = jsNative
