// <auto-generated>
//   Generated by Xantham.Generator from literal-alias-owner-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec Identity.LiteralAliasOwnerLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Value =
    abstract kind: Value.Kind option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?kind: Value.Kind) : Value = jsNative

module Value =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Kind =
        | [<CompiledName("a")>] A
        | [<CompiledName("b")>] B
