// <auto-generated>
//   Generated by Xantham.Generator from @types/types-only-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec TypesOnlyLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// A class, whose static is bound at the renderer's other specifier-writing call site.
/// </summary>
[<Interface>]
type Counter =
    abstract value: float
    [<ParamObject; Emit("$0")>]
    static member Create (value: float) : Counter = jsNative
    [<Import("Counter.MAX", "types-only-lab")>]
    static member MAX: float = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A function export: <c>[&lt;Import("greet", ...)&gt;]</c> on an <c>Exports</c> member.
    /// </summary>
    [<Import("greet", "types-only-lab")>]
    static member greet (name: string) : string = jsNative
    /// <summary>
    /// A value export: the same attribute, read as a get-only property.
    /// </summary>
    [<Import("version", "types-only-lab")>]
    static member version: string = jsNative
    /// <summary>
    /// A class, whose static is bound at the renderer's other specifier-writing call site.
    /// </summary>
    [<Import("Counter", "types-only-lab"); EmitConstructor>]
    static member Counter (start: float) : Counter = jsNative
