// <auto-generated>
//   Generated by Xantham.Generator from intersection-callable-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec IntersectionCallableLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

type Chained = (float -> float)

/// <summary>
/// Member position: the property's type is an intersection of two callables.
/// </summary>
type Utils =
    abstract round: value: float * length: float -> float
    abstract round: length: float -> float

/// <summary>
/// Call signatures beside a property: the member set flattens and the signature is the loss.
/// </summary>
[<Interface>]
type Timers =
    abstract schedule: Timers.Schedule with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (schedule: Timers.Schedule) : Timers = jsNative

module Timers =
    [<Interface>]
    type Schedule =
        abstract cancel: unit -> unit
        [<Emit("$0($1...)")>]
        abstract Invoke: unit -> unit
        [<ParamObject; Emit("$0")>]
        static member Create (cancel: (unit -> unit)) : Schedule = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("round", "intersection-callable-lab")>]
    static member round (value: float, length: float) : float = jsNative
    [<Import("utils", "intersection-callable-lab")>]
    static member utils: Utils = jsNative
    /// <summary>
    /// Export position: the same intersection, where the signatures already render.
    /// </summary>
    [<Import("roundPad", "intersection-callable-lab")>]
    static member roundPad (value: float, length: float) : float = jsNative
    /// <summary>
    /// Export position: the same intersection, where the signatures already render.
    /// </summary>
    [<Import("roundPad", "intersection-callable-lab")>]
    static member roundPad (length: float) : float = jsNative
