// <auto-generated>
//   Generated by Xantham.Generator from paramobject-overload-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec ParamobjectOverloadLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS

[<Interface>]
type QueryOptions =
    abstract query: string option with get, set
    abstract messages: unit option with get, set
    abstract shared: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (shared: float, ?query: string, ?messages: unit) : QueryOptions = jsNative

[<Interface>]
type MessagesOptions =
    abstract query: unit option with get, set
    abstract messages: string[] option with get, set
    abstract shared: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (shared: float, ?query: unit, ?messages: string[]) : MessagesOptions = jsNative

type SearchOptions = U2<MessagesOptions, QueryOptions>

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("search", "paramobject-overload-lab")>]
    static member search (options: SearchOptions) : unit = jsNative
