// <auto-generated>
//   Generated by Xantham.Generator from flags-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec FlagsLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// Alias position: the declaration itself is a template literal.
/// </summary>
type EventName = string

[<Interface>]
type Emitter =
    /// <summary>
    /// Member position, through the alias.
    /// </summary>
    abstract ``event``: string with get, set
    /// <summary>
    /// Member position, written inline over two open operands.
    /// </summary>
    abstract channel: string with get, set
    /// <summary>
    /// Parameter position on a member, returning one through the alias.
    /// </summary>
    abstract resolve: scope: string -> string
    [<ParamObject; Emit("$0")>]
    static member Create (``event``: string, channel: string, resolve: Func<string, string>) : Emitter = jsNative

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type Mode =
    | [<CompiledName("read")>] Read
    | [<CompiledName("write")>] Write

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type ModeEvent =
    | [<CompiledName("onRead")>] OnRead
    | [<CompiledName("onWrite")>] OnWrite

/// <summary>
/// A negative for the other side. A template literal over a type parameter is a type-level
/// computation the checker cannot finish, so it stays the erased phantom of D9's rung rather
/// than collapsing to a bare <c>string</c> and losing its arity.
/// </summary>
[<Erase>]
type Tagged<'T> = private Tagged__ of string

[<Interface>]
type Ledger =
    /// <summary>
    /// A member of bigint type, and a method taking and returning one.
    /// </summary>
    abstract balance: bigint with get, set
    abstract credit: amount: bigint -> bigint
    [<ParamObject; Emit("$0")>]
    static member Create (balance: bigint, credit: Func<bigint, bigint>) : Ledger = jsNative

/// <summary>
/// A bigint *literal* type is the widening its string and number counterparts already are.
/// </summary>
type Two = bigint

[<Interface>]
type Registry =
    abstract holder: obj with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (holder: obj) : Registry = jsNative

[<Interface>]
type Keyed =
    abstract id: obj with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (id: obj) : Keyed = jsNative

[<Interface>]
type Plain =
    abstract name: string with get, set
    abstract kind: string with get, set
    abstract count: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (name: string, kind: string, count: float) : Plain = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// Parameter position on an exported function, and a template literal returned.
    /// </summary>
    [<Import("normalize", "flags-lab")>]
    static member normalize (name: string) : string = jsNative
    /// <summary>
    /// An intrinsic string mapping over an open operand: a string, with the transform lost.
    /// </summary>
    [<Import("shout", "flags-lab")>]
    static member shout (text: string) : string = jsNative
    /// <summary>
    /// Under an array at a parameter, bare at a return.
    /// </summary>
    [<Import("total", "flags-lab")>]
    static member total (amounts: bigint[]) : bigint = jsNative
    [<Import("ledger", "flags-lab")>]
    static member ledger (start: bigint) : Ledger = jsNative
    [<Import("freeze", "flags-lab")>]
    static member freeze (value: obj) : obj = jsNative
    [<Import("brandTag", "flags-lab")>]
    static member brandTag: obj = jsNative
    [<Import("describe", "flags-lab")>]
    static member describe (key: obj) : string = jsNative
