module Spec

open System.Collections.Generic
open System.ComponentModel
open EasyBuild.FileSystemProvider
open Fable.Core
open TypeScript
open Xantham.Fable
open Xantham.Mocha

type This = AbsoluteFileSystem<__SOURCE_DIRECTORY__>
// If the file system doesn't compile, then it's because the test fixtures haven't
// been created. Run `dotnet fsi ./tests/Fixtures.Setup.fsx` from the root of the repo.
type TestFixtures = AbsoluteFileSystem<This.``..``.fixtures.``.``>

type RunnerContext = private {
    Suites: SuiteContext array
} with
    member this.suites = this.Suites
    static member inline make runnerName (testNameFileMap: (string * string) list) ([<InlineIfLambda>] fn: Suite -> RunnerContext -> unit) =
        Expecto.testSuite runnerName <| fun suite -> 
            fn suite { Suites = testNameFileMap |> List.map (fun (name, file) -> SuiteContext.Create name file) |> Array.ofList }
    [<EditorBrowsable(EditorBrowsableState.Never)>]
    member inline this.testSuiteImpl (suiteFn: string -> (Suite -> unit) -> Suite) name ([<InlineIfLambda>] fn: Suite -> unit) =
        suiteFn name fn
        |> _.bail(false)
        |> ignore
    member inline this.testSuite name ([<InlineIfLambda>] fn: Suite -> unit) = this.testSuiteImpl Expecto.testSuite name fn
    member inline this.ftestSuite name ([<InlineIfLambda>] fn: Suite -> unit) = this.testSuiteImpl Expecto.ftestSuite name fn
    member inline this.ptestSuite name ([<InlineIfLambda>] fn: Suite -> unit) = this.testSuiteImpl Expecto.ptestSuite name fn
    [<EditorBrowsable(EditorBrowsableState.Never)>]
    member inline this.testCaseImpl (suiteFn: string -> (Suite -> unit) -> Suite) name ([<InlineIfLambda>] fn: Context -> SuiteContext -> unit) =
        suiteFn name <| fun _ ->
            this.suites
            |> Array.iter (fun suiteContext ->
                testCase suiteContext.Name <| fun testContext ->
                    fn testContext suiteContext
                )
        |> _.bail(false)
        |> ignore
        
    member inline this.testCase name ([<InlineIfLambda>] fn: Context -> SuiteContext -> unit) = this.testCaseImpl Expecto.testSuite name fn
    member inline this.ptestCase name ([<InlineIfLambda>] fn: Context -> SuiteContext -> unit) = this.testCaseImpl Expecto.ptestSuite name fn
    member inline this.ftestCase name ([<InlineIfLambda>] fn: Context -> SuiteContext -> unit) = this.testCaseImpl Expecto.ftestSuite name fn
    [<EditorBrowsable(EditorBrowsableState.Never)>]
    member inline this.testSyntaxKindImpl<'T> (suiteFn: string -> (Suite -> unit) -> Suite) kind name ([<InlineIfLambda>] fn: SuiteContext -> Context -> 'T array -> unit) =
        suiteFn name <| fun _ ->
            this.suites
            |> Array.iter (fun suiteContext ->
                testCase suiteContext.Name <| fun test ->
                    match suiteContext.NodeMap.TryGetValue(kind) with
                    | true, nodes when nodes.Count > 0 -> fn suiteContext test (unbox nodes.AsArray)
                    | _ ->
                        let runnable = test.runnable()
                        runnable.title <- "[SKIPPED] No " + kind.Name + " nodes || " + runnable.title
                        test.skip()
                )
        |> _.bail(false)
        |> ignore
    member inline this.testSyntaxKind<'T> kind name ([<InlineIfLambda>] fn: SuiteContext -> Context -> 'T array -> unit) = this.testSyntaxKindImpl Expecto.testSuite kind name fn
    member inline this.ftestSyntaxKind<'T> kind name ([<InlineIfLambda>] fn: SuiteContext -> Context -> 'T array -> unit) = this.testSyntaxKindImpl Expecto.ftestSuite kind name fn
    member inline this.ptestSyntaxKind<'T> kind name ([<InlineIfLambda>] fn: SuiteContext -> Context -> 'T array -> unit) = this.testSyntaxKindImpl Expecto.ptestSuite kind name fn

and SuiteContext = {
    Name: string
    EntryFile: string
    Program: Ts.Program
    Checker: Ts.TypeChecker
    SourceFiles: Ts.SourceFile array
    NodeMap: Dictionary<Ts.SyntaxKind, ResizeArray<obj>>
    Nodes: Ts.Node array
    Types: Lazy<Ts.Type array>
    Symbols: Lazy<Ts.Symbol array>
} with
    static member inline Create (name: string) (entryFile: string) =
        let program = Ts.Program.Create [ entryFile ]
        let checker = program.getTypeChecker()
        let sourceFiles = program.getSourceFiles().AsArray
        let nodeMap = Dictionary<Ts.SyntaxKind, ResizeArray<obj>>()
        let rec crawl = fun node ->
            ts.forEachChild(node, fun node ->
                match nodeMap.TryGetValue(node.kind) with
                | true, nodes -> nodes.Add(node)
                | _ -> nodeMap[node.kind] <- ResizeArray [ box node ]
                crawl node
                JS.undefined
                ) |> ignore
        sourceFiles |> Array.iter crawl
        let nodes = nodeMap.Values |> Seq.collect _.AsArray |> Seq.toArray |> unbox<Ts.Node array>
        {
            EntryFile = entryFile
            Name = name
            Program = program
            Checker = checker
            SourceFiles = sourceFiles
            NodeMap = nodeMap
            Types =
                lazy
                nodes |> Array.filter ts.isTypeNode |> Array.map (unbox<Ts.TypeNode> >> checker.getTypeFromTypeNode)
            Symbols =
                lazy
                nodes |> Array.choose checker.getSymbolAtLocation
            Nodes = nodes
        }

module TypeFlags =
    /// <summary>
    /// Tracks what type flags are never seen in combination with other type flags across the corpus.
    /// </summary>
    let exclusiveMap = Map [
        Ts.TypeFlags.Boolean, [
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
        ]
        Ts.TypeFlags.Enum, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
            Ts.TypeFlags.Narrowable
        ]
        Ts.TypeFlags.BigInt, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.StringLiteral, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.NumberLiteral, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.BooleanLiteral, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.EnumLiteral, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
        ]
        Ts.TypeFlags.BigIntLiteral, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.ESSymbol, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.UniqueESSymbol, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.Void, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
            Ts.TypeFlags.Narrowable
        ]
        Ts.TypeFlags.Undefined, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
            Ts.TypeFlags.Narrowable
        ]
        Ts.TypeFlags.Null, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
            Ts.TypeFlags.Narrowable
        ]
        Ts.TypeFlags.Never, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
            Ts.TypeFlags.Narrowable
        ]
        Ts.TypeFlags.TypeParameter, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.InstantiablePrimitive
        ]
        Ts.TypeFlags.Object, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
        ]
        Ts.TypeFlags.Union, [
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
        ]
        Ts.TypeFlags.Intersection, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
        ]
        Ts.TypeFlags.Index, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
        ]
        Ts.TypeFlags.IndexedAccess, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.InstantiablePrimitive
        ]
        Ts.TypeFlags.Conditional, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiablePrimitive
        ]
        Ts.TypeFlags.Substitution, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiablePrimitive
        ]
        Ts.TypeFlags.NonPrimitive, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.TemplateLiteral, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
        ]
        Ts.TypeFlags.StringMapping, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
        ]
        Ts.TypeFlags.Literal, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.Unit, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.Freshable, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.StringOrNumberLiteral, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.PossiblyFalsy, [
            Ts.TypeFlags.Enum
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
        ]
        Ts.TypeFlags.StringLike, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
        ]
        Ts.TypeFlags.NumberLike, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.BigIntLike, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.BooleanLike, [
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
        ]
        Ts.TypeFlags.EnumLike, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
        ]
        Ts.TypeFlags.ESSymbolLike, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
        ]
        Ts.TypeFlags.VoidLike, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
            Ts.TypeFlags.StructuredOrInstantiable
            Ts.TypeFlags.Narrowable
        ]
        Ts.TypeFlags.UnionOrIntersection, [
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
        ]
        Ts.TypeFlags.StructuredType, [
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Index
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
            Ts.TypeFlags.InstantiablePrimitive
            Ts.TypeFlags.Instantiable
        ]
        Ts.TypeFlags.TypeVariable, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.InstantiablePrimitive
        ]
        Ts.TypeFlags.InstantiableNonPrimitive, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.Index
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.TemplateLiteral
            Ts.TypeFlags.StringMapping
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.StringLike
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.InstantiablePrimitive
        ]
        Ts.TypeFlags.InstantiablePrimitive, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.TypeParameter
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.IndexedAccess
            Ts.TypeFlags.Conditional
            Ts.TypeFlags.Substitution
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
            Ts.TypeFlags.TypeVariable
            Ts.TypeFlags.InstantiableNonPrimitive
        ]
        Ts.TypeFlags.Instantiable, [
            Ts.TypeFlags.Boolean
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.EnumLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.Object
            Ts.TypeFlags.Union
            Ts.TypeFlags.Intersection
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.PossiblyFalsy
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.BooleanLike
            Ts.TypeFlags.EnumLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
            Ts.TypeFlags.UnionOrIntersection
            Ts.TypeFlags.StructuredType
        ]
        Ts.TypeFlags.StructuredOrInstantiable, [
            Ts.TypeFlags.Enum
            Ts.TypeFlags.BigInt
            Ts.TypeFlags.StringLiteral
            Ts.TypeFlags.NumberLiteral
            Ts.TypeFlags.BooleanLiteral
            Ts.TypeFlags.BigIntLiteral
            Ts.TypeFlags.ESSymbol
            Ts.TypeFlags.UniqueESSymbol
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.NonPrimitive
            Ts.TypeFlags.Literal
            Ts.TypeFlags.Unit
            Ts.TypeFlags.Freshable
            Ts.TypeFlags.StringOrNumberLiteral
            Ts.TypeFlags.NumberLike
            Ts.TypeFlags.BigIntLike
            Ts.TypeFlags.ESSymbolLike
            Ts.TypeFlags.VoidLike
        ]
        Ts.TypeFlags.Narrowable, [
            Ts.TypeFlags.Enum
            Ts.TypeFlags.Void
            Ts.TypeFlags.Undefined
            Ts.TypeFlags.Null
            Ts.TypeFlags.Never
            Ts.TypeFlags.VoidLike
        ]
    ]
    let exclusiveMasks =
        exclusiveMap
        |> Map.map (fun _ flags -> flags |> List.reduce (|||))
module ObjectFlags =
    let exclusiveMap: Map<Ts.ObjectFlags, Ts.ObjectFlags list> = Map [

        Ts.ObjectFlags.Class, [
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.Interface, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.ClassOrInterface, [
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.Reference, [
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.Tuple, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.Anonymous, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
        ]
        Ts.ObjectFlags.Mapped, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.Instantiated, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.ObjectLiteral, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.EvolvingArray, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.ReverseMapped, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.JsxAttributes, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.JSLiteral, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.FreshLiteral, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.ArrayLiteral, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.ContainsSpread, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.ObjectRestType, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
        Ts.ObjectFlags.InstantiationExpressionType, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.SingleSignatureType
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
        ]
        Ts.ObjectFlags.SingleSignatureType, [
            Ts.ObjectFlags.Class
            Ts.ObjectFlags.Interface
            Ts.ObjectFlags.Reference
            Ts.ObjectFlags.Tuple
            Ts.ObjectFlags.Anonymous
            Ts.ObjectFlags.Mapped
            Ts.ObjectFlags.Instantiated
            Ts.ObjectFlags.ObjectLiteral
            Ts.ObjectFlags.EvolvingArray
            Ts.ObjectFlags.ObjectLiteralPatternWithComputedProperties
            Ts.ObjectFlags.ReverseMapped
            Ts.ObjectFlags.JsxAttributes
            Ts.ObjectFlags.JSLiteral
            Ts.ObjectFlags.FreshLiteral
            Ts.ObjectFlags.ArrayLiteral
            Ts.ObjectFlags.ClassOrInterface
            Ts.ObjectFlags.ContainsSpread
            Ts.ObjectFlags.ObjectRestType
            Ts.ObjectFlags.InstantiationExpressionType
        ]
    ]
    let exclusiveMasks =
        exclusiveMap
        |> Map.map (fun _ flags -> flags |> List.reduce (|||))