<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TestProject>true</TestProject>
        <DefineConstants>FABLE_TEST</DefineConstants>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>



    <ItemGroup>
        <Compile Include="Spec.fs" />
        <Compile Include="Program.test.fs" />
        <Compile Include="Structural.test.fs" />
        <Folder Include="output\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="EasyBuild.FileSystemProvider" Version="1.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Xantham.Mocha\Xantham.Mocha.fsproj" />
      <ProjectReference Include="..\..\src\Xantham.TypeScript\Xantham.TypeScript.fsproj" />
    </ItemGroup>
</Project>
