<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TestProject>true</TestProject>
        <DefineConstants>FABLE_TEST</DefineConstants>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>



    <ItemGroup>
        <Compile Include="Spec.fs" />
        <Compile Include="Discovery.test.fs" />
        <Compile Include="tests\SourceFile.test.fs" />
        <Compile Include="tests\NodeDeclaration.test.fs" />
        <Compile Include="tests\Identity.test.fs" />
        <Compile Include="tests\Wrappers\Symbol.Kind.test.fs" />
        <Compile Include="tests\Wrappers\Node.Type.test.fs" />
        <Compile Include="tests\Wrappers\Node.Kind.test.fs" />
        <Compile Include="tests\Wrappers\Type.Kind.test.fs" />
        <Compile Include="tests\Wrappers\InlinedProgram.test.fs" />
        <Compile Include="tests\Wrappers\Tracers.test.fs" />
        <Compile Include="tests\Wrappers\TypeParameter.test.fs" />
        <Compile Include="tests\Wrappers\Class.test.fs" />
        <Compile Include="tests\Wrappers\HeritageClause.test.fs" />
        <Compile Include="tests\Wrappers\BindingElement.test.fs" />
        <Compile Include="tests\Wrappers\Parameter.test.fs" />
        <Compile Include="tests\Wrappers\UniqueESSymbol.test.fs" />
        <Compile Include="tests\Wrappers\KeyOf.test.fs" />
        <Compile Include="tests\Declarations\EnumMember.test.fs" />
        <Compile Include="tests\Declarations\Members.test.fs" />
        <Compile Include="tests\Declarations\Parameters.test.fs" />
        <Compile Include="tests\Declarations\TypeReference.test.fs" />
        <Compile Include="tests\Declarations\Identifiers.test.fs" />
        <Compile Include="tests\TypeChecker\TypeChecker.test.fs" />
        <Compile Include="tests\TypeChecker\ObjectFlags.test.fs" />
        <Compile Include="tests\TypeChecker\TypeFlags.test.fs" />
        <Compile Include="tests\TypeChecker\TypeWrapper.test.fs" />
        <Compile Include="Program.test.fs" />
        <Compile Include="Structural.test.fs" />
        <Content Include="output/**/**/*.test.fs.js" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="EasyBuild.FileSystemProvider" Version="1.1.0" />
        <PackageReference Include="Scriptorium.Nib" Version="0.2.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Xantham.Mocha\Xantham.Mocha.fsproj" />
      <ProjectReference Include="..\..\src\Xantham.TypeScript\Xantham.TypeScript.fsproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="output\" />
    </ItemGroup>
</Project>
