// <auto-generated>
//   Generated by Xantham.Generator from intersection-empty-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec IntersectionEmptyLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// The idiom itself: an empty object operand beside a primitive, inside a union.
/// </summary>
type Ease = string

/// <summary>
/// The idiom on its own, outside a union.
/// </summary>
type Loose = string

/// <summary>
/// <c>Record&lt;never, never&gt;</c> is the same empty operand under another name (type-fest's <c>LiteralUnion</c>).
/// </summary>
type Size = string

/// <summary>
/// A number carries the idiom the same way.
/// </summary>
type Weight = float

/// <summary>
/// A real member on the object operand: both operands stand.
/// </summary>
type Counted = obj

/// <summary>
/// A marker-only operand is a brand (§4.6, D11), and the measure survives.
/// </summary>
/// <remarks>A brand over <c>string</c>.</remarks>
[<Measure>]
type UserId

/// <summary>
/// Two object operands, one of them empty: the flattened interface still declares the member.
/// </summary>
[<Interface>]
type Padded =
    abstract width: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (width: float) : Padded = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A reference position, so the reduction is visible where the alias is used.
    /// </summary>
    [<Import("ease", "intersection-empty-lab")>]
    static member ease: Ease = jsNative
