// <auto-generated>
//   Generated by Xantham.Generator from single-case-enum-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec SingleCaseEnumLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type Level =
    | [<CompiledName("high")>] High
    | [<CompiledName("low")>] Low

module Exports =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Error =
        | [<CompiledName("error")>] Error

    [<StringEnum(CaseRules.None)>]
    type Fast =
        | [<CompiledName("fast")>] Fast

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Ok =
        | [<CompiledName("ok")>] Ok

    [<StringEnum(CaseRules.None)>]
    type Slow =
        | [<CompiledName("slow")>] Slow

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("pick", "single-case-enum-lab")>]
    static member pick (kind: Exports.Fast) : float = jsNative
    [<Import("pick", "single-case-enum-lab")>]
    static member pick (kind: Exports.Slow) : string = jsNative
    [<Import("run", "single-case-enum-lab")>]
    static member run (mode: Exports.Ok) : string = jsNative
    [<Import("run", "single-case-enum-lab")>]
    static member run (mode: Exports.Error) : float = jsNative
    [<Import("level", "single-case-enum-lab")>]
    static member level (value: Level) : Level = jsNative
