// <auto-generated>
//   Generated by Xantham.Generator from compiler-lib-ownership-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CompilerLibOwnershipLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS

[<Interface>]
type Item =
    abstract ``when``: TypeScript.Lib.Es.Date with get, set
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``when``: TypeScript.Lib.Es.Date, value: string) : Item = jsNative

type Items = Item[]

[<Interface>]
type Brief =
    abstract ``when``: TypeScript.Lib.Es.Date with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``when``: TypeScript.Lib.Es.Date) : Brief = jsNative

type LocalDate = TypeScript.Lib.Es.Date

[<Interface>]
type Store =
    abstract update: value: Store.Update.Value -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (update: (Store.Update.Value -> unit)) : Store = jsNative

module Store =
    module Update =
        [<Interface>]
        type Value =
            abstract ``when``: TypeScript.Lib.Es.Date option with get, set
            abstract value: string option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?``when``: TypeScript.Lib.Es.Date, ?value: string) : Value = jsNative

type GlobalThis =
    abstract NaN: float with get, set
    abstract Infinity: float with get, set
    /// <summary>
    /// Evaluates JavaScript code and executes it.
    /// </summary>
    /// <remarks>@param x A String value that contains valid JavaScript code.</remarks>
    abstract eval: (string -> obj) with get, set
    /// <summary>
    /// Converts a string to an integer.
    /// </summary>
    /// <remarks>@param string A string to convert into a number.</remarks>
    /// <remarks>
    /// @param
    /// radix A value between 2 and 36 that specifies the base of the number in <c>string</c>.
    /// If this argument is not supplied, strings with a prefix of '0x' are considered hexadecimal.
    /// All other strings are considered decimal.
    /// </remarks>
    abstract parseInt: Func<string, float option, float> with get, set
    /// <summary>
    /// Converts a string to a floating-point number.
    /// </summary>
    /// <remarks>@param string A string that contains a floating-point number.</remarks>
    abstract parseFloat: (string -> float) with get, set
    /// <summary>
    /// Returns a Boolean value that indicates whether a value is the reserved value NaN (not a number).
    /// </summary>
    /// <remarks>@param number A numeric value.</remarks>
    abstract isNaN: (float -> bool) with get, set
    /// <summary>
    /// Determines whether a supplied number is finite.
    /// </summary>
    /// <remarks>@param number Any numeric value.</remarks>
    abstract isFinite: (float -> bool) with get, set
    /// <summary>
    /// Gets the unencoded version of an encoded Uniform Resource Identifier (URI).
    /// </summary>
    /// <remarks>@param encodedURI A value representing an encoded URI.</remarks>
    abstract decodeURI: (string -> string) with get, set
    /// <summary>
    /// Gets the unencoded version of an encoded component of a Uniform Resource Identifier (URI).
    /// </summary>
    /// <remarks>@param encodedURIComponent A value representing an encoded URI component.</remarks>
    abstract decodeURIComponent: (string -> string) with get, set
    /// <summary>
    /// Encodes a text string as a valid Uniform Resource Identifier (URI)
    /// </summary>
    /// <remarks>@param uri A value representing an unencoded URI.</remarks>
    abstract encodeURI: (string -> string) with get, set
    /// <summary>
    /// Encodes a text string as a valid component of a Uniform Resource Identifier (URI).
    /// </summary>
    /// <remarks>@param uriComponent A value representing an unencoded URI component.</remarks>
    abstract encodeURIComponent: (U3<string, float, bool> -> string) with get, set
    /// <summary>
    /// Computes a new string in which certain characters have been replaced by a hexadecimal escape sequence.
    /// </summary>
    /// <remarks>@deprecated A legacy feature for browser compatibility</remarks>
    /// <remarks>@param string A string value</remarks>
    abstract escape: (string -> string) with get, set
    /// <summary>
    /// Computes a new string in which hexadecimal escape sequences are replaced with the character that it represents.
    /// </summary>
    /// <remarks>@deprecated A legacy feature for browser compatibility</remarks>
    /// <remarks>@param string A string value</remarks>
    abstract unescape: (string -> string) with get, set
    /// <summary>
    /// Provides functionality common to all JavaScript objects.
    /// </summary>
    abstract Object: TypeScript.Lib.Es.ObjectConstructor with get, set
    /// <summary>
    /// Creates a new function.
    /// </summary>
    abstract Function: TypeScript.Lib.Es.FunctionConstructor with get, set
    /// <summary>
    /// Allows manipulation and formatting of text strings and determination and location of substrings within strings.
    /// </summary>
    abstract String: TypeScript.Lib.Es.StringConstructor with get, set
    abstract Boolean: TypeScript.Lib.Es.BooleanConstructor with get, set
    /// <summary>
    /// An object that represents a number of any kind. All JavaScript numbers are 64-bit floating-point numbers.
    /// </summary>
    abstract Number: TypeScript.Lib.Es.NumberConstructor with get, set
    /// <summary>
    /// An intrinsic object that provides basic mathematics functionality and constants.
    /// </summary>
    abstract Math: TypeScript.Lib.Es.Math with get, set
    /// <summary>
    /// Enables basic storage and retrieval of dates and times.
    /// </summary>
    abstract Date: TypeScript.Lib.Es.DateConstructor with get, set
    abstract RegExp: TypeScript.Lib.Es.RegExpConstructor with get, set
    abstract Error: TypeScript.Lib.Es.ErrorConstructor with get, set
    abstract EvalError: TypeScript.Lib.Es.EvalErrorConstructor with get, set
    abstract RangeError: TypeScript.Lib.Es.RangeErrorConstructor with get, set
    abstract ReferenceError: TypeScript.Lib.Es.ReferenceErrorConstructor with get, set
    abstract SyntaxError: TypeScript.Lib.Es.SyntaxErrorConstructor with get, set
    abstract TypeError: TypeScript.Lib.Es.TypeErrorConstructor with get, set
    abstract URIError: TypeScript.Lib.Es.URIErrorConstructor with get, set
    /// <summary>
    /// An intrinsic object that provides functions to convert JavaScript values to and from the JavaScript Object Notation (JSON) format.
    /// </summary>
    abstract JSON: TypeScript.Lib.Es.JSON with get, set
    abstract Array: TypeScript.Lib.Es.ArrayConstructor with get, set
    /// <summary>
    /// Represents a raw buffer of binary data, which is used to store data for the
    /// different typed arrays. ArrayBuffers cannot be read from or written to directly,
    /// but can be passed to a typed array or DataView Object to interpret the raw
    /// buffer as needed.
    /// </summary>
    abstract ArrayBuffer: TypeScript.Lib.Es.ArrayBufferConstructor with get, set
    abstract DataView: TypeScript.Lib.Es.DataViewConstructor with get, set
    /// <summary>
    /// A typed array of 8-bit integer values. The contents are initialized to 0. If the requested
    /// number of bytes could not be allocated an exception is raised.
    /// </summary>
    abstract Int8Array: TypeScript.Lib.Es.Int8ArrayConstructor with get, set
    /// <summary>
    /// A typed array of 8-bit unsigned integer values. The contents are initialized to 0. If the
    /// requested number of bytes could not be allocated an exception is raised.
    /// </summary>
    abstract Uint8Array: TypeScript.Lib.Es.Uint8ArrayConstructor with get, set
    /// <summary>
    /// A typed array of 8-bit unsigned integer (clamped) values. The contents are initialized to 0.
    /// If the requested number of bytes could not be allocated an exception is raised.
    /// </summary>
    abstract Uint8ClampedArray: TypeScript.Lib.Es.Uint8ClampedArrayConstructor with get, set
    /// <summary>
    /// A typed array of 16-bit signed integer values. The contents are initialized to 0. If the
    /// requested number of bytes could not be allocated an exception is raised.
    /// </summary>
    abstract Int16Array: TypeScript.Lib.Es.Int16ArrayConstructor with get, set
    /// <summary>
    /// A typed array of 16-bit unsigned integer values. The contents are initialized to 0. If the
    /// requested number of bytes could not be allocated an exception is raised.
    /// </summary>
    abstract Uint16Array: TypeScript.Lib.Es.Uint16ArrayConstructor with get, set
    /// <summary>
    /// A typed array of 32-bit signed integer values. The contents are initialized to 0. If the
    /// requested number of bytes could not be allocated an exception is raised.
    /// </summary>
    abstract Int32Array: TypeScript.Lib.Es.Int32ArrayConstructor with get, set
    /// <summary>
    /// A typed array of 32-bit unsigned integer values. The contents are initialized to 0. If the
    /// requested number of bytes could not be allocated an exception is raised.
    /// </summary>
    abstract Uint32Array: TypeScript.Lib.Es.Uint32ArrayConstructor with get, set
    /// <summary>
    /// A typed array of 32-bit float values. The contents are initialized to 0. If the requested number
    /// of bytes could not be allocated an exception is raised.
    /// </summary>
    abstract Float32Array: TypeScript.Lib.Es.Float32ArrayConstructor with get, set
    /// <summary>
    /// A typed array of 64-bit float values. The contents are initialized to 0. If the requested
    /// number of bytes could not be allocated an exception is raised.
    /// </summary>
    abstract Float64Array: TypeScript.Lib.Es.Float64ArrayConstructor with get, set
    abstract Intl: TypeScript.Lib.Es.Intl with get, set
    abstract currentItem: Item with get, set
    abstract inspect: (Item[] -> Brief) with get, set
    abstract windowLike: WindowLike with get, set
    abstract globalThis: GlobalThis
    abstract undefined: unit

[<Interface>]
type WindowLike =
    abstract self: WindowLike.Self
    [<ParamObject; Emit("$0")>]
    static member Create (self: WindowLike.Self) : WindowLike = jsNative

module WindowLike =
    type Self =
        inherit WindowLike
        inherit GlobalThis

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
[<Global("globalThis")>]
type Exports =
    static member currentItem
        with get (): Item = jsNative
        and set (_: Item): unit = jsNative
    [<Global("inspect")>]
    static member inspect (items: Item[]) : Brief = jsNative
    static member windowLike
        with get (): WindowLike = jsNative
        and set (_: WindowLike): unit = jsNative
    static member NaN
        with get (): float = jsNative
        and set (_: float): unit = jsNative
    static member Infinity
        with get (): float = jsNative
        and set (_: float): unit = jsNative
    /// <summary>
    /// Evaluates JavaScript code and executes it.
    /// </summary>
    /// <remarks>@param x A String value that contains valid JavaScript code.</remarks>
    [<Global("eval")>]
    static member eval (x: string) : obj = jsNative
    /// <summary>
    /// Converts a string to an integer.
    /// </summary>
    /// <remarks>@param string A string to convert into a number.</remarks>
    /// <remarks>
    /// @param
    /// radix A value between 2 and 36 that specifies the base of the number in <c>string</c>.
    /// If this argument is not supplied, strings with a prefix of '0x' are considered hexadecimal.
    /// All other strings are considered decimal.
    /// </remarks>
    [<Global("parseInt")>]
    static member parseInt (string: string, ?radix: float) : float = jsNative
    /// <summary>
    /// Converts a string to a floating-point number.
    /// </summary>
    /// <remarks>@param string A string that contains a floating-point number.</remarks>
    [<Global("parseFloat")>]
    static member parseFloat (string: string) : float = jsNative
    /// <summary>
    /// Returns a Boolean value that indicates whether a value is the reserved value NaN (not a number).
    /// </summary>
    /// <remarks>@param number A numeric value.</remarks>
    [<Global("isNaN")>]
    static member isNaN (number: float) : bool = jsNative
    /// <summary>
    /// Determines whether a supplied number is finite.
    /// </summary>
    /// <remarks>@param number Any numeric value.</remarks>
    [<Global("isFinite")>]
    static member isFinite (number: float) : bool = jsNative
    /// <summary>
    /// Gets the unencoded version of an encoded Uniform Resource Identifier (URI).
    /// </summary>
    /// <remarks>@param encodedURI A value representing an encoded URI.</remarks>
    [<Global("decodeURI")>]
    static member decodeURI (encodedURI: string) : string = jsNative
    /// <summary>
    /// Gets the unencoded version of an encoded component of a Uniform Resource Identifier (URI).
    /// </summary>
    /// <remarks>@param encodedURIComponent A value representing an encoded URI component.</remarks>
    [<Global("decodeURIComponent")>]
    static member decodeURIComponent (encodedURIComponent: string) : string = jsNative
    /// <summary>
    /// Encodes a text string as a valid Uniform Resource Identifier (URI)
    /// </summary>
    /// <remarks>@param uri A value representing an unencoded URI.</remarks>
    [<Global("encodeURI")>]
    static member encodeURI (uri: string) : string = jsNative
    /// <summary>
    /// Encodes a text string as a valid component of a Uniform Resource Identifier (URI).
    /// </summary>
    /// <remarks>@param uriComponent A value representing an unencoded URI component.</remarks>
    [<Global("encodeURIComponent")>]
    static member encodeURIComponent (uriComponent: U3<string, float, bool>) : string = jsNative
    /// <summary>
    /// Computes a new string in which certain characters have been replaced by a hexadecimal escape sequence.
    /// </summary>
    /// <remarks>@deprecated A legacy feature for browser compatibility</remarks>
    /// <remarks>@param string A string value</remarks>
    [<Global("escape")>]
    static member escape (string: string) : string = jsNative
    /// <summary>
    /// Computes a new string in which hexadecimal escape sequences are replaced with the character that it represents.
    /// </summary>
    /// <remarks>@deprecated A legacy feature for browser compatibility</remarks>
    /// <remarks>@param string A string value</remarks>
    [<Global("unescape")>]
    static member unescape (string: string) : string = jsNative
    /// <summary>
    /// Provides functionality common to all JavaScript objects.
    /// </summary>
    [<Global("Object")>]
    static member Object () : obj = jsNative
    /// <summary>
    /// Provides functionality common to all JavaScript objects.
    /// </summary>
    [<Global("Object")>]
    static member Object (value: obj) : obj = jsNative
    /// <summary>
    /// Creates a new function.
    /// </summary>
    [<Global("Function")>]
    static member Function ([<ParamArray>] args: string[]) : TypeScript.Lib.Es.Function = jsNative
    /// <summary>
    /// Allows manipulation and formatting of text strings and determination and location of substrings within strings.
    /// </summary>
    [<Global("String")>]
    static member String (?value: obj) : string = jsNative
    [<Global("Boolean")>]
    static member Boolean<'T> (?value: 'T) : bool = jsNative
    /// <summary>
    /// An object that represents a number of any kind. All JavaScript numbers are 64-bit floating-point numbers.
    /// </summary>
    [<Global("Number")>]
    static member Number (?value: obj) : float = jsNative
    /// <summary>
    /// An intrinsic object that provides basic mathematics functionality and constants.
    /// </summary>
    static member Math
        with get (): TypeScript.Lib.Es.Math = jsNative
        and set (_: TypeScript.Lib.Es.Math): unit = jsNative
    /// <summary>
    /// Enables basic storage and retrieval of dates and times.
    /// </summary>
    [<Global("Date")>]
    static member Date () : string = jsNative
    [<Global("RegExp")>]
    static member RegExp (pattern: U2<string, TypeScript.Lib.Es.RegExp>) : TypeScript.Lib.Es.RegExp = jsNative
    [<Global("RegExp")>]
    static member RegExp (pattern: string, ?flags: string) : TypeScript.Lib.Es.RegExp = jsNative
    [<Global("Error")>]
    static member Error (?message: string) : TypeScript.Lib.Es.Error = jsNative
    [<Global("EvalError")>]
    static member EvalError (?message: string) : TypeScript.Lib.Es.EvalError = jsNative
    [<Global("RangeError")>]
    static member RangeError (?message: string) : TypeScript.Lib.Es.RangeError = jsNative
    [<Global("ReferenceError")>]
    static member ReferenceError (?message: string) : TypeScript.Lib.Es.ReferenceError = jsNative
    [<Global("SyntaxError")>]
    static member SyntaxError (?message: string) : TypeScript.Lib.Es.SyntaxError = jsNative
    [<Global("TypeError")>]
    static member TypeError (?message: string) : TypeScript.Lib.Es.TypeError = jsNative
    [<Global("URIError")>]
    static member URIError (?message: string) : TypeScript.Lib.Es.URIError = jsNative
    /// <summary>
    /// An intrinsic object that provides functions to convert JavaScript values to and from the JavaScript Object Notation (JSON) format.
    /// </summary>
    static member JSON
        with get (): TypeScript.Lib.Es.JSON = jsNative
        and set (_: TypeScript.Lib.Es.JSON): unit = jsNative
    [<Global("Array")>]
    static member Array (?arrayLength: float) : obj[] = jsNative
    [<Global("Array")>]
    static member Array<'T> (arrayLength: float) : 'T[] = jsNative
    [<Global("Array")>]
    static member Array<'T> ([<ParamArray>] items: 'T[]) : 'T[] = jsNative
    /// <summary>
    /// Represents a raw buffer of binary data, which is used to store data for the
    /// different typed arrays. ArrayBuffers cannot be read from or written to directly,
    /// but can be passed to a typed array or DataView Object to interpret the raw
    /// buffer as needed.
    /// </summary>
    static member ArrayBuffer
        with get (): TypeScript.Lib.Es.ArrayBufferConstructor = jsNative
        and set (_: TypeScript.Lib.Es.ArrayBufferConstructor): unit = jsNative
    static member DataView
        with get (): TypeScript.Lib.Es.DataViewConstructor = jsNative
        and set (_: TypeScript.Lib.Es.DataViewConstructor): unit = jsNative
    /// <summary>
    /// A typed array of 8-bit integer values. The contents are initialized to 0. If the requested
    /// number of bytes could not be allocated an exception is raised.
    /// </summary>
    static member Int8Array
        with get (): TypeScript.Lib.Es.Int8ArrayConstructor = jsNative
        and set (_: TypeScript.Lib.Es.Int8ArrayConstructor): unit = jsNative
    /// <summary>
    /// A typed array of 8-bit unsigned integer values. The contents are initialized to 0. If the
    /// requested number of bytes could not be allocated an exception is raised.
    /// </summary>
    static member Uint8Array
        with get (): TypeScript.Lib.Es.Uint8ArrayConstructor = jsNative
        and set (_: TypeScript.Lib.Es.Uint8ArrayConstructor): unit = jsNative
    /// <summary>
    /// A typed array of 8-bit unsigned integer (clamped) values. The contents are initialized to 0.
    /// If the requested number of bytes could not be allocated an exception is raised.
    /// </summary>
    static member Uint8ClampedArray
        with get (): TypeScript.Lib.Es.Uint8ClampedArrayConstructor = jsNative
        and set (_: TypeScript.Lib.Es.Uint8ClampedArrayConstructor): unit = jsNative
    /// <summary>
    /// A typed array of 16-bit signed integer values. The contents are initialized to 0. If the
    /// requested number of bytes could not be allocated an exception is raised.
    /// </summary>
    static member Int16Array
        with get (): TypeScript.Lib.Es.Int16ArrayConstructor = jsNative
        and set (_: TypeScript.Lib.Es.Int16ArrayConstructor): unit = jsNative
    /// <summary>
    /// A typed array of 16-bit unsigned integer values. The contents are initialized to 0. If the
    /// requested number of bytes could not be allocated an exception is raised.
    /// </summary>
    static member Uint16Array
        with get (): TypeScript.Lib.Es.Uint16ArrayConstructor = jsNative
        and set (_: TypeScript.Lib.Es.Uint16ArrayConstructor): unit = jsNative
    /// <summary>
    /// A typed array of 32-bit signed integer values. The contents are initialized to 0. If the
    /// requested number of bytes could not be allocated an exception is raised.
    /// </summary>
    static member Int32Array
        with get (): TypeScript.Lib.Es.Int32ArrayConstructor = jsNative
        and set (_: TypeScript.Lib.Es.Int32ArrayConstructor): unit = jsNative
    /// <summary>
    /// A typed array of 32-bit unsigned integer values. The contents are initialized to 0. If the
    /// requested number of bytes could not be allocated an exception is raised.
    /// </summary>
    static member Uint32Array
        with get (): TypeScript.Lib.Es.Uint32ArrayConstructor = jsNative
        and set (_: TypeScript.Lib.Es.Uint32ArrayConstructor): unit = jsNative
    /// <summary>
    /// A typed array of 32-bit float values. The contents are initialized to 0. If the requested number
    /// of bytes could not be allocated an exception is raised.
    /// </summary>
    static member Float32Array
        with get (): TypeScript.Lib.Es.Float32ArrayConstructor = jsNative
        and set (_: TypeScript.Lib.Es.Float32ArrayConstructor): unit = jsNative
    /// <summary>
    /// A typed array of 64-bit float values. The contents are initialized to 0. If the requested
    /// number of bytes could not be allocated an exception is raised.
    /// </summary>
    static member Float64Array
        with get (): TypeScript.Lib.Es.Float64ArrayConstructor = jsNative
        and set (_: TypeScript.Lib.Es.Float64ArrayConstructor): unit = jsNative
    [<Global("Intl")>]
    static member Intl: TypeScript.Lib.Es.Intl = jsNative
    [<Global("globalThis")>]
    static member globalThis: GlobalThis = jsNative
