// <auto-generated>
//   Generated by Xantham.Generator from hook-interface-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec HookInterfaceLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// The value every hook below is handed.
/// </summary>
[<Interface>]
type Signal =
    abstract label: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (label: string) : Signal = jsNative

/// <summary>
/// An entrypoint a consumer derives from. <c>run</c> is the mandatory slot; <c>fetch</c> and <c>alarm</c> are
/// the platform's lifecycle hooks, called where the object provides them.
/// </summary>
[<Import("Station", "hook-lab:runtime"); AbstractClass>]
type Station (label: string) =
    member _.label: string = jsNative
    abstract run: signal: Signal -> string
    /// <summary>
    /// An optional property rather than an optional method: nothing calls this one.
    /// </summary>
    member _.tag
        with get (): string option = jsNative
        and set (_: string option): unit = jsNative

module Station =
    [<Interface>]
    type IAlarmHandler =
        abstract alarm: unit -> string
        [<ParamObject; Emit("$0")>]
        static member Create (alarm: Func<string>) : IAlarmHandler = jsNative

    [<Interface>]
    type IFetchHandler =
        abstract fetch: signal: Signal -> string
        [<ParamObject; Emit("$0")>]
        static member Create (fetch: Func<Signal, string>) : IFetchHandler = jsNative

/// <summary>
/// An entrypoint whose hook mentions the class's own type parameter.
/// </summary>
[<Import("Relay", "hook-lab:runtime"); AbstractClass>]
type Relay<'T> (seed: 'T) =
    member _.seed: 'T = jsNative

module Relay =
    [<Interface>]
    type IForwardHandler<'T> =
        abstract forward: value: 'T -> 'T
        [<ParamObject; Emit("$0")>]
        static member Create (forward: Func<'T, 'T>) : IForwardHandler<'T> = jsNative

/// <summary>
/// An exported class that is neither abstract nor derived: the interface form, where an
/// optional method is an option property because there is no class to hang a hook off.
/// </summary>
[<Interface>]
type Hub =
    abstract depth: float
    abstract probe: Func<Signal, string> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (depth: float, ?probe: Func<Signal, string>) : Hub = jsNative

/// <summary>
/// A class whose base this run declares. An F# interface admits no <c>inherit</c> of a class, so
/// this keeps the interface form and its inherited optional method stays an option.
/// </summary>
[<Interface>]
type Annex =
    inherit Hub
    abstract tag: string
    abstract depth: float
    abstract probe: Func<Signal, string> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (tag: string, depth: float, ?probe: Func<Signal, string>) : Annex = jsNative

/// <summary>
/// A plain interface carrying an optional method. Nothing derives from it, so the method stays
/// an option property.
/// </summary>
[<Interface>]
type Listener =
    abstract ping: Func<Signal, string> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?ping: Func<Signal, string>) : Listener = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// An entrypoint a consumer derives from. <c>run</c> is the mandatory slot; <c>fetch</c> and <c>alarm</c> are
    /// the platform's lifecycle hooks, called where the object provides them.
    /// </summary>
    [<Import("Station", "hook-lab:runtime"); EmitConstructor>]
    static member Station (label: string) : Station = jsNative
    /// <summary>
    /// An entrypoint whose hook mentions the class's own type parameter.
    /// </summary>
    [<Import("Relay", "hook-lab:runtime"); EmitConstructor>]
    static member Relay<'T> (seed: 'T) : Relay<'T> = jsNative
    /// <summary>
    /// An exported class that is neither abstract nor derived: the interface form, where an
    /// optional method is an option property because there is no class to hang a hook off.
    /// </summary>
    [<Import("Hub", "hook-lab:runtime"); EmitConstructor>]
    static member Hub (depth: float) : Hub = jsNative
    /// <summary>
    /// A class whose base this run declares. An F# interface admits no <c>inherit</c> of a class, so
    /// this keeps the interface form and its inherited optional method stays an option.
    /// </summary>
    [<Import("Annex", "hook-lab:runtime"); EmitConstructor>]
    static member Annex (depth: float, tag: string) : Annex = jsNative
