module Xantham.Cli.Spec
// <auto-generated>
//  DO-NOT-EDIT:
//  This file is generated by build.fsx, and pins the version to the one in package.json.
//  You can only edit the version in package.json, not this file.
// </auto-generated>

[<Literal>]
let tscVersion = "^7.1.0-dev.20260902.1"
