// <auto-generated>
//   Generated by Xantham.Generator from generics-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec GenericsLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// A generic interface that is not exported: it is reached only through instantiations.
/// </summary>
[<Interface>]
type Ready<'T> =
    abstract latest: 'T with get, set
    abstract settled: bool with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (latest: 'T, settled: bool) : Ready<'T> = jsNative

/// <summary>
/// A second one, so the union below has two generic arms.
/// </summary>
[<Interface>]
type Pending<'T> =
    abstract previous: 'T option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?previous: 'T) : Pending<'T> = jsNative

/// <summary>
/// Two instantiations of one generic declaration - the arms are applications of it, not re-expansions.
/// </summary>
type Resource<'T> = U2<Pending<'T>, Ready<'T>>

/// <summary>
/// A concrete instantiation of the same declaration.
/// </summary>
type StringResource = Ready<string>

/// <summary>
/// A generic union alias: the parameter is bound on the alias, and the arms read it.
/// </summary>
type Ref<'T> = U2<'T, ('T -> unit)>

/// <summary>
/// A generic union alias with a nullish arm, hoisted to option around the erased union.
/// </summary>
type Source<'S> = U2<'S, (unit -> 'S)> option

module Each =
    [<Interface>]
    type Props<'T, 'U> =
        abstract items: 'T[] with get, set
        abstract fallback: string option with get, set
        abstract render: Func<'T, float, 'U> with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (items: 'T[], render: Func<'T, float, 'U>, ?fallback: string) : Props<'T, 'U> = jsNative

/// <summary>
/// An anonymous object type inside a generic alias.
/// </summary>
type Handle<'T> = (unit -> 'T) * Handle.Item<'T>

module Handle =
    [<Interface>]
    type Item<'T> =
        abstract set: ('T -> unit) with get, set
        abstract reset: unit -> unit
        [<ParamObject; Emit("$0")>]
        static member Create (set: ('T -> unit), reset: (unit -> unit)) : Item<'T> = jsNative

/// <summary>
/// A named bound: the only kind of constraint F# can state.
/// </summary>
[<Interface>]
type Named =
    abstract name: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (name: string) : Named = jsNative

/// <summary>
/// A constrained parameter that is not the last: F# writes one <c>when</c> clause after the parameter list.
/// </summary>
[<Interface>]
type Labelled<'T, 'U when 'T :> Named> =
    abstract subject: 'T with get, set
    abstract label: 'U with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (subject: 'T, label: 'U) : Labelled<'T, 'U> = jsNative

/// <summary>
/// An application of a constrained generic whose argument is a <c>typekeyof</c> result: the argument is written as the constraint.
/// </summary>
[<Interface>]
type Registry<'M> =
    abstract pick<'R>: key: typekeyof<'M, 'R> -> Labelled<Named, typekeyof<'M, 'R>>
    [<ParamObject; Emit("$0")>]
    static member Create (pick: (typekeyof<'M, 'R> -> Labelled<Named, typekeyof<'M, 'R>>)) : Registry<'M> = jsNative

/// <summary>
/// An index-only anonymous object, written in the compiler lib: an interface of one indexer, not <c>obj</c>.
/// </summary>
[<Interface>]
type Manifest =
    abstract flags: Manifest.Flags with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (flags: Manifest.Flags) : Manifest = jsNative

module Manifest =
    type Flags =
        [<EmitIndexer>]
        abstract Item: string -> bool with get, set

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// An anonymous object type inside a generic function - it binds nothing itself and reads the function's parameters.
    /// </summary>
    [<Import("each", "generics-lab")>]
    static member each<'T, 'U> (props: Each.Props<'T, 'U>) : 'U[] = jsNative
    /// <summary>
    /// An optional parameter ahead of a rest parameter: F# has no tail for the <c>?</c>, so it stays required, of option type.
    /// </summary>
    [<Import("schedule", "generics-lab")>]
    static member schedule (callback: (float[] -> unit), delay: float option, [<ParamArray>] args: float[]) : float = jsNative
