// <auto-generated>
//   Generated by Xantham.Generator from readonly-enums-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec ReadonlyEnumsLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Permissions =
    abstract access: Permissions.Access with get, set
    abstract waiting: Permissions.Waiting with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (access: Permissions.Access, waiting: Permissions.Waiting) : Permissions = jsNative

[<Interface>]
type View =
    abstract access: Permissions.Access
    abstract waiting: Permissions.Waiting
    [<ParamObject; Emit("$0")>]
    static member Create (access: Permissions.Access, waiting: Permissions.Waiting) : View = jsNative

module Permissions =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Access =
        | [<CompiledName("ALLOW")>] Allow
        | [<CompiledName("DENY")>] Deny

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Waiting =
        | [<CompiledName("AUTO")>] Auto
        | [<CompiledName("MANUAL")>] Manual
