/**
 * Parses the vendored `packages/typescript/src/enums/*.enum.ts` files.
 *
 * These are not hand-written upstream either: each carries a `Code generated by Herebyfile.mjs
 * generate:enums from tsc/internal/...` banner, so they are a machine-produced view of the Go
 * flag declarations with the Go name prefix stripped (`SymbolFlags.Property`, not
 * `SymbolFlagsProperty`). Reading them costs a small const-expression evaluator; reading the Go
 * directly would cost a Go parser and a 64 KB `types.go` in the vendor tree.
 *
 * Kept apart from the emitter for the same reason `kinds.mts` is: the values have to be right,
 * and a wrong one is silent.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const enumDir = path.join(here, "upstream", "packages", "typescript", "src", "enums");

export interface EnumMember {
  name: string;
  /** The expression as upstream spelled it, kept for the emitted comment on composites. */
  expression: string;
  /** Evaluated as uint32, or the string for a string-valued enum. */
  value: number | string;
  /** True when the expression names other members rather than standing alone. */
  composite: boolean;
  /** True when upstream declared this as `1 << n`, i.e. it defines a bit rather than combining. */
  bit: boolean;
  /** The parsed expression, for rendering as F#. Absent on a string enum's members. */
  tree?: Expr;
}

export interface EnumType {
  name: string;
  /** The Go file upstream generated this from, off the banner. */
  origin: string;
  members: EnumMember[];
  /** String-valued enums cannot be F# enums; they emit as literals. */
  isString: boolean;
}

// ────────────────────────────────────────────────────────────────────────────
// The const evaluator
// ────────────────────────────────────────────────────────────────────────────

/** The parsed shape of a member's value expression. */
type Expr =
  | { kind: "literal"; value: number }
  | { kind: "member"; name: string }
  | { kind: "unary"; operator: "~" | "-"; operand: Expr }
  | { kind: "binary"; operator: string; left: Expr; right: Expr };

/**
 * A recursive-descent reader over the subset upstream actually emits: integer literals, member
 * references, `<<`, `-`, `|`, `&`, `^`, `~` and parentheses. Precedence follows TypeScript, so
 * `A | B & C` groups as `A | (B & C)` exactly as it does upstream.
 *
 * This is a parser rather than a fold because the tree is needed twice: once to evaluate, and
 * once to render as F#. Rendering cannot reuse upstream's text, because F# puts `|||` and `&&&`
 * at the *same* precedence and associates left, so `A ||| B &&& C` groups as `(A ||| B) &&& C` -
 * a different number, silently. The renderer parenthesises everything for that reason.
 */
function parse(expression: string, context: string): Expr {
  const tokens = expression.match(/<<|>>|[|&^~()+\-]|0[xX][0-9a-fA-F]+|\d+|[A-Za-z_]\w*/g) ?? [];
  let at = 0;
  const peek = () => tokens[at];
  const take = () => tokens[at++];

  const primary = (): Expr => {
    const token = take();
    if (token === undefined) throw new Error(`${context}: expression ended early`);
    if (token === "(") {
      const inner = or();
      if (take() !== ")") throw new Error(`${context}: unbalanced parentheses`);
      return inner;
    }
    if (/^\d/.test(token)) return { kind: "literal", value: Number(token) >>> 0 };
    return { kind: "member", name: token };
  };

  const unary = (): Expr =>
    peek() === "~" || peek() === "-"
      ? { kind: "unary", operator: take() as "~" | "-", operand: unary() }
      : primary();

  /** One level of a left-associative infix chain. */
  const chain = (operators: string[], next: () => Expr) => (): Expr => {
    let left = next();
    while (operators.includes(peek()!)) left = { kind: "binary", operator: take()!, left, right: next() };
    return left;
  };

  const additive = chain(["+", "-"], unary);
  const shift = chain(["<<", ">>"], additive);
  const and = chain(["&"], shift);
  const xor = chain(["^"], and);
  const or = chain(["|"], xor);

  const parsed = or();
  if (at !== tokens.length) throw new Error(`${context}: trailing input after ${tokens[at]}`);
  return parsed;
}

/**
 * Everything is uint32, matching the Go declarations: `~Decorator` and `1 << 30` both rely on it,
 * and evaluating them as signed would silently produce a negative F# literal.
 */
function evaluate(expression: Expr, resolved: Map<string, number>, context: string): number {
  switch (expression.kind) {
    case "literal":
      return expression.value;
    case "member":
      if (!resolved.has(expression.name))
        throw new Error(`${context}: ${expression.name} is not a member declared above it`);
      return resolved.get(expression.name)!;
    case "unary": {
      const operand = evaluate(expression.operand, resolved, context);
      return (expression.operator === "~" ? ~operand : -operand) >>> 0;
    }
    case "binary": {
      const left = evaluate(expression.left, resolved, context);
      const right = evaluate(expression.right, resolved, context);
      switch (expression.operator) {
        case "|": return (left | right) >>> 0;
        case "&": return (left & right) >>> 0;
        case "^": return (left ^ right) >>> 0;
        case "<<": return (left << right) >>> 0;
        case ">>": return (left >>> right) >>> 0;
        case "+": return (left + right) >>> 0;
        case "-": return (left - right) >>> 0;
        default: throw new Error(`${context}: unknown operator ${expression.operator}`);
      }
    }
  }
}

const FSHARP_OPERATORS: Record<string, string> = {
  "|": "|||", "&": "&&&", "^": "^^^", "<<": "<<<", ">>": ">>>", "+": "+", "-": "-",
};

/**
 * Renders as F#, fully parenthesised, with member references spelled by `spell` - the caller
 * decides whether a name is an enum case (`SymbolFlags.Property`) or an earlier literal in the
 * same module (`Variable`, bare, because the qualified form would resolve against the type and
 * find nothing).
 *
 * Returns `null` for an expression that cannot be typed as the enum: a bare integer has no enum
 * type, so `(1 << 30) - 1` has to stay an enum case with its evaluated value.
 */
export function render(expression: Expr, spell: (name: string) => string): string | null {
  switch (expression.kind) {
    case "literal":
      return null;
    case "member":
      return spell(expression.name);
    case "unary": {
      const operand = render(expression.operand, spell);
      return operand && `(${expression.operator === "~" ? "~~~" : "-"}${operand})`;
    }
    case "binary": {
      const operator = FSHARP_OPERATORS[expression.operator];
      const left = render(expression.left, spell);
      const right = render(expression.right, spell);
      return operator && left && right ? `(${left} ${operator} ${right})` : null;
    }
  }
}

// ────────────────────────────────────────────────────────────────────────────
// The file reader
// ────────────────────────────────────────────────────────────────────────────

const BANNER = /^\/\/ Code generated by .* from (\S+)\. DO NOT EDIT\.$/;
const DECLARATION = /^export enum (\w+) \{$/;
const MEMBER = /^ {4}(\w+) = (.+),$/;

/**
 * Strict on purpose. These files have exactly one shape today - banner, declaration, one member
 * per line, close - and all twenty conform. A file that stops conforming is an upstream change
 * worth stopping for, not one worth guessing at.
 */
export function readEnum(file: string): EnumType {
  const lines = fs.readFileSync(path.join(enumDir, file), "utf8").split(/\r?\n/);
  let at = 0;

  let origin = "unrecorded";
  const banner = BANNER.exec(lines[at] ?? "");
  if (banner) (origin = banner[1]), at++;
  while (lines[at] === "") at++;

  const declaration = DECLARATION.exec(lines[at] ?? "");
  if (!declaration) throw new Error(`${file}:${at + 1}: expected an enum declaration, got ${JSON.stringify(lines[at])}`);
  at++;

  const members: EnumMember[] = [];
  const resolved = new Map<string, number>();
  let isString = false;

  for (; at < lines.length && lines[at] !== "}"; at++) {
    const line = lines[at];
    if (line === "") continue;
    const member = MEMBER.exec(line);
    if (!member) throw new Error(`${file}:${at + 1}: not a member declaration: ${JSON.stringify(line)}`);

    const [, name, expression] = member;
    const literal = /^"([^"]*)"$/.exec(expression);
    if (literal) {
      isString = true;
      members.push({ name, expression, value: literal[1], composite: false, bit: false });
      continue;
    }
    if (isString) throw new Error(`${file}:${at + 1}: ${name} mixes a numeric value into a string enum`);

    const tree = parse(expression, `${file}:${at + 1}`);
    const value = evaluate(tree, resolved, `${file}:${at + 1}`);
    resolved.set(name, value);
    members.push({
      name,
      expression,
      value,
      composite: /[A-Za-z_]/.test(expression),
      bit: /^1 << \d+$/.test(expression),
      tree,
    });
  }

  if (lines[at] !== "}") throw new Error(`${file}: enum body is not closed`);
  return { name: declaration[1], origin, members, isString };
}

/**
 * The enums vendored for Wire, in emission order: the answers the checker gives back, then the
 * two words `Ast` reads off a node, then the small ones phase 4 left as bare `uint32`.
 *
 * `syntaxKind.enum.ts` is deliberately absent - it is vendored as an oracle for the ordinals
 * `kinds.mts` derives positionally, not to be emitted, since `AstKind.SyntaxKind` already exists
 * and two of them would be two sources of truth.
 */
export const VENDORED = [
  "symbolFlags", "checkFlags", "typeFlags", "objectFlags", "signatureFlags", "elementFlags",
  "signatureKind", "typePredicateKind", "nodeBuilderFlags", "internalSymbolName",
  "nodeFlags", "tokenFlags", "modifierFlags",
  "scriptKind", "languageVariant",
  "spanMapKind", "spanMapFeature", "spanMapFidelity", "diagnosticDirectivePolicy",
  "commentDirectiveType",
] as const;

export function readEnums(): EnumType[] {
  return VENDORED.map(name => readEnum(`${name}.enum.ts`));
}

/** The published `SyntaxKind`, for cross-checking the positional derivation in `kinds.mts`. */
export function syntaxKindOracle(): Map<string, number> {
  const published = readEnum("syntaxKind.enum.ts");
  return new Map(published.members.map(member => [member.name, member.value as number]));
}
