/**
 * Shared F# emission helpers.
 *
 * `tools/proto-gen/generate.mjs` predates this module and keeps its own copies; it is left
 * alone so that regenerating the proto surface stays a no-op. If the two are ever unified,
 * the check is that the three `Proto*.generated.fs` files come back byte-identical.
 */

/**
 * Identifiers that have to be escaped to survive as F# names. Deliberately broader than the
 * language's reserved set - `process`, `file` and friends are not keywords but shadow things
 * that callers expect to be able to use.
 */
export const KEYWORDS = new Set([
  // Reserved for future use: a warning today, an error tomorrow.
  "atomic", "break", "checked", "constraint", "constructor", "continue", "eager", "event",
  "external", "functor", "include", "method", "mixin", "object", "parallel", "pure", "sealed",
  "tailcall", "trait", "virtual",
  "abstract", "and", "as", "assert", "base", "begin", "class", "component", "const", "default",
  "delegate", "do", "done", "downcast", "downto", "elif", "else", "end", "exception", "extern",
  "false", "file", "finally", "fixed", "for", "fun", "function", "global", "if", "in", "inherit",
  "inline", "interface", "internal", "lazy", "let", "match", "measure", "member", "module",
  "mutable", "namespace", "new", "not", "null", "of", "open", "or", "override", "private",
  "process", "public", "rec", "return", "sig", "static", "struct", "then", "to", "true", "try",
  "type", "upcast", "use", "val", "void", "when", "while", "with", "yield",
]);

/**
 * Case-sensitive: every F# keyword is lower case, so `Type` and `Module` are ordinary
 * identifiers and escaping them would only make the emitted surface uglier.
 */
export const needsEscape = name => KEYWORDS.has(name);

/** Backtick-escapes `name` if it would otherwise collide with an F# keyword. */
export const fsIdent = name => (needsEscape(name) ? "``" + name + "``" : name);

/** A line buffer. `w` writes at the current indent; `blank` is idempotent at the seams. */
export class Lines {
  #lines = [];
  #indent = "";

  /** Writes each argument as its own line. Multi-line strings are split so indent applies. */
  w(...lines) {
    for (const line of lines) {
      for (const part of String(line).split("\n")) {
        this.#lines.push(part === "" ? "" : this.#indent + part);
      }
    }
    return this;
  }

  blank() {
    this.#lines.push("");
    return this;
  }

  /** Runs `body` one indent level deeper. F# is whitespace-sensitive; 4 spaces throughout. */
  indent(body) {
    const outer = this.#indent;
    this.#indent += "    ";
    body(this);
    this.#indent = outer;
    return this;
  }

  /**
   * Emits `text` as `///` doc lines. An empty string is a deliberate paragraph break and
   * emits a bare `///`; nothing at all emits nothing, so scraped comments can be passed
   * through without a presence check.
   */
  doc(text) {
    if (text === undefined || text === null) return this;
    if (text === "") return this.w("///");
    if (!text) return this;
    for (const line of String(text).split("\n")) {
      const trimmed = line.trim();
      if (trimmed) this.w(`/// ${trimmed}`);
    }
    return this;
  }

  /** Collapses runs of blank lines, so callers can emit separators without bookkeeping. */
  render() {
    return this.#lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/^\n+/, "") + "\n";
  }
}

/**
 * Escapes text for an XML doc comment. F# parses `///` content as XML and warns on anything
 * malformed (FS3390), so an expression like `(1 << 30) - 1` cannot be dropped into a `<code>`
 * element verbatim - `<` opens a tag that never closes.
 */
export function xml(text) {
  return String(text).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/**
 * The `<auto-generated>` banner. Records the upstream commit so a generated file can always be
 * traced back to the schema it came from.
 */
export function header({ namespace, generator, repo, ref, source }) {
  return [
    `namespace ${namespace}`,
    "",
    "// <auto-generated>",
    `//   Generated by ${generator} from ${repo}@${ref.slice(0, 12)}`,
    `//   at ${source}.`,
    "//   Do not edit by hand - re-run the generator when the pinned schema moves.",
    "// </auto-generated>",
  ];
}
