// <auto-generated>
//   Generated by Xantham.Generator from ansi-regex.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec AnsiRegex

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Interface>]
type Options =
    /// <summary>
    /// Match only the first ANSI escape.
    /// </summary>
    /// <remarks>@default false</remarks>
    abstract onlyFirst: bool
    [<ParamObject; Emit("$0")>]
    static member Create (onlyFirst: bool) : Options = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// Regular expression for matching ANSI escape codes.
    /// </summary>
    /// <remarks>
    /// @example
    /// <code>
    /// import ansiRegex from 'ansi-regex';
    ///
    /// ansiRegex().test('\u001B[4mcake\u001B[0m');
    /// //=&gt; true
    ///
    /// ansiRegex().test('cake');
    /// //=&gt; false
    ///
    /// '\u001B[4mcake\u001B[0m'.match(ansiRegex());
    /// //=&gt; ['\u001B[4m', '\u001B[0m']
    ///
    /// '\u001B[4mcake\u001B[0m'.match(ansiRegex({onlyFirst: true}));
    /// //=&gt; ['\u001B[4m']
    ///
    /// '\u001B]8;;https://github.com\u0007click\u001B]8;;\u0007'.match(ansiRegex());
    /// //=&gt; ['\u001B]8;;https://github.com\u0007', '\u001B]8;;\u0007']
    /// </code>
    /// </remarks>
    [<Import("default", "ansi-regex")>]
    static member ansiRegex (?options: Options) : obj = jsNative
