// <auto-generated>
//   Generated by Xantham.Generator from grouped-dom-aliases-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec GroupedDomAliasesLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("roundTrip", "grouped-dom-aliases-lab")>]
    static member roundTrip (request: GroupedDomAliases.WorkerAugmentationLab.Request) : GroupedDomAliases.WorkerAugmentationLab.Request = jsNative
