// <auto-generated>
//   Generated by Xantham.Generator from typescript/lib.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec TypeScript.Lib

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS

type ActiveXObject =
    [<EmitConstructor>]
    abstract Create: s: string -> obj

[<Interface>]
type ITextWriter =
    abstract Write: s: string -> unit
    abstract WriteLine: s: string -> unit
    abstract Close: unit -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (Write: (string -> unit), WriteLine: (string -> unit), Close: (unit -> unit)) : ITextWriter = jsNative

[<Interface>]
type TextStreamBase =
    /// <summary>
    /// The column number of the current character position in an input stream.
    /// </summary>
    abstract Column: float with get, set
    /// <summary>
    /// The current line number in an input stream.
    /// </summary>
    abstract Line: float with get, set
    /// <summary>
    /// Closes a text stream.
    /// It is not necessary to close standard streams; they close automatically when the process ends. If
    /// you close a standard stream, be aware that any other pointers to that standard stream become invalid.
    /// </summary>
    abstract Close: unit -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (Column: float, Line: float, Close: (unit -> unit)) : TextStreamBase = jsNative

[<Interface>]
type TextStreamWriter =
    inherit TextStreamBase
    /// <summary>
    /// Sends a string to an output stream.
    /// </summary>
    abstract Write: s: string -> unit
    /// <summary>
    /// Sends a specified number of blank lines (newline characters) to an output stream.
    /// </summary>
    abstract WriteBlankLines: intLines: float -> unit
    /// <summary>
    /// Sends a string followed by a newline character to an output stream.
    /// </summary>
    abstract WriteLine: s: string -> unit
    /// <summary>
    /// The column number of the current character position in an input stream.
    /// </summary>
    abstract Column: float with get, set
    /// <summary>
    /// The current line number in an input stream.
    /// </summary>
    abstract Line: float with get, set
    /// <summary>
    /// Closes a text stream.
    /// It is not necessary to close standard streams; they close automatically when the process ends. If
    /// you close a standard stream, be aware that any other pointers to that standard stream become invalid.
    /// </summary>
    abstract Close: unit -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (Write: (string -> unit), WriteBlankLines: (float -> unit), WriteLine: (string -> unit), Column: float, Line: float, Close: (unit -> unit)) : TextStreamWriter = jsNative

[<Interface>]
type TextStreamReader =
    inherit TextStreamBase
    /// <summary>
    /// Returns a specified number of characters from an input stream, starting at the current pointer position.
    /// Does not return until the ENTER key is pressed.
    /// Can only be used on a stream in reading mode; causes an error in writing or appending mode.
    /// </summary>
    abstract Read: characters: float -> string
    /// <summary>
    /// Returns all characters from an input stream.
    /// Can only be used on a stream in reading mode; causes an error in writing or appending mode.
    /// </summary>
    abstract ReadAll: unit -> string
    /// <summary>
    /// Returns an entire line from an input stream.
    /// Although this method extracts the newline character, it does not add it to the returned string.
    /// Can only be used on a stream in reading mode; causes an error in writing or appending mode.
    /// </summary>
    abstract ReadLine: unit -> string
    /// <summary>
    /// Skips a specified number of characters when reading from an input text stream.
    /// Can only be used on a stream in reading mode; causes an error in writing or appending mode.
    /// </summary>
    /// <remarks>@param characters Positive number of characters to skip forward. (Backward skipping is not supported.)</remarks>
    abstract Skip: characters: float -> unit
    /// <summary>
    /// Skips the next line when reading from an input text stream.
    /// Can only be used on a stream in reading mode, not writing or appending mode.
    /// </summary>
    abstract SkipLine: unit -> unit
    /// <summary>
    /// Indicates whether the stream pointer position is at the end of a line.
    /// </summary>
    abstract AtEndOfLine: bool with get, set
    /// <summary>
    /// Indicates whether the stream pointer position is at the end of a stream.
    /// </summary>
    abstract AtEndOfStream: bool with get, set
    /// <summary>
    /// The column number of the current character position in an input stream.
    /// </summary>
    abstract Column: float with get, set
    /// <summary>
    /// The current line number in an input stream.
    /// </summary>
    abstract Line: float with get, set
    /// <summary>
    /// Closes a text stream.
    /// It is not necessary to close standard streams; they close automatically when the process ends. If
    /// you close a standard stream, be aware that any other pointers to that standard stream become invalid.
    /// </summary>
    abstract Close: unit -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (Read: (float -> string), ReadAll: (unit -> string), ReadLine: (unit -> string), Skip: (float -> unit), SkipLine: (unit -> unit), AtEndOfLine: bool, AtEndOfStream: bool, Column: float, Line: float, Close: (unit -> unit)) : TextStreamReader = jsNative

[<Interface>]
type WScript =
    /// <summary>
    /// Outputs text to either a message box (under WScript.exe) or the command console window followed by
    /// a newline (under CScript.exe).
    /// </summary>
    abstract Echo: s: obj -> unit
    /// <summary>
    /// Exposes the write-only error output stream for the current script.
    /// Can be accessed only while using CScript.exe.
    /// </summary>
    abstract StdErr: TextStreamWriter with get, set
    /// <summary>
    /// Exposes the write-only output stream for the current script.
    /// Can be accessed only while using CScript.exe.
    /// </summary>
    abstract StdOut: TextStreamWriter with get, set
    abstract Arguments: WScript.Arguments with get, set
    /// <summary>
    /// The full path of the currently running script.
    /// </summary>
    abstract ScriptFullName: string with get, set
    /// <summary>
    /// Forces the script to stop immediately, with an optional exit code.
    /// </summary>
    abstract Quit: ?exitCode: float -> float
    /// <summary>
    /// The Windows Script Host build version number.
    /// </summary>
    abstract BuildVersion: float with get, set
    /// <summary>
    /// Fully qualified path of the host executable.
    /// </summary>
    abstract FullName: string with get, set
    /// <summary>
    /// Gets/sets the script mode - interactive(true) or batch(false).
    /// </summary>
    abstract Interactive: bool with get, set
    /// <summary>
    /// The name of the host executable (WScript.exe or CScript.exe).
    /// </summary>
    abstract Name: string with get, set
    /// <summary>
    /// Path of the directory containing the host executable.
    /// </summary>
    abstract Path: string with get, set
    /// <summary>
    /// The filename of the currently running script.
    /// </summary>
    abstract ScriptName: string with get, set
    /// <summary>
    /// Exposes the read-only input stream for the current script.
    /// Can be accessed only while using CScript.exe.
    /// </summary>
    abstract StdIn: TextStreamReader with get, set
    /// <summary>
    /// Windows Script Host version
    /// </summary>
    abstract Version: string with get, set
    /// <summary>
    /// Connects a COM object's event sources to functions named with a given prefix, in the form prefix_event.
    /// </summary>
    abstract ConnectObject: objEventSource: obj * strPrefix: string -> unit
    /// <summary>
    /// Creates a COM object.
    /// </summary>
    /// <remarks>@param strProgiID</remarks>
    /// <remarks>@param strPrefix Function names in the form prefix_event will be bound to this object's COM events.</remarks>
    abstract CreateObject: strProgID: string * ?strPrefix: string -> obj
    /// <summary>
    /// Disconnects a COM object from its event sources.
    /// </summary>
    abstract DisconnectObject: obj: obj -> unit
    /// <summary>
    /// Retrieves an existing object with the specified ProgID from memory, or creates a new one from a file.
    /// </summary>
    /// <remarks>
    /// @param
    /// strPathname Fully qualified path to the file containing the object persisted to disk.
    ///    For objects in memory, pass a zero-length string.
    /// </remarks>
    /// <remarks>@param strProgID</remarks>
    /// <remarks>@param strPrefix Function names in the form prefix_event will be bound to this object's COM events.</remarks>
    abstract GetObject: strPathname: string * ?strProgID: string * ?strPrefix: string -> obj
    /// <summary>
    /// Suspends script execution for a specified length of time, then continues execution.
    /// </summary>
    /// <remarks>@param intTime Interval (in milliseconds) to suspend script execution.</remarks>
    abstract Sleep: intTime: float -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (Echo: (obj -> unit), StdErr: TextStreamWriter, StdOut: TextStreamWriter, Arguments: WScript.Arguments, ScriptFullName: string, Quit: (float option -> float), BuildVersion: float, FullName: string, Interactive: bool, Name: string, Path: string, ScriptName: string, StdIn: TextStreamReader, Version: string, ConnectObject: Action<obj, string>, CreateObject: Func<string, string option, obj>, DisconnectObject: (obj -> unit), GetObject: Func<string, string option, string option, obj>, Sleep: (float -> unit)) : WScript = jsNative

module WScript =
    [<Interface>]
    type Arguments =
        abstract length: float with get, set
        abstract Item: n: float -> string
        [<ParamObject; Emit("$0")>]
        static member Create (length: float, Item: (float -> string)) : Arguments = jsNative

/// <summary>
/// Represents an Automation SAFEARRAY
/// </summary>
[<Interface>]
type SafeArray<'T> =
    abstract SafeArray_typekey: SafeArray<'T> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (SafeArray_typekey: SafeArray<'T>) : SafeArray<'T> = jsNative

/// <summary>
/// Allows enumerating over a COM collection, which may not have indexed item access.
/// </summary>
[<Interface>]
type Enumerator<'T> =
    /// <summary>
    /// Returns true if the current item is the last one in the collection, or the collection is empty,
    /// or the current item is undefined.
    /// </summary>
    abstract atEnd: unit -> bool
    /// <summary>
    /// Returns the current item in the collection
    /// </summary>
    abstract item: unit -> 'T
    /// <summary>
    /// Resets the current item in the collection to the first item. If there are no items in the collection,
    /// the current item is set to undefined.
    /// </summary>
    abstract moveFirst: unit -> unit
    /// <summary>
    /// Moves the current item to the next item in the collection. If the enumerator is at the end of
    /// the collection or the collection is empty, the current item is set to undefined.
    /// </summary>
    abstract moveNext: unit -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (atEnd: (unit -> bool), item: (unit -> 'T), moveFirst: (unit -> unit), moveNext: (unit -> unit)) : Enumerator<'T> = jsNative

module EnumeratorConstructor =
    [<Interface>]
    type Collection<'T> =
        abstract Item: index: obj -> 'T
        [<ParamObject; Emit("$0")>]
        static member Create (Item: (obj -> 'T)) : Collection<'T> = jsNative

type EnumeratorConstructor =
    [<EmitConstructor>]
    abstract Create<'T>: safearray: SafeArray<'T> -> Enumerator<'T>
    [<EmitConstructor>]
    abstract Create<'T>: collection: EnumeratorConstructor.Collection<'T> -> Enumerator<'T>
    [<EmitConstructor>]
    abstract Create<'T>: collection: obj -> Enumerator<'T>

/// <summary>
/// Enables reading from a COM safe array, which might have an alternate lower bound, or multiple dimensions.
/// </summary>
[<Interface>]
type VBArray<'T> =
    /// <summary>
    /// Returns the number of dimensions (1-based).
    /// </summary>
    abstract dimensions: unit -> float
    /// <summary>
    /// Takes an index for each dimension in the array, and returns the item at the corresponding location.
    /// </summary>
    abstract getItem: dimension1Index: float * [<ParamArray>] dimensionNIndexes: obj -> 'T
    /// <summary>
    /// Returns the smallest available index for a given dimension.
    /// </summary>
    /// <remarks>@param dimension 1-based dimension (defaults to 1)</remarks>
    abstract lbound: ?dimension: float -> float
    /// <summary>
    /// Returns the largest available index for a given dimension.
    /// </summary>
    /// <remarks>@param dimension 1-based dimension (defaults to 1)</remarks>
    abstract ubound: ?dimension: float -> float
    /// <summary>
    /// Returns a Javascript array with all the elements in the VBArray. If there are multiple dimensions,
    /// each successive dimension is appended to the end of the array.
    /// Example: [[1,2,3],[4,5,6]] becomes [1,2,3,4,5,6]
    /// </summary>
    abstract toArray: unit -> obj
    [<ParamObject; Emit("$0")>]
    static member Create (dimensions: (unit -> float), getItem: Func<float, obj, 'T>, lbound: (float option -> float), ubound: (float option -> float), toArray: (unit -> obj)) : VBArray<'T> = jsNative

type VBArrayConstructor =
    [<EmitConstructor>]
    abstract Create<'T>: safeArray: SafeArray<'T> -> VBArray<'T>

/// <summary>
/// Automation date (VT_DATE)
/// </summary>
[<Interface>]
type VarDate =
    abstract VarDate_typekey: VarDate with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (VarDate_typekey: VarDate) : VarDate = jsNative

type DateConstructor =
    [<EmitConstructor>]
    abstract Create: vd: VarDate -> Date

[<Interface>]
type Date =
    abstract getVarDate: (unit -> VarDate) with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (getVarDate: (unit -> VarDate)) : Date = jsNative

[<Interface>]
type GlobalThis =
    abstract ActiveXObject: ActiveXObject with get, set
    abstract WScript: WScript with get, set
    /// <summary>
    /// WSH is an alias for WScript under Windows Script Host
    /// </summary>
    abstract WSH: WScript with get, set
    /// <summary>
    /// Allows enumerating over a COM collection, which may not have indexed item access.
    /// </summary>
    abstract Enumerator: EnumeratorConstructor with get, set
    /// <summary>
    /// Enables reading from a COM safe array, which might have an alternate lower bound, or multiple dimensions.
    /// </summary>
    abstract VBArray: VBArrayConstructor with get, set
    abstract globalThis: GlobalThis
    abstract undefined: unit
    [<ParamObject; Emit("$0")>]
    static member Create (ActiveXObject: ActiveXObject, WScript: WScript, WSH: WScript, Enumerator: EnumeratorConstructor, VBArray: VBArrayConstructor, globalThis: GlobalThis) : GlobalThis = jsNative
