// <auto-generated>
//   Generated by Xantham.Generator from typescript/lib.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec TypeScript.Lib

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS

[<Interface>]
type GlobalThis =
    abstract ActiveXObject: TypeScript.Lib.Dom.ActiveXObject with get, set
    abstract WScript: TypeScript.Lib.Dom.WScript with get, set
    /// <summary>
    /// WSH is an alias for WScript under Windows Script Host
    /// </summary>
    abstract WSH: TypeScript.Lib.Dom.WScript with get, set
    /// <summary>
    /// Allows enumerating over a COM collection, which may not have indexed item access.
    /// </summary>
    abstract Enumerator: TypeScript.Lib.Dom.EnumeratorConstructor with get, set
    /// <summary>
    /// Enables reading from a COM safe array, which might have an alternate lower bound, or multiple dimensions.
    /// </summary>
    abstract VBArray: TypeScript.Lib.Dom.VBArrayConstructor with get, set
    abstract globalThis: GlobalThis
    abstract undefined: unit
    [<ParamObject; Emit("$0")>]
    static member Create (ActiveXObject: TypeScript.Lib.Dom.ActiveXObject, WScript: TypeScript.Lib.Dom.WScript, WSH: TypeScript.Lib.Dom.WScript, Enumerator: TypeScript.Lib.Dom.EnumeratorConstructor, VBArray: TypeScript.Lib.Dom.VBArrayConstructor, globalThis: GlobalThis) : GlobalThis = jsNative
