// <auto-generated>
//   Generated by Xantham.Generator from optional-param-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec OptionalParamLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// The same three at method positions, where the owner is an interface rather than a module.
/// </summary>
[<Interface>]
type Station =
    abstract marked: a: string * ?b: string -> string
    abstract unioned: a: string * ?b: string -> string
    abstract required: a: string * b: string -> string
    [<ParamObject; Emit("$0")>]
    static member Create (marked: Func<string, string option, string>, unioned: Func<string, string option, string>, required: Func<string, string, string>) : Station = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// <c>b?: T</c> - the marker alone.
    /// </summary>
    [<Import("marked", "optional-param-lab")>]
    static member marked (a: string, ?b: string) : string = jsNative
    /// <summary>
    /// <c>b: T | undefined</c> - the declared type alone. Callers must still pass something.
    /// </summary>
    [<Import("unioned", "optional-param-lab")>]
    static member unioned (a: string, ?b: string) : string = jsNative
    /// <summary>
    /// Neither. The negative both of the above are read against.
    /// </summary>
    [<Import("required", "optional-param-lab")>]
    static member required (a: string, b: string) : string = jsNative
    /// <summary>
    /// <c>?</c> over a type that already absorbs <c>undefined</c>: the marker is the only fact there is.
    /// </summary>
    [<Import("markedAny", "optional-param-lab")>]
    static member markedAny (a: string, ?b: obj) : string = jsNative
