// <auto-generated>
//   Generated by Xantham.Generator from lib-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec LibLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// A generated interface whose members are lib types throughout.
/// </summary>
[<Interface>]
type Store =
    /// <summary>
    /// A promise-returning member, which is what the group's widening used to cost most.
    /// </summary>
    abstract load: key: string -> JS.Promise<JS.Uint8Array>
    /// <summary>
    /// Under an array.
    /// </summary>
    abstract all: unit -> JS.Promise<string>[]
    /// <summary>
    /// Optional, so the promise arrives wrapped in an option.
    /// </summary>
    abstract pending: JS.Promise<unit> option with get, set
    /// <summary>
    /// A lib type as the argument of a generic this package declares.
    /// </summary>
    abstract boxed: Box<JS.Date> with get, set
    /// <summary>
    /// A property whose type is a lib collection.
    /// </summary>
    abstract index: JS.Map<string, JS.ArrayBuffer> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (load: Func<string, JS.Promise<JS.Uint8Array>>, all: Func<JS.Promise<string>[]>, boxed: Box<JS.Date>, index: JS.Map<string, JS.ArrayBuffer>, ?pending: JS.Promise<unit>) : Store = jsNative

/// <summary>
/// A generic of our own, so a lib type can be seen passing through one.
/// </summary>
[<Interface>]
type Box<'T> =
    abstract value: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T) : Box<'T> = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// The one that matters most: nearly every asynchronous API in a <c>.d.ts</c> returns one.
    /// </summary>
    [<Import("fetchOne", "lib-lab")>]
    static member fetchOne (url: string) : JS.Promise<string> = jsNative
    /// <summary>
    /// A promise of a promise, so the argument is shaped at its position rather than widened.
    /// </summary>
    [<Import("fetchAll", "lib-lab")>]
    static member fetchAll (urls: string[]) : JS.Promise<JS.Promise<string>[]> = jsNative
    /// <summary>
    /// Both parameters carried.
    /// </summary>
    [<Import("index", "lib-lab")>]
    static member index (entries: JS.Map<string, float>) : JS.Map<string, string[]> = jsNative
    /// <summary>
    /// And the one-parameter collections.
    /// </summary>
    [<Import("unique", "lib-lab")>]
    static member unique (values: JS.Set<string>) : JS.Set<float> = jsNative
    /// <summary>
    /// The weak collections, which Fable binds under the same names.
    /// </summary>
    [<Import("cache", "lib-lab")>]
    static member cache (store: JS.WeakMap<obj, string>, seen: JS.WeakSet<obj>) : unit = jsNative
    /// <summary>
    /// Non-generic lib types: no arguments to shape, just a name to write.
    /// </summary>
    [<Import("stamp", "lib-lab")>]
    static member stamp (at: JS.Date) : JS.Date = jsNative
    /// <summary>
    /// Binary data - the buffer types a worker or a stream API traffics in.
    /// </summary>
    [<Import("view", "lib-lab")>]
    static member view (buffer: JS.ArrayBuffer, over: JS.DataView) : JS.ArrayBufferView = jsNative
    /// <summary>
    /// An async iterable, which Fable.Core binds (the *synchronous* one it does not - see below).
    /// </summary>
    [<Import("stream", "lib-lab")>]
    static member stream (source: JS.AsyncIterable<string>) : JS.AsyncIterator<float> = jsNative
    /// <summary>
    /// A bare <c>Function</c> in a <c>.d.ts</c> is untyped by construction; <c>JS.Function</c> says the same.
    /// </summary>
    [<Import("invoke", "lib-lab")>]
    static member invoke (fn: JS.Function) : JS.Object = jsNative
    /// <summary>
    /// A typed array. Under a modern lib this is <c>Uint8Array&lt;ArrayBufferLike&gt;</c>.
    /// </summary>
    [<Import("bytes", "lib-lab")>]
    static member bytes (input: JS.Uint8Array) : JS.Float64Array = jsNative
    /// <summary>
    /// A thenable is the structural supertype of a promise, not a promise.
    /// </summary>
    [<Import("thenable", "lib-lab")>]
    static member thenable () : JS.Promise<string> = jsNative
    /// <summary>
    /// Readonly views over the collections. F# has the mutable binding and only that.
    /// </summary>
    [<Import("frozen", "lib-lab")>]
    static member frozen (entries: JS.Map<string, float>, values: JS.Set<string>) : unit = jsNative
    /// <summary>
    /// The one the group's widening used to cost most: a DOM name in an ordinary position.
    /// </summary>
    [<Import("handle", "lib-lab")>]
    static member handle (target: Browser.Types.EventTarget) : unit = jsNative
    /// <summary>
    /// Elements and events, which is most of what a browser-facing <c>.d.ts</c> traffics in.
    /// </summary>
    [<Import("mount", "lib-lab")>]
    static member mount (host: Browser.Types.HTMLElement, on: Browser.Types.Event) : unit = jsNative
    /// <summary>
    /// Binary and URL types, which come from separate packages of the same family.
    /// </summary>
    [<Import("upload", "lib-lab")>]
    static member upload (body: Browser.Types.Blob, ``to``: Browser.Types.URL) : Browser.Types.FormData = jsNative
    /// <summary>
    /// Bound at two arities: <c>CustomEvent</c> is in the family both bare and generic.
    /// </summary>
    [<Import("emit", "lib-lab")>]
    static member emit (detail: Browser.Types.CustomEvent<string>) : unit = jsNative
    /// <summary>
    /// <c>seq&lt;'T&gt;</c> is not a JS iterable, whatever the two have in common. Widened, and noted.
    /// </summary>
    [<Import("each", "lib-lab")>]
    static member each (values: obj) : unit = jsNative
    /// <summary>
    /// A DOM name two packages of the family both define (<c>Browser.IndexedDB</c> and
    /// <c>Browser.MediaStream</c> each declare a <c>Range</c>). There is no qualification that picks one, so
    /// the table drops it and this widens - the honest outcome, and the reason ambiguity is
    /// resolved when the table is generated rather than when the reference is emitted.
    /// </summary>
    [<Import("select", "lib-lab")>]
    static member ``select`` (over: obj) : unit = jsNative
    /// <summary>
    /// A DOM name the family does not bind at all. <c>Response</c> and the rest of <c>fetch</c> live in
    /// <c>Fable.Fetch</c>, a different package family, so this is still <c>obj</c>.
    /// </summary>
    [<Import("respond", "lib-lab")>]
    static member respond () : obj = jsNative
