// <auto-generated>
//   Generated by Xantham.Generator from subpath-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec SubpathLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Internal =
    abstract hidden: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (hidden: float) : Internal = jsNative

[<Interface>]
type Payload =
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string) : Payload = jsNative

[<Interface>]
type RootSession =
    abstract kind: string
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string) : RootSession = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("describe", "subpath-lab")>]
    static member describe (payload: Payload) : string = jsNative
    [<Import("RootSession", "subpath-lab"); EmitConstructor>]
    static member RootSession () : RootSession = jsNative

/// <summary>subpath-lab/alias</summary>
module Alias =
    [<Interface>]
    type AliasShape =
        abstract name: string with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (name: string) : AliasShape = jsNative

    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        [<Import("whoami", "subpath-lab/alias")>]
        static member whoami () : string = jsNative

/// <summary>subpath-lab/client</summary>
module Client =
    [<Interface>]
    type ClientOptions =
        abstract retries: float with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (retries: float) : ClientOptions = jsNative

    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        [<Import("connect", "subpath-lab/client")>]
        static member connect (options: ClientOptions) : Internal = jsNative
        [<Import("describe", "subpath-lab/client")>]
        static member describe (payload: Payload) : string = jsNative
        [<Import("Session", "subpath-lab/client"); EmitConstructor>]
        static member Session () : RootSession = jsNative

    /// <summary>subpath-lab/client/deep</summary>
    module Deep =
        [<Interface>]
        type DeepOnly =
            abstract level: float with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (level: float) : DeepOnly = jsNative

        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            [<Import("depth", "subpath-lab/client/deep")>]
            static member depth () : float = jsNative

/// <summary>subpath-lab/legacy/index.js</summary>
module Legacy =
    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        [<Import("connect", "subpath-lab/legacy/index.js")>]
        static member connect (options: Client.ClientOptions) : Internal = jsNative
        [<Import("describe", "subpath-lab/legacy/index.js")>]
        static member describe (payload: Payload) : string = jsNative
        [<Import("Session", "subpath-lab/legacy/index.js"); EmitConstructor>]
        static member Session () : RootSession = jsNative

/// <summary>subpath-lab/mirror</summary>
module Mirror =
    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        [<Import("whoami", "subpath-lab/mirror")>]
        static member whoami () : string = jsNative
