// <auto-generated>
//   Generated by Xantham.Generator from ambient-types-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec AmbientTypesLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Host =
    abstract runtime: AmbientProviderLab.RuntimeHandle with get, set
    abstract binding: AmbientProviderLab.HostBinding with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (runtime: AmbientProviderLab.RuntimeHandle, binding: AmbientProviderLab.HostBinding) : Host = jsNative
