// <auto-generated>
//   Generated by Xantham.Generator from alias-api-owner-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec Identity.Support.AliasApiOwnerLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Part =
    abstract output: Part.Output with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (output: Part.Output) : Part = jsNative

module Part =
    [<RequireQualifiedAccess; TypeScriptTaggedUnion("type", CaseRules.None)>]
    type Output =
        | [<CompiledName("text")>] Text of value: string
        | [<CompiledName("json")>] Json of value: U2<string, float> option

    [<Interface>]
    type Output2 =
        abstract ``type``: string with get, set
        abstract value: string with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (``type``: string, value: string) : Output2 = jsNative

    [<Interface>]
    type Output3 =
        abstract ``type``: string with get, set
        abstract value: U2<string, float> option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (``type``: string, ?value: U2<string, float>) : Output3 = jsNative
