// <auto-generated>
//   Generated by Xantham.Generator from inner-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec InnerLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Interface>]
type Pulse =
    abstract id: string with get, set
    abstract at: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (id: string, at: float) : Pulse = jsNative
