// <auto-generated>
//   Generated by Xantham.Generator from outer-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec OuterLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Interface>]
type Signal =
    abstract pulse: InnerLab.Pulse with get, set
    abstract label: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (pulse: InnerLab.Pulse, label: string) : Signal = jsNative
