// <auto-generated>
//   Generated by Xantham.Generator from literal-alias-consumer-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec LiteralAliasIdentityLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("accept", "literal-alias-consumer-lab")>]
    static member accept (value: Identity.LiteralAliasOwnerLab.Value, mode: Identity.LiteralAliasOwnerLab.Value.Kind) : Identity.LiteralAliasOwnerLab.Value = jsNative
    [<Import("nominal", "literal-alias-consumer-lab")>]
    static member nominal (mode: Nominal.Mode) : Nominal.Mode = jsNative

module Nominal =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Mode =
        | [<CompiledName("a")>] A
        | [<CompiledName("b")>] B
