// <auto-generated>
//   Generated by Xantham.Generator from generic-tag-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec GenericTagLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Base =
    abstract id: string
    [<ParamObject; Emit("$0")>]
    static member Create (id: string) : Base = jsNative

[<RequireQualifiedAccess; TypeScriptTaggedUnion("kind", CaseRules.None)>]
type Pair<'T, 'U> =
    | [<CompiledName("left")>] Left of value: 'T
    | [<CompiledName("right")>] Right of value: 'U
    | [<CompiledName("both")>] Both of left: 'T * right: 'U

[<Interface>]
type Pair2<'T> =
    abstract kind: string
    abstract value: 'T
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, value: 'T) : Pair2<'T> = jsNative

[<Interface>]
type Pair3<'U> =
    abstract kind: string
    abstract value: 'U
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, value: 'U) : Pair3<'U> = jsNative

[<Interface>]
type Pair4<'T, 'U> =
    abstract kind: string
    abstract left: 'T
    abstract right: 'U
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, left: 'T, right: 'U) : Pair4<'T, 'U> = jsNative

[<RequireQualifiedAccess; TypeScriptTaggedUnion("kind", CaseRules.None)>]
type Batch<'T> =
    | [<CompiledName("many")>] Many of items: 'T[]
    | [<CompiledName("later")>] Later of pending: JS.Promise<'T>

[<Interface>]
type Batch2<'T> =
    abstract kind: string
    abstract items: 'T[]
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, items: 'T[]) : Batch2<'T> = jsNative

[<Interface>]
type Batch3<'T> =
    abstract kind: string
    abstract pending: JS.Promise<'T>
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, pending: JS.Promise<'T>) : Batch3<'T> = jsNative

[<RequireQualifiedAccess; TypeScriptTaggedUnion("kind", CaseRules.None)>]
type Owned<'T when 'T :> Base> =
    | [<CompiledName("owned")>] Owned of owner: 'T
    | [<CompiledName("orphan")>] Orphan

[<Interface>]
type Owned2<'T when 'T :> Base> =
    abstract kind: string
    abstract owner: 'T
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, owner: 'T) : Owned2<'T> = jsNative

[<Interface>]
type Owned3 =
    abstract kind: string
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string) : Owned3 = jsNative

[<RequireQualifiedAccess; TypeScriptTaggedUnion("kind", CaseRules.None)>]
type Marker<'T> =
    | [<CompiledName("on")>] On
    | [<CompiledName("off")>] Off

[<Interface>]
type Marker2 =
    abstract kind: string
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string) : Marker2 = jsNative

[<Interface>]
type Marker3 =
    abstract kind: string
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string) : Marker3 = jsNative

[<RequireQualifiedAccess; TypeScriptTaggedUnion("kind", CaseRules.None)>]
type Tree<'T> =
    | [<CompiledName("leaf")>] Leaf of value: 'T
    | [<CompiledName("node")>] Node of children: Tree<'T>[]

[<Interface>]
type Tree2<'T> =
    abstract kind: string
    abstract value: 'T
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, value: 'T) : Tree2<'T> = jsNative

[<Interface>]
type Tree3<'T> =
    abstract kind: string
    abstract children: Tree<'T>[]
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, children: Tree<'T>[]) : Tree3<'T> = jsNative

[<Interface>]
type Fulfilled<'T> =
    abstract status: string
    abstract value: 'T
    [<ParamObject; Emit("$0")>]
    static member Create (status: string, value: 'T) : Fulfilled<'T> = jsNative

[<Interface>]
type Rejected =
    abstract status: string
    abstract reason: string
    [<ParamObject; Emit("$0")>]
    static member Create (status: string, reason: string) : Rejected = jsNative

[<RequireQualifiedAccess; TypeScriptTaggedUnion("status", CaseRules.None)>]
type Settled<'T> =
    | [<CompiledName("fulfilled")>] Fulfilled of value: 'T
    | [<CompiledName("rejected")>] Rejected of reason: string

[<RequireQualifiedAccess; TypeScriptTaggedUnion("type", CaseRules.None)>]
type Job<'T> =
    | [<CompiledName("once")>] Once of id: string * payload: 'T * at: float
    | [<CompiledName("every")>] Every of id: string * payload: 'T * seconds: float

[<Interface>]
type Job2<'T> =
    abstract id: string
    abstract payload: 'T
    abstract ``type``: string
    abstract at: float
    [<ParamObject; Emit("$0")>]
    static member Create (id: string, payload: 'T, ``type``: string, at: float) : Job2<'T> = jsNative

[<Interface>]
type Job3<'T> =
    abstract id: string
    abstract payload: 'T
    abstract ``type``: string
    abstract seconds: float
    [<ParamObject; Emit("$0")>]
    static member Create (id: string, payload: 'T, ``type``: string, seconds: float) : Job3<'T> = jsNative

type Task<'T> = Job<'T>

type MaybeJob<'T> = Job<'T> option

[<RequireQualifiedAccess; TypeScriptTaggedUnion("type", CaseRules.None)>]
type JobAlias<'T> =
    | [<CompiledName("once")>] Once of id: string * payload: 'T * at: float
    | [<CompiledName("every")>] Every of id: string * payload: 'T * seconds: float

[<Interface>]
type JobAlias2<'T> =
    abstract id: string
    abstract payload: 'T
    abstract ``type``: string
    abstract at: float
    [<ParamObject; Emit("$0")>]
    static member Create (id: string, payload: 'T, ``type``: string, at: float) : JobAlias2<'T> = jsNative

[<Interface>]
type JobAlias3<'T> =
    abstract id: string
    abstract payload: 'T
    abstract ``type``: string
    abstract seconds: float
    [<ParamObject; Emit("$0")>]
    static member Create (id: string, payload: 'T, ``type``: string, seconds: float) : JobAlias3<'T> = jsNative

[<RequireQualifiedAccess; TypeScriptTaggedUnion("kind", CaseRules.None)>]
type Sided<'T, 'U> =
    | [<CompiledName("left")>] Left of value: 'T
    | [<CompiledName("right")>] Right of value: 'U

[<Interface>]
type Sided2<'T> =
    abstract kind: string
    abstract value: 'T
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, value: 'T) : Sided2<'T> = jsNative

[<Interface>]
type Sided3<'U> =
    abstract kind: string
    abstract value: 'U
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, value: 'U) : Sided3<'U> = jsNative

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type Mode =
    | [<CompiledName("fast")>] Fast
    | [<CompiledName("slow")>] Slow

[<Interface>]
type Queue<'T> =
    abstract head: Job<'T>
    abstract items: Job<'T>[]
    abstract last: Job<'T> option
    abstract fallback: Job<string>
    abstract mode: Mode
    abstract next: unit -> JS.Promise<Job<'T>>
    abstract peek: unit -> Job<'T> option
    abstract concrete: unit -> Job<Base>
    abstract settle<'U>: value: 'U -> Settled<'U>
    abstract sided<'U>: value: 'U -> Sided<'T, 'U>
    abstract state: unit -> Queue.State.Result<'T>
    [<ParamObject; Emit("$0")>]
    static member Create (head: Job<'T>, items: Job<'T>[], fallback: Job<string>, mode: Mode, next: (unit -> JS.Promise<Job<'T>>), peek: (unit -> Job<'T> option), concrete: (unit -> Job<Base>), settle: ('U -> Settled<'U>), sided: ('U -> Sided<'T, 'U>), state: (unit -> Queue.State.Result<'T>), ?last: Job<'T>) : Queue<'T> = jsNative

[<Interface>]
type Holder<'T> =
    abstract marker: Marker<string> option
    abstract nullable: Marker<float> option
    abstract either: U2<Marker2, Marker3>
    abstract poll: unit -> Job<'T> option
    [<ParamObject; Emit("$0")>]
    static member Create (either: U2<Marker2, Marker3>, poll: (unit -> Job<'T> option), ?marker: Marker<string>, ?nullable: Marker<float>) : Holder<'T> = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("accept", "generic-tag-lab")>]
    static member accept<'T> (input: Accept.Input<'T>) : 'T option = jsNative

module Accept =
    [<RequireQualifiedAccess; TypeScriptTaggedUnion("kind", CaseRules.None)>]
    type Input<'T> =
        | [<CompiledName("a")>] A of value: 'T
        | [<CompiledName("b")>] B

    [<Interface>]
    type Input2<'T> =
        abstract kind: string
        abstract value: 'T
        [<ParamObject; Emit("$0")>]
        static member Create (kind: string, value: 'T) : Input2<'T> = jsNative

    [<Interface>]
    type Input3 =
        abstract kind: string
        [<ParamObject; Emit("$0")>]
        static member Create (kind: string) : Input3 = jsNative

module Queue =
    module State =
        [<RequireQualifiedAccess; TypeScriptTaggedUnion("kind", CaseRules.None)>]
        type Result<'T> =
            | [<CompiledName("idle")>] Idle
            | [<CompiledName("busy")>] Busy of job: Job<'T>

        [<Interface>]
        type Result2 =
            abstract kind: string
            [<ParamObject; Emit("$0")>]
            static member Create (kind: string) : Result2 = jsNative

        [<Interface>]
        type Result3<'T> =
            abstract kind: string
            abstract job: Job<'T>
            [<ParamObject; Emit("$0")>]
            static member Create (kind: string, job: Job<'T>) : Result3<'T> = jsNative
