// <auto-generated>
//   Generated by Xantham.Generator from optional-array-consumer-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec AnonymousParentSourceLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Container =
    abstract values: string[] option with get, set
    abstract cache: OptionalArraySharedLab.Shared with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (cache: OptionalArraySharedLab.Shared, ?values: string[]) : Container = jsNative
