// <auto-generated>
//   Generated by Xantham.Generator from array-shape-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec ArrayShapeLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// An array reached through an interface of its own: the symbol is <c>Chapters</c>, not <c>Array</c>.
/// </summary>
type Chapters = string[]

/// <summary>
/// An array intersected with a shape: the symbol is the intersection's.
/// </summary>
type Tagged = float[]

/// <summary>
/// A tuple the checker cannot collapse before the mapped type applies.
/// </summary>
type TupleOf = obj

/// <summary>
/// A mapped type over a deferred tuple operand: the symbol is <c>__type</c>.
/// </summary>
type ReadonlyTuple = obj[]

/// <summary>
/// Indexable by number and carrying <c>length</c>, with none of <c>Array</c>'s members.
/// </summary>
type Register =
    abstract length: float with get, set
    [<EmitIndexer>]
    abstract Item: float -> string with get, set

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("chapters", "array-shape-lab")>]
    static member chapters: string[] = jsNative
    [<Import("tagged", "array-shape-lab")>]
    static member tagged: float[] = jsNative
    [<Import("pair", "array-shape-lab")>]
    static member pair: string * string = jsNative
    [<Import("register", "array-shape-lab")>]
    static member register: Register = jsNative
