// <auto-generated>
//   Generated by Xantham.Generator from dep-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec DepLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Interface>]
type Widget =
    abstract id: string with get, set
    abstract size: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (id: string, size: float) : Widget = jsNative
