// <auto-generated>
//   Generated by Xantham.Generator from literal-union-ownership-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec LiteralUnionOwnershipLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("accept", "literal-union-ownership-lab")>]
    static member accept (a: Identity.LiteralOwnerALab.AOptions, b: Identity.LiteralOwnerBLab.BOptions) : unit = jsNative
    [<Import("takeA", "literal-union-ownership-lab")>]
    static member takeA (?value: Identity.LiteralOwnerALab.AOptions.MaxTokensField) : unit = jsNative
    [<Import("takeB", "literal-union-ownership-lab")>]
    static member takeB (?value: Identity.LiteralOwnerALab.AOptions.MaxTokensField) : unit = jsNative
