// <auto-generated>
//   Generated by Xantham.Generator from literal-owner-a-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec Identity.LiteralOwnerALab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type AOptions =
    abstract maxTokensField: AOptions.MaxTokensField option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?maxTokensField: AOptions.MaxTokensField) : AOptions = jsNative

module AOptions =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type MaxTokensField =
        | [<CompiledName("max_completion_tokens")>] MaxCompletionTokens
        | [<CompiledName("max_tokens")>] MaxTokens
