// <auto-generated>
//   Generated by Xantham.Generator from literal-owner-b-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec Identity.LiteralOwnerBLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type BOptions =
    abstract maxTokensField: Identity.LiteralOwnerALab.AOptions.MaxTokensField option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?maxTokensField: Identity.LiteralOwnerALab.AOptions.MaxTokensField) : BOptions = jsNative
