#Requires -Version 7
<#
Generates the compiler-lib bindings and packs them as one NuGet package, Xantham.Fable.Lib:
`namespace rec TypeScript.Lib` with `module Es` (lib.es*.d.ts) and `module Dom` (lib.dom*,
lib.webworker*, lib.scripthost*), which reference each other in both directions.

Usage, from the repository root, after `dotnet build src/Xantham.Cli -c Release`:

    pwsh tools/lib-pack/pack-libs.ps1 -Work C:\xantham-libs [-Version 0.1.0-alpha.1]

-Work must be outside the repository: the build gate's format stage sweeps every .fs under it.
#>
param(
    [Parameter(Mandatory)] [string] $Work,
    [string] $Version = "0.1.0-alpha.1",
    [string] $Tsc = ""
)

$ErrorActionPreference = "Stop"
$repo = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$cli = Join-Path $repo "src\Xantham.Cli\bin\Release\net10.0\xantham.dll"
if (-not (Test-Path $cli)) { throw "build the CLI first: dotnet build src/Xantham.Cli -c Release" }

if ($Tsc -eq "") {
    $Tsc = Join-Path $repo "node_modules\@typescript\typescript-win32-x64\lib\tsc.exe"
}
$env:XANTHAM_TSGO_EXE = $Tsc

$probe = Join-Path $Work "probe"
New-Item -ItemType Directory -Force $probe | Out-Null
Set-Content (Join-Path $probe "index.d.ts") "export {};"
Set-Content (Join-Path $probe "package.json") '{ "name": "xantham-lib-probe", "version": "0.0.0", "types": "index.d.ts" }'
Set-Content (Join-Path $probe "xantham.json") '{ "groups": { "typescript/lib": "ship" }, "lib": ["dom"] }'

$out = Join-Path $probe "out"
if (Test-Path $out) { Remove-Item -Recurse -Force $out }
& dotnet $cli generate $probe -o $out
if ($LASTEXITCODE -ne 0) { throw "generate failed" }

$core = Join-Path $repo "src\Xantham.Fable.Core\Xantham.Fable.Core.fsproj"

function New-LibProject($name, $file, $deps) {
    $dir = Join-Path $Work $name
    New-Item -ItemType Directory -Force $dir | Out-Null
    Copy-Item (Join-Path $out "groups\$file") (Join-Path $dir $file) -Force
    $refs = ($deps | ForEach-Object { "        <ProjectReference Include=`"$_`" />" }) -join "`n"
    @"
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
        <Version>$Version</Version>
        <PackageId>$name</PackageId>
        <Authors>Shayan Habibi</Authors>
        <Description>Fable binding for the TypeScript compiler lib, generated by Xantham.</Description>
        <PackageTags>fable;fsharp;typescript;bindings</PackageTags>
        <NoWarn>`$(NoWarn);FS3370;FS0064;FS1182</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="$file" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Fable.Core" Version="5.2.0" />
$refs
    </ItemGroup>
</Project>
"@ | Set-Content (Join-Path $dir "$name.fsproj")
    return Join-Path $dir "$name.fsproj"
}

$lib = New-LibProject "Xantham.Fable.Lib" "TypeScript.Lib.fs" @($core)

$nupkg = Join-Path $Work "nupkg"
& dotnet pack $lib -c Release -o $nupkg
if ($LASTEXITCODE -ne 0) { throw "pack failed" }
Write-Host "packages in $nupkg"
