// <auto-generated>
//   Generated by Xantham.Generator from alias-copy-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec AliasCopyLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// One member per referenced shape, so each dependency name is read exactly once.
/// </summary>
[<Interface>]
type Panel =
    abstract widget: AliasCopyDepLab.Widget with get, set
    abstract pair: AliasCopyDepLab.WidgetPair with get, set
    abstract format: AliasCopyDepLab.Formatter with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (widget: AliasCopyDepLab.Widget, pair: AliasCopyDepLab.WidgetPair, format: AliasCopyDepLab.Formatter) : Panel = jsNative

/// <summary>
/// The entry package's own alias over an object literal, which this run declares.
/// </summary>
[<Interface>]
type PanelPair =
    abstract left: Panel with get, set
    abstract right: Panel with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (left: Panel, right: Panel) : PanelPair = jsNative

[<Interface>]
type DraftPanel =
    abstract widget: AliasCopyDepLab.Widget option with get, set
    abstract pair: AliasCopyDepLab.WidgetPair option with get, set
    abstract format: AliasCopyDepLab.Formatter option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?widget: AliasCopyDepLab.Widget, ?pair: AliasCopyDepLab.WidgetPair, ?format: AliasCopyDepLab.Formatter) : DraftPanel = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A mapped type over the entry package's own operand, resolved by content (D6).
    /// </summary>
    [<Import("draft", "alias-copy-lab")>]
    static member draft (panel: DraftPanel) : unit = jsNative
