// <auto-generated>
//   Generated by Xantham.Generator from class-implements-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec ClassImplementsLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Client =
    inherit Model<string>
    abstract generate: options: Options -> string
    [<ParamObject; Emit("$0")>]
    static member Create (generate: (Options -> string)) : Client = jsNative

[<Interface>]
type Model<'T> =
    abstract generate: options: Options -> 'T
    [<ParamObject; Emit("$0")>]
    static member Create (generate: (Options -> 'T)) : Model<'T> = jsNative

[<Interface>]
type Options =
    abstract text: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (text: string) : Options = jsNative

[<Interface>]
type GenericClient<'T when 'T :> Model<string>> =
    inherit Model<'T>
    [<ParamObject; Emit("$0")>]
    static member Create (generate: (Options -> 'T)) : GenericClient<'T> = jsNative

[<Interface>]
type StructuralClient =
    abstract generate: options: Options -> string
    [<ParamObject; Emit("$0")>]
    static member Create (generate: (Options -> string)) : StructuralClient = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("Client", "class-implements-lab"); EmitConstructor>]
    static member Client () : Client = jsNative
    [<Import("GenericClient", "class-implements-lab"); EmitConstructor>]
    static member GenericClient<'T when 'T :> Model<string>> () : GenericClient<'T> = jsNative
    [<Import("StructuralClient", "class-implements-lab"); EmitConstructor>]
    static member StructuralClient () : StructuralClient = jsNative
