// <auto-generated>
//   Generated by Xantham.Generator from customization-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CustomizationLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Properties<'T> =
    abstract value: 'T with get, set
    abstract stamp: string
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T, stamp: string) : Properties<'T> = jsNative

[<Interface>]
type Named =
    abstract title: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (title: string) : Named = jsNative

[<Interface>]
type Input =
    inherit Properties<string>
    inherit Named
    abstract disabled: bool with get, set
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (disabled: bool, value: string, stamp: string, title: string) : Input = jsNative

[<Interface>]
type OddKeys =
    abstract ``aria-label``: string with get, set
    abstract ``quote"key``: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``aria-label``: string, ``quote"key``: string) : OddKeys = jsNative

[<Interface>]
type Left =
    inherit Properties<string>
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string, stamp: string) : Left = jsNative

[<Interface>]
type Right =
    inherit Properties<string>
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string, stamp: string) : Right = jsNative

[<Interface>]
type Diamond =
    inherit Left
    inherit Right
    abstract optional: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string, stamp: string, ?optional: string) : Diamond = jsNative

[<Interface>]
type Override =
    inherit Properties<string>
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string, stamp: string) : Override = jsNative
