// <auto-generated>
//   Generated by Xantham.Generator from paramobject-method-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec ParamobjectMethodLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// A method beside a required and an optional property. The method's parameter is required, so
/// it sorts ahead of the optional property; a method returning <c>void</c> is an <c>Action</c>.
/// </summary>
[<Interface>]
type Listener =
    abstract name: string with get, set
    abstract tag: string option with get, set
    abstract notify: count: float -> string
    abstract reset: unit -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (name: string, notify: (float -> string), reset: (unit -> unit), ?tag: string) : Listener = jsNative

/// <summary>
/// A negative: an index signature has no name to bind a Create parameter to, whatever named
/// members sit beside it.
/// </summary>
type Bag =
    abstract label: string with get, set
    abstract lookup: key: string -> float
    [<EmitIndexer>]
    abstract Item: string -> obj with get, set

/// <summary>
/// The instance side of the constructor-object negative.
/// A negative: the construct signature already made <c>Create</c> members of its own (§4.4), so the
/// constructor object gets no ParamObject overload beside them.
/// </summary>
[<Interface>]
type Handle =
    abstract id: string
    [<ParamObject; Emit("$0")>]
    static member Create (id: string) : Handle = jsNative

type HandleConstructor =
    abstract reset: unit -> unit
    [<EmitConstructor>]
    abstract Create: id: string -> Handle

/// <summary>
/// A negative: two same-named methods would bind two Create parameters of one name.
/// </summary>
type Formatter =
    abstract locale: string with get, set
    abstract format: value: float -> string
    abstract format: value: float * digits: float -> string

/// <summary>
/// A negative: twenty-five members, one over the Create parameter budget.
/// </summary>
type Wide =
    abstract a1: float with get, set
    abstract a2: float with get, set
    abstract a3: float with get, set
    abstract a4: float with get, set
    abstract a5: float with get, set
    abstract a6: float with get, set
    abstract a7: float with get, set
    abstract a8: float with get, set
    abstract a9: float with get, set
    abstract a10: float with get, set
    abstract a11: float with get, set
    abstract a12: float with get, set
    abstract a13: float with get, set
    abstract a14: float with get, set
    abstract a15: float with get, set
    abstract a16: float with get, set
    abstract a17: float with get, set
    abstract a18: float with get, set
    abstract a19: float with get, set
    abstract a20: float with get, set
    abstract a21: float with get, set
    abstract a22: float with get, set
    abstract a23: float with get, set
    abstract a24: float with get, set
    abstract go: unit -> unit

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// The instance side of the constructor-object negative.
    /// A negative: the construct signature already made <c>Create</c> members of its own (§4.4), so the
    /// constructor object gets no ParamObject overload beside them.
    /// </summary>
    [<Import("Handle", "paramobject-method-lab")>]
    static member Handle: HandleConstructor = jsNative
    [<Import("listener", "paramobject-method-lab")>]
    static member listener: Listener = jsNative
    [<Import("bag", "paramobject-method-lab")>]
    static member bag: Bag = jsNative
    [<Import("formatter", "paramobject-method-lab")>]
    static member formatter: Formatter = jsNative
    [<Import("wide", "paramobject-method-lab")>]
    static member wide: Wide = jsNative
