// <auto-generated>
//   Generated by Xantham.Generator from generic-marker-consumer-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec GenericMarkerCatalogLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("accept", "generic-marker-consumer-lab")>]
    static member accept<'T> (options: Identity.GenericMarkerOwnerLab.Options<'T>) : Identity.GenericMarkerOwnerLab.Options<'T> = jsNative
    [<Import("loose", "generic-marker-consumer-lab")>]
    static member loose (options: Identity.GenericMarkerOwnerLab.LooseOptions) : Identity.GenericMarkerOwnerLab.LooseOptions = jsNative
