// <auto-generated>
//   Generated by Xantham.Generator from cross-package-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CrossPackageLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// A member of each referenced shape, so the O7 templated name is read at three arities of use.
/// </summary>
[<Interface>]
type Panel =
    abstract widget: obj with get, set
    abstract boxed: obj with get, set
    abstract pair: PanelPair with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (widget: obj, boxed: obj, pair: PanelPair) : Panel = jsNative

[<Interface>]
type PanelPair =
    abstract left: obj with get, set
    abstract right: obj with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (left: obj, right: obj) : PanelPair = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A referenced generic at a return position, applied to another referenced name.
    /// </summary>
    [<Import("mount", "cross-package-lab")>]
    static member mount (widget: obj) : obj = jsNative
