// <auto-generated>
//   Generated by Xantham.Generator from case-sanitise-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CaseSanitiseLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type Kind =
    | [<CompiledName("meta")>] CfMeta
    | [<CompiledName("beta")>] BetaChannel
    | [<CompiledName("twofactor")>] N2fa

[<Interface>]
type Kind2 =
    abstract ``@cf/meta``: string
    abstract ``beta channel``: string
    abstract ``2fa``: string
    [<ParamObject; Emit("$0")>]
    static member Create (``@cf/meta``: string, ``beta channel``: string, ``2fa``: string) : Kind2 = jsNative

type Collide =
    | AB = 1
    | AB2 = 2

type Collide2 =
    abstract ``a-b``: float
    abstract a_b: float
    [<EmitIndexer>]
    abstract Item: float -> string

/// <summary>
/// Negative: an ordinary dash/underscore/dot-separated member name is untouched noise-wise.
/// </summary>
type Plain = string

[<Interface>]
type Plain2 =
    abstract ``one-two``: string
    [<ParamObject; Emit("$0")>]
    static member Create (``one-two``: string) : Plain2 = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A real TS enum whose member names carry characters illegal in a .NET union case name: <c>@</c>
    /// and <c>/</c> from a model-key style name, a space, and a leading digit. The member's own name
    /// becomes the case; its value stays the compiled text a JavaScript consumer reads.
    /// </summary>
    [<Import("Kind", "case-sanitise-lab")>]
    static member Kind: Kind2 = jsNative
    /// <summary>
    /// Negative: two member names that sanitise to the same identifier must still keep separate cases.
    /// </summary>
    [<Import("Collide", "case-sanitise-lab")>]
    static member Collide: Collide2 = jsNative
    /// <summary>
    /// Negative: an ordinary dash/underscore/dot-separated member name is untouched noise-wise.
    /// </summary>
    [<Import("Plain", "case-sanitise-lab")>]
    static member Plain: Plain2 = jsNative
