// <auto-generated>
//   Generated by Xantham.Generator from package-submanifest-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec PackageSubmanifestLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

type Item = obj
