// <auto-generated>
//   Generated by Xantham.Generator from delegate-name-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec DelegateNameLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

type TickHandler = delegate of x: float * y: float -> string

/// <summary>
/// Two members of the same declared shape, and one nullary for contrast.
/// </summary>
[<Interface>]
type EventTarget =
    abstract onTick: EventTarget.OnTick with get, set
    abstract onDrag: EventTarget.OnDrag with get, set
    abstract onDone: (unit -> unit) option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (onTick: EventTarget.OnTick, onDrag: EventTarget.OnDrag, ?onDone: (unit -> unit)) : EventTarget = jsNative

/// <summary>
/// A retained callback in return position.
/// </summary>
[<Interface>]
type Factory =
    abstract pair: Factory.Pair
    abstract make: seed: float -> Factory.Make.Result
    [<ParamObject; Emit("$0")>]
    static member Create (pair: Factory.Pair, make: (float -> Factory.Make.Result)) : Factory = jsNative

module CallNesting =
    type Outer = delegate of seed: float -> (float -> string)

module CallThree =
    type Handler = delegate of x: float * y: float * label: string -> string

module CallTwo =
    type Handler = delegate of x: float * y: float -> string

module CallVoidTwo =
    type Handler = delegate of x: float * y: float -> unit

module EventTarget =
    type OnDrag = delegate of x: float * y: float -> string

    type OnTick = delegate of x: float * y: float -> string

module Factory =
    type Pair = delegate of x: float * y: float -> string

    module Make =
        type Result = delegate of x: float * y: float -> string

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A two-argument callback in parameter position.
    /// </summary>
    [<Import("callTwo", "delegate-name-lab")>]
    static member callTwo (handler: CallTwo.Handler) : string = jsNative
    /// <summary>
    /// A three-argument callback in parameter position.
    /// </summary>
    [<Import("callThree", "delegate-name-lab")>]
    static member callThree (handler: CallThree.Handler) : string = jsNative
    /// <summary>
    /// A two-argument callback returning nothing, which rendered <c>Action&lt;A, B&gt;</c>.
    /// </summary>
    [<Import("callVoidTwo", "delegate-name-lab")>]
    static member callVoidTwo (handler: CallVoidTwo.Handler) : string = jsNative
    /// <summary>
    /// The alias in parameter position.
    /// </summary>
    [<Import("callNamed", "delegate-name-lab")>]
    static member callNamed (handler: TickHandler) : string = jsNative
    /// <summary>
    /// Reports the arity of each member of a target built in F#.
    /// </summary>
    [<Import("fire", "delegate-name-lab")>]
    static member fire (target: EventTarget) : string = jsNative
    /// <summary>
    /// The same target built in JavaScript, for reading the members back into F#.
    /// </summary>
    [<Import("target", "delegate-name-lab")>]
    static member target: EventTarget = jsNative
    /// <summary>
    /// A factory built in JavaScript, so the delegate crosses inward.
    /// </summary>
    [<Import("factory", "delegate-name-lab")>]
    static member factory: Factory = jsNative
    /// <summary>
    /// A factory built in F#, so the delegate crosses outward.
    /// </summary>
    [<Import("drive", "delegate-name-lab")>]
    static member drive (source: Factory) : string = jsNative
    /// <summary>
    /// A unary callback returning a unary callback: retained at the outer level by the nesting rule.
    /// </summary>
    [<Import("callNesting", "delegate-name-lab")>]
    static member callNesting (outer: CallNesting.Outer) : string = jsNative
