// <auto-generated>
//   Generated by Xantham.Generator from callback-function-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CallbackFunctionLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

type Formatter = Func<float, float, string>

/// <summary>
/// A callback carried by an interface member, required and optional.
/// </summary>
[<Interface>]
type Handlers =
    abstract onTick: Func<float, float, string> with get, set
    abstract onDone: Action<float> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (onTick: Func<float, float, string>, ?onDone: Action<float>) : Handlers = jsNative

/// <summary>
/// A method member, which the ParamObject pass binds as a callback-typed Create parameter.
/// </summary>
[<Interface>]
type Options =
    abstract label: string with get, set
    abstract transform: a: float * b: float -> string
    abstract finish: unit -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (label: string, transform: Func<float, float, string>, finish: Action) : Options = jsNative

/// <summary>
/// A callback in return position, at arity 2 and at arity 0.
/// </summary>
[<Interface>]
type Factory =
    abstract make: seed: float -> Func<float, float, string>
    abstract makeOne: seed: float -> Func<float, string>
    abstract makeNone: seed: float -> Func<string>
    abstract makeThree: seed: float -> Func<float, float, float, string>
    abstract ready: Func<string>
    abstract pair: Func<float, float, string>
    [<ParamObject; Emit("$0")>]
    static member Create (make: Func<float, Func<float, float, string>>, makeOne: Func<float, Func<float, string>>, makeNone: Func<float, Func<string>>, makeThree: Func<float, Func<float, float, float, string>>, ready: Func<string>, pair: Func<float, float, string>) : Factory = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A callback of arity 0 in parameter position.
    /// </summary>
    [<Import("callNone", "callback-function-lab")>]
    static member callNone (callback: Func<string>) : string = jsNative
    /// <summary>
    /// A callback of arity 1 in parameter position.
    /// </summary>
    [<Import("callOne", "callback-function-lab")>]
    static member callOne (callback: Func<float, string>) : string = jsNative
    /// <summary>
    /// A callback of arity 2 in parameter position.
    /// </summary>
    [<Import("callTwo", "callback-function-lab")>]
    static member callTwo (callback: Func<float, float, string>) : string = jsNative
    /// <summary>
    /// A callback of arity 3 in parameter position.
    /// </summary>
    [<Import("callThree", "callback-function-lab")>]
    static member callThree (callback: Func<float, float, float, string>) : string = jsNative
    /// <summary>
    /// A callback returning <c>void</c>: the arm that renders <c>Action</c> today.
    /// </summary>
    [<Import("callVoid", "callback-function-lab")>]
    static member callVoid (callback: Action<float>) : float = jsNative
    /// <summary>
    /// The same arm at arity 2, where <c>Action&lt;A, B&gt;</c> has more than one argument to guarantee.
    /// </summary>
    [<Import("callVoidTwo", "callback-function-lab")>]
    static member callVoidTwo (callback: Action<float, float>) : float = jsNative
    /// <summary>
    /// The named callback in parameter position, so the abbreviation is what crosses.
    /// </summary>
    [<Import("callNamed", "callback-function-lab")>]
    static member callNamed (formatter: Formatter) : string = jsNative
    /// <summary>
    /// Reports the arity of each member of a handler object built in F#.
    /// </summary>
    [<Import("fire", "callback-function-lab")>]
    static member fire (handlers: Handlers) : string = jsNative
    /// <summary>
    /// A handler object built in JavaScript, for reading a callback member back into F#.
    /// </summary>
    [<Import("handlers", "callback-function-lab")>]
    static member handlers: Handlers = jsNative
    /// <summary>
    /// Reports the arity of the callback the Create literal carried.
    /// </summary>
    [<Import("build", "callback-function-lab")>]
    static member build (options: Options) : string = jsNative
    [<Import("factory", "callback-function-lab")>]
    static member factory: Factory = jsNative
