// <auto-generated>
//   Generated by Xantham.Generator from callback-function-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CallbackFunctionLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

type Formatter = Func<float, float, string>

/// <summary>
/// A callback carried by an interface member, required and optional.
/// </summary>
[<Interface>]
type Handlers =
    abstract onTick: Func<float, float, string> with get, set
    abstract onDone: (float -> unit) option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (onTick: Func<float, float, string>, ?onDone: (float -> unit)) : Handlers = jsNative

/// <summary>
/// A method member, which the ParamObject pass binds as a callback-typed Create parameter.
/// </summary>
[<Interface>]
type Options =
    abstract label: string with get, set
    abstract transform: a: float * b: float -> string
    abstract finish: unit -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (label: string, transform: Func<float, float, string>, finish: (unit -> unit)) : Options = jsNative

/// <summary>
/// A callback in return position, at arity 2 and at arity 0.
/// </summary>
[<Interface>]
type Factory =
    abstract make: seed: float -> Func<float, float, string>
    abstract makeOne: seed: float -> (float -> string)
    abstract makeNone: seed: float -> (unit -> string)
    abstract makeThree: seed: float -> Func<float, float, float, string>
    abstract ready: (unit -> string)
    abstract pair: Func<float, float, string>
    [<ParamObject; Emit("$0")>]
    static member Create (make: (float -> Func<float, float, string>), makeOne: Func<float, (float -> string)>, makeNone: Func<float, (unit -> string)>, makeThree: (float -> Func<float, float, float, string>), ready: (unit -> string), pair: Func<float, float, string>) : Factory = jsNative

/// <summary>
/// A union of a callback arm and a non-callback arm, the shape the corpus carries as
/// <c>EventListenerOrEventListenerObject</c>. The erased union unwraps at runtime, so what crosses is
/// whichever arm was supplied.
/// </summary>
type Listener = U2<string, (float -> string)>

/// <summary>
/// Union-typed members, at both arities and with the non-callback arm supplied.
/// </summary>
[<Interface>]
type UnionHandlers =
    abstract one: U2<string, (float -> string)> with get, set
    abstract two: U2<string, Func<float, float, string>> with get, set
    abstract text: U2<string, (float -> string)> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (one: U2<string, (float -> string)>, two: U2<string, Func<float, float, string>>, text: U2<string, (float -> string)>) : UnionHandlers = jsNative

/// <summary>
/// The object arm of <c>EventListenerOrEventListenerObject</c>, whose method carries the same arity.
/// </summary>
[<Interface>]
type ListenerObject =
    abstract handleEvent: a: float -> string
    [<ParamObject; Emit("$0")>]
    static member Create (handleEvent: (float -> string)) : ListenerObject = jsNative

/// <summary>
/// A union-typed member one level deeper: behind an array, matching
/// <c>U2&lt;ScopeConstructorCallback, (Scope -&gt; Tickable)&gt;[]</c> on <c>animejs</c>'s <c>Scope</c>.
/// </summary>
[<Interface>]
type ArrayUnionHandlers =
    abstract steps: U2<string, (float -> string)>[] with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (steps: U2<string, (float -> string)>[]) : ArrayUnionHandlers = jsNative

/// <summary>
/// A union-typed member one level deeper: behind an <c>option</c>, matching
/// <c>U2&lt;bool, (ScrollObserver -&gt; bool)&gt; option</c> on <c>animejs</c>'s <c>repeat</c>.
/// </summary>
[<Interface>]
type OptionUnionHandlers =
    abstract step: U2<string, (float -> string)> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?step: U2<string, (float -> string)>) : OptionUnionHandlers = jsNative

/// <summary>
/// The object arm of the nested union below, matching <c>EventListenerObject&lt;Event&gt;</c> in shape.
/// </summary>
[<Interface>]
type UnionListenerObject =
    abstract handleEvent: x: float -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (handleEvent: (float -> unit)) : UnionListenerObject = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A callback of arity 0 in parameter position.
    /// </summary>
    [<Import("callNone", "callback-function-lab")>]
    static member callNone (callback: (unit -> string)) : string = jsNative
    /// <summary>
    /// A callback of arity 1 in parameter position.
    /// </summary>
    [<Import("callOne", "callback-function-lab")>]
    static member callOne (callback: (float -> string)) : string = jsNative
    /// <summary>
    /// A callback of arity 2 in parameter position.
    /// </summary>
    [<Import("callTwo", "callback-function-lab")>]
    static member callTwo (callback: Func<float, float, string>) : string = jsNative
    /// <summary>
    /// A callback of arity 3 in parameter position.
    /// </summary>
    [<Import("callThree", "callback-function-lab")>]
    static member callThree (callback: Func<float, float, float, string>) : string = jsNative
    /// <summary>
    /// A callback returning <c>void</c>: the arm that renders <c>Action</c> today.
    /// </summary>
    [<Import("callVoid", "callback-function-lab")>]
    static member callVoid (callback: (float -> unit)) : float = jsNative
    /// <summary>
    /// The same arm at arity 2, where <c>Action&lt;A, B&gt;</c> has more than one argument to guarantee.
    /// </summary>
    [<Import("callVoidTwo", "callback-function-lab")>]
    static member callVoidTwo (callback: Action<float, float>) : float = jsNative
    /// <summary>
    /// The named callback in parameter position, so the abbreviation is what crosses.
    /// </summary>
    [<Import("callNamed", "callback-function-lab")>]
    static member callNamed (formatter: Formatter) : string = jsNative
    /// <summary>
    /// Reports the arity of each member of a handler object built in F#.
    /// </summary>
    [<Import("fire", "callback-function-lab")>]
    static member fire (handlers: Handlers) : string = jsNative
    /// <summary>
    /// A handler object built in JavaScript, for reading a callback member back into F#.
    /// </summary>
    [<Import("handlers", "callback-function-lab")>]
    static member handlers: Handlers = jsNative
    /// <summary>
    /// Reports the arity of the callback the Create literal carried.
    /// </summary>
    [<Import("build", "callback-function-lab")>]
    static member build (options: Options) : string = jsNative
    [<Import("factory", "callback-function-lab")>]
    static member factory: Factory = jsNative
    /// <summary>
    /// A callback whose own return is a callback. Where only some arities convert, this is the
    /// nesting the rule has to decide: the outer function and the inner one need not agree.
    /// </summary>
    [<Import("callNesting", "callback-function-lab")>]
    static member callNesting (outer: (float -> Func<float, float, string>)) : string = jsNative
    /// <summary>
    /// The same nesting with a unary inner callback, where both levels are alike.
    /// </summary>
    [<Import("callNestingOne", "callback-function-lab")>]
    static member callNestingOne (outer: Func<float, (float -> string)>) : string = jsNative
    /// <summary>
    /// A <c>Factory</c> built in F#, so its callback members cross outward rather than back.
    /// </summary>
    [<Import("drive", "callback-function-lab")>]
    static member drive (factory: Factory) : string = jsNative
    /// <summary>
    /// The named union in parameter position, so the abbreviation is what crosses.
    /// </summary>
    [<Import("callUnionNamed", "callback-function-lab")>]
    static member callUnionNamed (listener: Listener) : string = jsNative
    /// <summary>
    /// A union arm of arity 0 in parameter position.
    /// </summary>
    [<Import("callUnionNone", "callback-function-lab")>]
    static member callUnionNone (listener: U2<string, (unit -> string)>) : string = jsNative
    /// <summary>
    /// A union arm of arity 1 in parameter position.
    /// </summary>
    [<Import("callUnionOne", "callback-function-lab")>]
    static member callUnionOne (listener: U2<string, (float -> string)>) : string = jsNative
    /// <summary>
    /// A union arm of arity 2 in parameter position, where the delegate is retained.
    /// </summary>
    [<Import("callUnionTwo", "callback-function-lab")>]
    static member callUnionTwo (listener: U2<string, Func<float, float, string>>) : string = jsNative
    /// <summary>
    /// A union arm in return position at arity 1.
    /// </summary>
    [<Import("makeUnionOne", "callback-function-lab")>]
    static member makeUnionOne (seed: float) : U2<string, (float -> string)> = jsNative
    /// <summary>
    /// A union arm in return position at arity 2.
    /// </summary>
    [<Import("makeUnionTwo", "callback-function-lab")>]
    static member makeUnionTwo (seed: float) : U2<string, Func<float, float, string>> = jsNative
    /// <summary>
    /// A union-typed member object built in JavaScript, for reading a callback arm back into F#.
    /// </summary>
    [<Import("unionHandlers", "callback-function-lab")>]
    static member unionHandlers: UnionHandlers = jsNative
    /// <summary>
    /// Reports the arity of each union-typed member of an object built in F#.
    /// </summary>
    [<Import("fireUnion", "callback-function-lab")>]
    static member fireUnion (handlers: UnionHandlers) : string = jsNative
    /// <summary>
    /// The corpus shape exactly: a callback arm beside an object arm rather than beside a primitive.
    /// </summary>
    [<Import("callUnionObject", "callback-function-lab")>]
    static member callUnionObject (listener: U2<ListenerObject, (float -> string)>) : string = jsNative
    /// <summary>
    /// The same union built in JavaScript, for reading the callback arm back into F#.
    /// </summary>
    [<Import("objectUnion", "callback-function-lab")>]
    static member objectUnion: U2<ListenerObject, (float -> string)> = jsNative
    /// <summary>
    /// Reports the arity of each element of the array member built in F#.
    /// </summary>
    [<Import("fireArrayUnion", "callback-function-lab")>]
    static member fireArrayUnion (handlers: ArrayUnionHandlers) : string = jsNative
    /// <summary>
    /// The same array member built in JavaScript, for reading its callback arm back into F#.
    /// </summary>
    [<Import("arrayUnionHandlers", "callback-function-lab")>]
    static member arrayUnionHandlers: ArrayUnionHandlers = jsNative
    /// <summary>
    /// Reports the arity of the optional member built in F#, or its absence.
    /// </summary>
    [<Import("fireOptionUnion", "callback-function-lab")>]
    static member fireOptionUnion (handlers: OptionUnionHandlers) : string = jsNative
    /// <summary>
    /// The optional member present, built in JavaScript.
    /// </summary>
    [<Import("optionUnionHandlersSome", "callback-function-lab")>]
    static member optionUnionHandlersSome: OptionUnionHandlers = jsNative
    /// <summary>
    /// The optional member absent, built in JavaScript.
    /// </summary>
    [<Import("optionUnionHandlersNone", "callback-function-lab")>]
    static member optionUnionHandlersNone: OptionUnionHandlers = jsNative
    /// <summary>
    /// A two-argument void callback whose second parameter is itself a union of a function arm and an
    /// object arm - the shape <c>Action&lt;'Type, U2&lt;(obj -&gt; unit), EventListenerObject&lt;Event&gt;&gt;, ...&gt;</c>
    /// carries on <c>EventTarget</c>'s <c>Create</c> in <c>@cloudflare/workers-types</c>. The outer callback converts
    /// to <c>Action</c> by the arity rule already measured; whether the inner union arm keeps its own arity
    /// once nested inside the delegate's own type parameter is what this measures.
    /// </summary>
    [<Import("addListener", "callback-function-lab")>]
    static member addListener (register: Action<string, U2<UnionListenerObject, (float -> unit)>>) : unit = jsNative
