// <auto-generated>
//   Generated by Xantham.Generator from ambient-provider-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec AmbientProviderLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type HostBinding =
    abstract name: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (name: string) : HostBinding = jsNative

[<Interface>]
type RuntimeHandle =
    abstract send: payload: string -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (send: (string -> unit)) : RuntimeHandle = jsNative
