// <auto-generated>
//   Generated by Xantham.Generator from setter-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec SetterLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Erase>]
type Setter<'T, 'U> = private Setter__ of (obj -> obj)

[<Erase>]
type Distinct<'T, 'A, 'B> = private Distinct__ of ('A -> 'A)

[<Erase>]
type Single<'T, 'U> = private Single__ of ('U -> 'U)

/// <summary>
/// Reference positions, including the empty-tuple rest <c>Setter&lt;string | undefined&gt;</c> reaches.
/// </summary>
type Holder =
    abstract setter<'U>: args: U2<'U, (string -> 'U)> -> 'U
    abstract setter<'U>: value: (string -> 'U) -> 'U
    abstract setter<'U>: value: 'U -> 'U
    abstract optional: unit -> unit
    abstract optional<'U>: value: (string option -> 'U) -> 'U
    abstract optional<'U>: value: 'U -> 'U
    abstract distinct<'A>: value: 'A -> 'A
    abstract single: (obj -> obj) with get, set
    abstract divergent<'U>: value: 'U -> 'U
