// <auto-generated>
//   Generated by Xantham.Generator from setter-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec SetterLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Erase>]
type Setter<'T, 'U> = private Setter__ of (obj -> obj)

[<Erase>]
type Distinct<'T, 'A, 'B> = private Distinct__ of ('A -> 'A)

[<Erase>]
type Single<'T, 'U> = private Single__ of ('U -> 'U)

/// <summary>
/// Reference positions, including the empty-tuple rest <c>Setter&lt;string | undefined&gt;</c> reaches.
/// </summary>
[<Interface>]
type Holder =
    abstract setter: (obj -> obj) with get, set
    abstract optional: (unit -> unit) with get, set
    abstract distinct: (obj -> obj) with get, set
    abstract single: (obj -> obj) with get, set
    abstract divergent: (obj -> obj) with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (setter: (obj -> obj), optional: (unit -> unit), distinct: (obj -> obj), single: (obj -> obj), divergent: (obj -> obj)) : Holder = jsNative
