// <auto-generated>
//   Generated by Xantham.Generator from intrinsic-owner-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec Identity.Support.IntrinsicOwnerLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Item =
    abstract nested: Item.Nested with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (nested: Item.Nested) : Item = jsNative

module Item =
    [<Interface>]
    type Nested =
        abstract value: string with get, set
        abstract count: float with get, set
        abstract enabled: bool with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (value: string, count: float, enabled: bool) : Nested = jsNative
