// <auto-generated>
//   Generated by Xantham.Generator from keyof-overload-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec KeyofOverloadLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS

[<Interface>]
type Div =
    abstract div: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (div: string) : Div = jsNative

[<Interface>]
type Span =
    abstract span: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (span: string) : Span = jsNative

[<Interface>]
type HtmlTags =
    abstract div: Div with get, set
    abstract span: Span with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (div: Div, span: Span) : HtmlTags = jsNative

[<Interface>]
type SvgTags =
    abstract circle: Div with get, set
    abstract rect: Span with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (circle: Div, rect: Span) : SvgTags = jsNative

type Finder =
    /// <summary>
    /// Separated by which key set the parameter is bounded to, and by nothing else.
    /// </summary>
    abstract find<'K>: selector: 'K -> U2<Div, Span>
    /// <summary>
    /// Separated by which key set the parameter is bounded to, and by nothing else.
    /// </summary>
    abstract find: selector: string -> Div
    /// <summary>
    /// The negative: a nominal bound, erased the same way, still reports a plain drop.
    /// </summary>
    abstract pick<'T when 'T :> Div>: value: 'T -> unit
