// <auto-generated>
//   Generated by Xantham.Generator from literal-overload-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec LiteralOverloadLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// Options an overload selects with a literal type argument rather than a literal parameter.
/// </summary>
[<Interface>]
type ReadOptions<'Kind> =
    abstract kind: 'Kind with get, set
    abstract cacheTtl: float option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (kind: 'Kind, ?cacheTtl: float) : ReadOptions<'Kind> = jsNative

[<Interface>]
type Chunk =
    abstract size: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (size: float) : Chunk = jsNative

/// <summary>
/// The construct. Six overloads over two colliding groups: three tell themselves apart by a
/// literal-typed <c>kind</c> parameter, two more by the literal a <c>ReadOptions</c> argument carries, and
/// the sixth stands alone because <c>ReadOptions&lt;undefined&gt;</c> carries no literal at all.
/// </summary>
type Store =
    abstract read: key: string * ?options: ReadOptions<unit> -> JS.Promise<string option>
    abstract read: key: string * kind: Store.Text -> JS.Promise<string option>
    abstract read: key: string * kind: Store.Json -> JS.Promise<obj>
    abstract read: key: string * kind: Store.Bytes -> JS.Promise<Chunk option>
    abstract read: key: string * ?options: ReadOptions<Store.Text> -> JS.Promise<string option>
    abstract read: key: string * ?options: ReadOptions<Store.Bytes> -> JS.Promise<Chunk option>

module Store =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Bytes =
        | [<CompiledName("bytes")>] Bytes

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Json =
        | [<CompiledName("json")>] Json

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Text =
        | [<CompiledName("text")>] Text

/// <summary>
/// Negative: one signature, so the literal separates nothing and widens to <c>string</c>.
/// </summary>
[<Interface>]
type Solo =
    abstract tag: name: string -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (tag: (string -> unit)) : Solo = jsNative

/// <summary>
/// Negative: a property typed by a literal the overload set above also carries. The checker
/// interns a literal type, so this pins retention as a property of the position rather than of
/// the type.
/// </summary>
[<Interface>]
type Label =
    abstract kind: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string) : Label = jsNative

/// <summary>
/// Negative: the parameter lists differ before the literal is read, so nothing collides.
/// </summary>
type Mixed =
    abstract send: body: string * mode: string -> unit
    abstract send: body: float * mode: string -> unit

/// <summary>
/// Negative: a union of literals per position, which one literal type cannot stand for.
/// </summary>
type Choice =
    abstract pick: kind: Choice.Pick.Kind -> unit
    abstract pick: kind: Choice.Pick.Kind2 -> unit

module Choice =
    module Pick =
        [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
        type Kind =
            | [<CompiledName("a")>] A
            | [<CompiledName("b")>] B

        [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
        type Kind2 =
            | [<CompiledName("c")>] C
            | [<CompiledName("d")>] D

/// <summary>
/// Negative: a collision no literal is party to, which drops an overload as it always did.
/// </summary>
type Widen =
    abstract scan: input: obj -> unit
