// <auto-generated>
//   Generated by Xantham.Generator from catalog-generic-defaults-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CatalogGenericDefaultsLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Def =
    abstract id: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (id: string) : Def = jsNative

[<Interface>]
type Result<'T when 'T :> Def> =
    abstract definition: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (definition: 'T) : Result<'T> = jsNative

[<Interface>]
type Middleware<'U when 'U :> Def> =
    abstract callback: (unit -> Middleware.Callback.Result<'U>) option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?callback: (unit -> Middleware.Callback.Result<'U>)) : Middleware<'U> = jsNative

[<Interface>]
type Defaults =
    abstract middleware: Middleware<Def> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (middleware: Middleware<Def>) : Defaults = jsNative

[<Interface>]
type Bound<'T> =
    abstract value: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T) : Bound<'T> = jsNative

[<Interface>]
type Applied<'U when 'U :> Bound<string>> =
    abstract value: 'U with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'U) : Applied<'U> = jsNative

type AnyApplied = Applied<Bound<string>>

type NeverApplied = Applied<Bound<string>>

[<Interface>]
type InheritedApplied =
    inherit Applied<Bound<string>>
    abstract value: unit
    [<ParamObject; Emit("$0")>]
    static member Create () : InheritedApplied = jsNative

[<Interface>]
type StringBound =
    inherit Bound<string>
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string) : StringBound = jsNative

[<Interface>]
type NumberBound =
    inherit Bound<float>
    abstract value: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: float) : NumberBound = jsNative

type StringApplied = Applied<StringBound>

[<Interface>]
type Erased<'U when 'U :> Bound<obj>> =
    abstract value: 'U with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'U) : Erased<'U> = jsNative

type ErasedString = Erased<Bound<obj>>

[<Interface>]
type Recursive<'T when 'T :> Recursive<'T>> =
    abstract next: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (next: 'T) : Recursive<'T> = jsNative

[<Interface>]
type RecursiveValue =
    inherit Recursive<RecursiveValue>
    abstract next: RecursiveValue with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (next: RecursiveValue) : RecursiveValue = jsNative

type RecursiveUse = Recursive<RecursiveValue>

module Middleware =
    module Callback =
        [<Interface>]
        type Result<'U when 'U :> Def> =
            abstract definition: 'U with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (definition: 'U) : Result<'U> = jsNative
