namespace Xantham.TypeScript.Wire

// <auto-generated>
//   Generated by tools/tsc-ast/generate-ast.mts from microsoft/TypeScript@9a8581c393a3
//   at packages/typescript/src/enums.
//   Do not edit by hand - re-run the generator when the pinned schema moves.
// </auto-generated>

// The compiler's own flag and kind enums.
//
// These are the words the checker answers with - `SymbolResponse.Flags` is a `SymbolFlags`,
// `TypeResponse.Flags` is a `TypeFlags` - and the two `Ast` reads straight off a node,
// `NodeFlags` and `TokenFlags`.
//
// Each enum arrives in two halves. The cases are the bits upstream defines, spelled as it spells
// them (`1u <<< 23`, not `8388608u`); the companion module holds the members upstream builds by
// combining those bits, as `[<Literal>]` values computed the same way. `SymbolFlags.Property` and
// `SymbolFlags.Value` both still resolve, so which half a name landed in does not matter to a
// caller, and a literal is still usable as a match pattern.
//
// The split is forced: an enum case may not name another case of its own enum. A composite that
// mixes in a bare integer - `SymbolFlags.All = (1 << 30) - 1` - has no enum type to be written at
// and stays a case, carrying upstream's spelling as a comment.
//
// Duplicate values are kept rather than dropped, and F# permits them: `ObjectFlags` reuses its
// high bits across disjoint categories of type, so eight of its bits carry two or three names.
// `ToString` reports the first name declared at a value, which is upstream order.

/// `SymbolFlags`, from `tsc/internal/ast/symbolflags.go` upstream.
[<System.Flags>]
type SymbolFlags =
    | None = 0u
    | FunctionScopedVariable = (1u <<< 0)
    | BlockScopedVariable = (1u <<< 1)
    | Property = (1u <<< 2)
    | EnumMember = (1u <<< 3)
    | Function = (1u <<< 4)
    | Class = (1u <<< 5)
    | Interface = (1u <<< 6)
    | ConstEnum = (1u <<< 7)
    | RegularEnum = (1u <<< 8)
    | ValueModule = (1u <<< 9)
    | NamespaceModule = (1u <<< 10)
    | TypeLiteral = (1u <<< 11)
    | ObjectLiteral = (1u <<< 12)
    | Method = (1u <<< 13)
    | Constructor = (1u <<< 14)
    | GetAccessor = (1u <<< 15)
    | SetAccessor = (1u <<< 16)
    | Signature = (1u <<< 17)
    | TypeParameter = (1u <<< 18)
    | TypeAlias = (1u <<< 19)
    | ExportValue = (1u <<< 20)
    | Alias = (1u <<< 21)
    | Prototype = (1u <<< 22)
    | ExportStar = (1u <<< 23)
    | Optional = (1u <<< 24)
    | Transient = (1u <<< 25)
    | Assignment = (1u <<< 26)
    | ModuleExports = (1u <<< 27)
    | ConstEnumOnlyModule = (1u <<< 28)
    | ReplaceableByMethod = (1u <<< 29)
    | GlobalLookup = (1u <<< 30)
    /// <summary><code>(1 &lt;&lt; 30) - 1</code></summary>
    | All = 1073741823u

/// Composite `SymbolFlags` values, computed from the cases above rather than written out.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module SymbolFlags =

    /// <summary><code>RegularEnum | ConstEnum</code></summary><returns><c>384u</c></returns>
    [<Literal>]
    let Enum = (SymbolFlags.RegularEnum ||| SymbolFlags.ConstEnum)

    /// <summary><code>FunctionScopedVariable | BlockScopedVariable</code></summary><returns><c>3u</c></returns>
    [<Literal>]
    let Variable = (SymbolFlags.FunctionScopedVariable ||| SymbolFlags.BlockScopedVariable)

    /// <summary><code>Variable | Property | EnumMember | ObjectLiteral | Function | Class | Enum | ValueModule | Method | GetAccessor | SetAccessor</code></summary><returns><c>111551u</c></returns>
    [<Literal>]
    let Value = ((((((((((Variable ||| SymbolFlags.Property) ||| SymbolFlags.EnumMember) ||| SymbolFlags.ObjectLiteral) ||| SymbolFlags.Function) ||| SymbolFlags.Class) ||| Enum) ||| SymbolFlags.ValueModule) ||| SymbolFlags.Method) ||| SymbolFlags.GetAccessor) ||| SymbolFlags.SetAccessor)

    /// <summary><code>Class | Interface | Enum | EnumMember | TypeLiteral | TypeParameter | TypeAlias</code></summary><returns><c>788968u</c></returns>
    [<Literal>]
    let Type = ((((((SymbolFlags.Class ||| SymbolFlags.Interface) ||| Enum) ||| SymbolFlags.EnumMember) ||| SymbolFlags.TypeLiteral) ||| SymbolFlags.TypeParameter) ||| SymbolFlags.TypeAlias)

    /// <summary><code>ValueModule | NamespaceModule | Enum</code></summary><returns><c>1920u</c></returns>
    [<Literal>]
    let Namespace = ((SymbolFlags.ValueModule ||| SymbolFlags.NamespaceModule) ||| Enum)

    /// <summary><code>ValueModule | NamespaceModule</code></summary><returns><c>1536u</c></returns>
    [<Literal>]
    let Module = (SymbolFlags.ValueModule ||| SymbolFlags.NamespaceModule)

    /// <summary><code>GetAccessor | SetAccessor</code></summary><returns><c>98304u</c></returns>
    [<Literal>]
    let Accessor = (SymbolFlags.GetAccessor ||| SymbolFlags.SetAccessor)

    /// <summary><code>Value &amp; ~FunctionScopedVariable</code></summary><returns><c>111550u</c></returns>
    [<Literal>]
    let FunctionScopedVariableExcludes = (Value &&& (~~~SymbolFlags.FunctionScopedVariable))

    /// <summary><code>Value</code></summary><returns><c>111551u</c></returns>
    [<Literal>]
    let BlockScopedVariableExcludes = Value

    /// <summary><code>Value</code></summary><returns><c>111551u</c></returns>
    [<Literal>]
    let ParameterExcludes = Value

    /// <summary><code>Value &amp; ~(Property | Accessor)</code></summary><returns><c>13243u</c></returns>
    [<Literal>]
    let PropertyExcludes = (Value &&& (~~~(SymbolFlags.Property ||| Accessor)))

    /// <summary><code>Value | Type</code></summary><returns><c>900095u</c></returns>
    [<Literal>]
    let EnumMemberExcludes = (Value ||| Type)

    /// <summary><code>Value &amp; ~(Function | ValueModule | Class)</code></summary><returns><c>110991u</c></returns>
    [<Literal>]
    let FunctionExcludes = (Value &&& (~~~((SymbolFlags.Function ||| SymbolFlags.ValueModule) ||| SymbolFlags.Class)))

    /// <summary><code>(Value | Type) &amp; ~(ValueModule | Interface | Function)</code></summary><returns><c>899503u</c></returns>
    [<Literal>]
    let ClassExcludes = ((Value ||| Type) &&& (~~~((SymbolFlags.ValueModule ||| SymbolFlags.Interface) ||| SymbolFlags.Function)))

    /// <summary><code>Type &amp; ~(Interface | Class)</code></summary><returns><c>788872u</c></returns>
    [<Literal>]
    let InterfaceExcludes = (Type &&& (~~~(SymbolFlags.Interface ||| SymbolFlags.Class)))

    /// <summary><code>(Value | Type) &amp; ~(RegularEnum | ValueModule)</code></summary><returns><c>899327u</c></returns>
    [<Literal>]
    let RegularEnumExcludes = ((Value ||| Type) &&& (~~~(SymbolFlags.RegularEnum ||| SymbolFlags.ValueModule)))

    /// <summary><code>(Value | Type) &amp; ~ConstEnum</code></summary><returns><c>899967u</c></returns>
    [<Literal>]
    let ConstEnumExcludes = ((Value ||| Type) &&& (~~~SymbolFlags.ConstEnum))

    /// <summary><code>Value &amp; ~(Function | Class | RegularEnum | ValueModule)</code></summary><returns><c>110735u</c></returns>
    [<Literal>]
    let ValueModuleExcludes = (Value &&& (~~~(((SymbolFlags.Function ||| SymbolFlags.Class) ||| SymbolFlags.RegularEnum) ||| SymbolFlags.ValueModule)))

    /// <summary><code>None</code></summary><returns><c>0u</c></returns>
    [<Literal>]
    let NamespaceModuleExcludes = SymbolFlags.None

    /// <summary><code>Value &amp; ~Method</code></summary><returns><c>103359u</c></returns>
    [<Literal>]
    let MethodExcludes = (Value &&& (~~~SymbolFlags.Method))

    /// <summary><code>Value &amp; ~(SetAccessor | Property)</code></summary><returns><c>46011u</c></returns>
    [<Literal>]
    let GetAccessorExcludes = (Value &&& (~~~(SymbolFlags.SetAccessor ||| SymbolFlags.Property)))

    /// <summary><code>Value &amp; ~(GetAccessor | Property)</code></summary><returns><c>78779u</c></returns>
    [<Literal>]
    let SetAccessorExcludes = (Value &&& (~~~(SymbolFlags.GetAccessor ||| SymbolFlags.Property)))

    /// <summary><code>Value &amp; ~Property</code></summary><returns><c>111547u</c></returns>
    [<Literal>]
    let AccessorExcludes = (Value &&& (~~~SymbolFlags.Property))

    /// <summary><code>Type &amp; ~TypeParameter</code></summary><returns><c>526824u</c></returns>
    [<Literal>]
    let TypeParameterExcludes = (Type &&& (~~~SymbolFlags.TypeParameter))

    /// <summary><code>Type</code></summary><returns><c>788968u</c></returns>
    [<Literal>]
    let TypeAliasExcludes = Type

    /// <summary><code>Alias</code></summary><returns><c>2097152u</c></returns>
    [<Literal>]
    let AliasExcludes = SymbolFlags.Alias

    /// <summary><code>Variable | Function | Class | Interface | Enum | Module | TypeAlias | Alias</code></summary><returns><c>2623475u</c></returns>
    [<Literal>]
    let ModuleMember = (((((((Variable ||| SymbolFlags.Function) ||| SymbolFlags.Class) ||| SymbolFlags.Interface) ||| Enum) ||| Module) ||| SymbolFlags.TypeAlias) ||| SymbolFlags.Alias)

    /// <summary><code>Function | Class | Enum | ValueModule</code></summary><returns><c>944u</c></returns>
    [<Literal>]
    let ExportHasLocal = (((SymbolFlags.Function ||| SymbolFlags.Class) ||| Enum) ||| SymbolFlags.ValueModule)

    /// <summary><code>BlockScopedVariable | Class | Enum</code></summary><returns><c>418u</c></returns>
    [<Literal>]
    let BlockScoped = ((SymbolFlags.BlockScopedVariable ||| SymbolFlags.Class) ||| Enum)

    /// <summary><code>Property | Accessor</code></summary><returns><c>98308u</c></returns>
    [<Literal>]
    let PropertyOrAccessor = (SymbolFlags.Property ||| Accessor)

    /// <summary><code>Method | Accessor | Property</code></summary><returns><c>106500u</c></returns>
    [<Literal>]
    let ClassMember = ((SymbolFlags.Method ||| Accessor) ||| SymbolFlags.Property)

    /// <summary><code>Class | Function | Interface</code></summary><returns><c>112u</c></returns>
    [<Literal>]
    let ExportSupportsDefaultModifier = ((SymbolFlags.Class ||| SymbolFlags.Function) ||| SymbolFlags.Interface)

    /// <summary><code>~ExportSupportsDefaultModifier</code></summary><returns><c>4294967183u</c></returns>
    [<Literal>]
    let ExportDoesNotSupportDefaultModifier = (~~~ExportSupportsDefaultModifier)

    /// <summary><code>Class | Interface | TypeLiteral | ObjectLiteral | Function</code></summary><returns><c>6256u</c></returns>
    [<Literal>]
    let LateBindingContainer = ((((SymbolFlags.Class ||| SymbolFlags.Interface) ||| SymbolFlags.TypeLiteral) ||| SymbolFlags.ObjectLiteral) ||| SymbolFlags.Function)

/// `CheckFlags`, from `tsc/internal/ast/checkflags.go` upstream.
[<System.Flags>]
type CheckFlags =
    | None = 0u
    | Instantiated = (1u <<< 0)
    | SyntheticProperty = (1u <<< 1)
    | SyntheticMethod = (1u <<< 2)
    | Readonly = (1u <<< 3)
    | ReadPartial = (1u <<< 4)
    | WritePartial = (1u <<< 5)
    | HasNonUniformType = (1u <<< 6)
    | HasLiteralType = (1u <<< 7)
    | ContainsPublic = (1u <<< 8)
    | ContainsProtected = (1u <<< 9)
    | ContainsPrivate = (1u <<< 10)
    | ContainsWritePublic = (1u <<< 11)
    | ContainsWriteProtected = (1u <<< 12)
    | ContainsWritePrivate = (1u <<< 13)
    | ContainsStatic = (1u <<< 14)
    | Late = (1u <<< 15)
    | ReverseMapped = (1u <<< 16)
    | OptionalParameter = (1u <<< 17)
    | RestParameter = (1u <<< 18)
    | DeferredType = (1u <<< 19)
    | HasNeverType = (1u <<< 20)
    | Mapped = (1u <<< 21)
    | StripOptional = (1u <<< 22)
    | Unresolved = (1u <<< 23)
    | IsDiscriminantComputed = (1u <<< 24)
    | IsDiscriminant = (1u <<< 25)
    | IndexSymbol = (1u <<< 26)

/// Composite `CheckFlags` values, computed from the cases above rather than written out.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module CheckFlags =

    /// <summary><code>SyntheticProperty | SyntheticMethod</code></summary><returns><c>6u</c></returns>
    [<Literal>]
    let Synthetic = (CheckFlags.SyntheticProperty ||| CheckFlags.SyntheticMethod)

    /// <summary><code>HasNonUniformType | HasLiteralType</code></summary><returns><c>192u</c></returns>
    [<Literal>]
    let NonUniformAndLiteral = (CheckFlags.HasNonUniformType ||| CheckFlags.HasLiteralType)

    /// <summary><code>ReadPartial | WritePartial</code></summary><returns><c>48u</c></returns>
    [<Literal>]
    let Partial = (CheckFlags.ReadPartial ||| CheckFlags.WritePartial)

/// `TypeFlags`, from `tsc/internal/checker/types.go` upstream.
[<System.Flags>]
type TypeFlags =
    | None = 0u
    | Any = (1u <<< 0)
    | Unknown = (1u <<< 1)
    | Undefined = (1u <<< 2)
    | Null = (1u <<< 3)
    | Void = (1u <<< 4)
    | String = (1u <<< 5)
    | Number = (1u <<< 6)
    | BigInt = (1u <<< 7)
    | Boolean = (1u <<< 8)
    | ESSymbol = (1u <<< 9)
    | StringLiteral = (1u <<< 10)
    | NumberLiteral = (1u <<< 11)
    | BigIntLiteral = (1u <<< 12)
    | BooleanLiteral = (1u <<< 13)
    | UniqueESSymbol = (1u <<< 14)
    | EnumLiteral = (1u <<< 15)
    | Enum = (1u <<< 16)
    | NonPrimitive = (1u <<< 17)
    | Never = (1u <<< 18)
    | TypeParameter = (1u <<< 19)
    | Object = (1u <<< 20)
    | Index = (1u <<< 21)
    | TemplateLiteral = (1u <<< 22)
    | StringMapping = (1u <<< 23)
    | Substitution = (1u <<< 24)
    | IndexedAccess = (1u <<< 25)
    | Conditional = (1u <<< 26)
    | Union = (1u <<< 27)
    | Intersection = (1u <<< 28)
    | Reserved1 = (1u <<< 29)
    | Reserved2 = (1u <<< 30)
    | Reserved3 = (1u <<< 31)

/// Composite `TypeFlags` values, computed from the cases above rather than written out.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module TypeFlags =

    /// <summary><code>Any | Unknown</code></summary><returns><c>3u</c></returns>
    [<Literal>]
    let AnyOrUnknown = (TypeFlags.Any ||| TypeFlags.Unknown)

    /// <summary><code>Undefined | Null</code></summary><returns><c>12u</c></returns>
    [<Literal>]
    let Nullable = (TypeFlags.Undefined ||| TypeFlags.Null)

    /// <summary><code>StringLiteral | NumberLiteral | BigIntLiteral | BooleanLiteral</code></summary><returns><c>15360u</c></returns>
    [<Literal>]
    let Literal = (((TypeFlags.StringLiteral ||| TypeFlags.NumberLiteral) ||| TypeFlags.BigIntLiteral) ||| TypeFlags.BooleanLiteral)

    /// <summary><code>Enum | Literal | UniqueESSymbol | Nullable</code></summary><returns><c>97292u</c></returns>
    [<Literal>]
    let Unit = (((TypeFlags.Enum ||| Literal) ||| TypeFlags.UniqueESSymbol) ||| Nullable)

    /// <summary><code>Enum | Literal</code></summary><returns><c>80896u</c></returns>
    [<Literal>]
    let Freshable = (TypeFlags.Enum ||| Literal)

    /// <summary><code>StringLiteral | NumberLiteral</code></summary><returns><c>3072u</c></returns>
    [<Literal>]
    let StringOrNumberLiteral = (TypeFlags.StringLiteral ||| TypeFlags.NumberLiteral)

    /// <summary><code>StringLiteral | NumberLiteral | UniqueESSymbol</code></summary><returns><c>19456u</c></returns>
    [<Literal>]
    let StringOrNumberLiteralOrUnique = ((TypeFlags.StringLiteral ||| TypeFlags.NumberLiteral) ||| TypeFlags.UniqueESSymbol)

    /// <summary><code>StringLiteral | NumberLiteral | BigIntLiteral | BooleanLiteral | Void | Undefined | Null</code></summary><returns><c>15388u</c></returns>
    [<Literal>]
    let DefinitelyFalsy = ((((((TypeFlags.StringLiteral ||| TypeFlags.NumberLiteral) ||| TypeFlags.BigIntLiteral) ||| TypeFlags.BooleanLiteral) ||| TypeFlags.Void) ||| TypeFlags.Undefined) ||| TypeFlags.Null)

    /// <summary><code>DefinitelyFalsy | String | Number | BigInt | Boolean</code></summary><returns><c>15868u</c></returns>
    [<Literal>]
    let PossiblyFalsy = ((((DefinitelyFalsy ||| TypeFlags.String) ||| TypeFlags.Number) ||| TypeFlags.BigInt) ||| TypeFlags.Boolean)

    /// <summary><code>Any | Unknown | String | Number | BigInt | ESSymbol | Void | Undefined | Null | Never | NonPrimitive</code></summary><returns><c>393983u</c></returns>
    [<Literal>]
    let Intrinsic = ((((((((((TypeFlags.Any ||| TypeFlags.Unknown) ||| TypeFlags.String) ||| TypeFlags.Number) ||| TypeFlags.BigInt) ||| TypeFlags.ESSymbol) ||| TypeFlags.Void) ||| TypeFlags.Undefined) ||| TypeFlags.Null) ||| TypeFlags.Never) ||| TypeFlags.NonPrimitive)

    /// <summary><code>String | StringLiteral | TemplateLiteral | StringMapping</code></summary><returns><c>12583968u</c></returns>
    [<Literal>]
    let StringLike = (((TypeFlags.String ||| TypeFlags.StringLiteral) ||| TypeFlags.TemplateLiteral) ||| TypeFlags.StringMapping)

    /// <summary><code>Number | NumberLiteral | Enum</code></summary><returns><c>67648u</c></returns>
    [<Literal>]
    let NumberLike = ((TypeFlags.Number ||| TypeFlags.NumberLiteral) ||| TypeFlags.Enum)

    /// <summary><code>BigInt | BigIntLiteral</code></summary><returns><c>4224u</c></returns>
    [<Literal>]
    let BigIntLike = (TypeFlags.BigInt ||| TypeFlags.BigIntLiteral)

    /// <summary><code>Boolean | BooleanLiteral</code></summary><returns><c>8448u</c></returns>
    [<Literal>]
    let BooleanLike = (TypeFlags.Boolean ||| TypeFlags.BooleanLiteral)

    /// <summary><code>Enum | EnumLiteral</code></summary><returns><c>98304u</c></returns>
    [<Literal>]
    let EnumLike = (TypeFlags.Enum ||| TypeFlags.EnumLiteral)

    /// <summary><code>ESSymbol | UniqueESSymbol</code></summary><returns><c>16896u</c></returns>
    [<Literal>]
    let ESSymbolLike = (TypeFlags.ESSymbol ||| TypeFlags.UniqueESSymbol)

    /// <summary><code>Void | Undefined</code></summary><returns><c>20u</c></returns>
    [<Literal>]
    let VoidLike = (TypeFlags.Void ||| TypeFlags.Undefined)

    /// <summary><code>StringLike | NumberLike | BigIntLike | BooleanLike | EnumLike | ESSymbolLike | VoidLike | Null</code></summary><returns><c>12713980u</c></returns>
    [<Literal>]
    let Primitive = (((((((StringLike ||| NumberLike) ||| BigIntLike) ||| BooleanLike) ||| EnumLike) ||| ESSymbolLike) ||| VoidLike) ||| TypeFlags.Null)

    /// <summary><code>StringLike | NumberLike | BigIntLike | BooleanLike | EnumLike | ESSymbolLike | Object | NonPrimitive</code></summary><returns><c>13893600u</c></returns>
    [<Literal>]
    let DefinitelyNonNullable = (((((((StringLike ||| NumberLike) ||| BigIntLike) ||| BooleanLike) ||| EnumLike) ||| ESSymbolLike) ||| TypeFlags.Object) ||| TypeFlags.NonPrimitive)

    /// <summary><code>NonPrimitive | StringLike | NumberLike | BigIntLike | BooleanLike | ESSymbolLike | VoidLike | Null</code></summary><returns><c>12812284u</c></returns>
    [<Literal>]
    let DisjointDomains = (((((((TypeFlags.NonPrimitive ||| StringLike) ||| NumberLike) ||| BigIntLike) ||| BooleanLike) ||| ESSymbolLike) ||| VoidLike) ||| TypeFlags.Null)

    /// <summary><code>Union | Intersection</code></summary><returns><c>402653184u</c></returns>
    [<Literal>]
    let UnionOrIntersection = (TypeFlags.Union ||| TypeFlags.Intersection)

    /// <summary><code>Object | Union | Intersection</code></summary><returns><c>403701760u</c></returns>
    [<Literal>]
    let StructuredType = ((TypeFlags.Object ||| TypeFlags.Union) ||| TypeFlags.Intersection)

    /// <summary><code>TypeParameter | IndexedAccess</code></summary><returns><c>34078720u</c></returns>
    [<Literal>]
    let TypeVariable = (TypeFlags.TypeParameter ||| TypeFlags.IndexedAccess)

    /// <summary><code>TypeVariable | Conditional | Substitution</code></summary><returns><c>117964800u</c></returns>
    [<Literal>]
    let InstantiableNonPrimitive = ((TypeVariable ||| TypeFlags.Conditional) ||| TypeFlags.Substitution)

    /// <summary><code>Index | TemplateLiteral | StringMapping</code></summary><returns><c>14680064u</c></returns>
    [<Literal>]
    let InstantiablePrimitive = ((TypeFlags.Index ||| TypeFlags.TemplateLiteral) ||| TypeFlags.StringMapping)

    /// <summary><code>InstantiableNonPrimitive | InstantiablePrimitive</code></summary><returns><c>132644864u</c></returns>
    [<Literal>]
    let Instantiable = (InstantiableNonPrimitive ||| InstantiablePrimitive)

    /// <summary><code>StructuredType | Instantiable</code></summary><returns><c>536346624u</c></returns>
    [<Literal>]
    let StructuredOrInstantiable = (StructuredType ||| Instantiable)

    /// <summary><code>Any | Nullable | Never | Object | Union | Intersection</code></summary><returns><c>403963917u</c></returns>
    [<Literal>]
    let ObjectFlagsType = (((((TypeFlags.Any ||| Nullable) ||| TypeFlags.Never) ||| TypeFlags.Object) ||| TypeFlags.Union) ||| TypeFlags.Intersection)

    /// <summary><code>IndexedAccess | Conditional | Index</code></summary><returns><c>102760448u</c></returns>
    [<Literal>]
    let Simplifiable = ((TypeFlags.IndexedAccess ||| TypeFlags.Conditional) ||| TypeFlags.Index)

    /// <summary><code>Any | Unknown | String | Number | Boolean | BigInt | ESSymbol | Void | Undefined | Null | Never | NonPrimitive</code></summary><returns><c>394239u</c></returns>
    [<Literal>]
    let Singleton = (((((((((((TypeFlags.Any ||| TypeFlags.Unknown) ||| TypeFlags.String) ||| TypeFlags.Number) ||| TypeFlags.Boolean) ||| TypeFlags.BigInt) ||| TypeFlags.ESSymbol) ||| TypeFlags.Void) ||| TypeFlags.Undefined) ||| TypeFlags.Null) ||| TypeFlags.Never) ||| TypeFlags.NonPrimitive)

    /// <summary><code>Any | Unknown | StructuredOrInstantiable | StringLike | NumberLike | BigIntLike | BooleanLike | ESSymbol | UniqueESSymbol | NonPrimitive</code></summary><returns><c>536575971u</c></returns>
    [<Literal>]
    let Narrowable = (((((((((TypeFlags.Any ||| TypeFlags.Unknown) ||| StructuredOrInstantiable) ||| StringLike) ||| NumberLike) ||| BigIntLike) ||| BooleanLike) ||| TypeFlags.ESSymbol) ||| TypeFlags.UniqueESSymbol) ||| TypeFlags.NonPrimitive)

    /// <summary><code>Any | Unknown | Primitive | Never | Object | Union | Intersection | NonPrimitive | TemplateLiteral | StringMapping</code></summary><returns><c>416808959u</c></returns>
    [<Literal>]
    let IncludesMask = (((((((((TypeFlags.Any ||| TypeFlags.Unknown) ||| Primitive) ||| TypeFlags.Never) ||| TypeFlags.Object) ||| TypeFlags.Union) ||| TypeFlags.Intersection) ||| TypeFlags.NonPrimitive) ||| TypeFlags.TemplateLiteral) ||| TypeFlags.StringMapping)

    /// <summary><code>TypeParameter</code></summary><returns><c>524288u</c></returns>
    [<Literal>]
    let IncludesMissingType = TypeFlags.TypeParameter

    /// <summary><code>Index</code></summary><returns><c>2097152u</c></returns>
    [<Literal>]
    let IncludesNonWideningType = TypeFlags.Index

    /// <summary><code>IndexedAccess</code></summary><returns><c>33554432u</c></returns>
    [<Literal>]
    let IncludesWildcard = TypeFlags.IndexedAccess

    /// <summary><code>Conditional</code></summary><returns><c>67108864u</c></returns>
    [<Literal>]
    let IncludesEmptyObject = TypeFlags.Conditional

    /// <summary><code>Substitution</code></summary><returns><c>16777216u</c></returns>
    [<Literal>]
    let IncludesInstantiable = TypeFlags.Substitution

    /// <summary><code>Reserved1</code></summary><returns><c>536870912u</c></returns>
    [<Literal>]
    let IncludesConstrainedTypeVariable = TypeFlags.Reserved1

    /// <summary><code>Reserved2</code></summary><returns><c>1073741824u</c></returns>
    [<Literal>]
    let IncludesError = TypeFlags.Reserved2

    /// <summary><code>Any | Unknown | Void | Never | Object | Intersection | IncludesInstantiable</code></summary><returns><c>286523411u</c></returns>
    [<Literal>]
    let NotPrimitiveUnion = ((((((TypeFlags.Any ||| TypeFlags.Unknown) ||| TypeFlags.Void) ||| TypeFlags.Never) ||| TypeFlags.Object) ||| TypeFlags.Intersection) ||| IncludesInstantiable)

/// `ObjectFlags`, from `tsc/internal/checker/types.go` upstream.
[<System.Flags>]
type ObjectFlags =
    | None = 0u
    | Class = (1u <<< 0)
    | Interface = (1u <<< 1)
    | Reference = (1u <<< 2)
    | Tuple = (1u <<< 3)
    | Anonymous = (1u <<< 4)
    | Mapped = (1u <<< 5)
    | Instantiated = (1u <<< 6)
    | ObjectLiteral = (1u <<< 7)
    | EvolvingArray = (1u <<< 8)
    | ObjectLiteralPatternWithComputedProperties = (1u <<< 9)
    | ReverseMapped = (1u <<< 10)
    | JsxAttributes = (1u <<< 11)
    | JSLiteral = (1u <<< 12)
    | FreshLiteral = (1u <<< 13)
    | ArrayLiteral = (1u <<< 14)
    | PrimitiveUnion = (1u <<< 15)
    | ContainsWideningType = (1u <<< 16)
    | ContainsObjectOrArrayLiteral = (1u <<< 17)
    | NonInferrableType = (1u <<< 18)
    | CouldContainTypeVariablesComputed = (1u <<< 19)
    | CouldContainTypeVariables = (1u <<< 20)
    | MembersResolved = (1u <<< 21)
    | InstantiationExpressionType = (1u <<< 24)
    | SingleSignatureType = (1u <<< 25)
    | ContainsSpread = (1u <<< 22)
    | ObjectRestType = (1u <<< 23)
    | IsClassInstanceClone = (1u <<< 26)
    | IdenticalBaseTypeCalculated = (1u <<< 27)
    | IdenticalBaseTypeExists = (1u <<< 28)
    | UnresolvedMembers = (1u <<< 29)
    | FromTypeNode = (1u <<< 30)
    | IsGenericTypeComputed = (1u <<< 22)
    | IsGenericObjectType = (1u <<< 23)
    | IsGenericIndexType = (1u <<< 24)
    | ContainsIntersections = (1u <<< 25)
    | IsUnknownLikeUnionComputed = (1u <<< 26)
    | IsUnknownLikeUnion = (1u <<< 27)
    | IsUniformEnumComputed = (1u <<< 28)
    | IsUniformEnum = (1u <<< 29)
    | IsNeverIntersectionComputed = (1u <<< 25)
    | IsNeverIntersection = (1u <<< 26)
    | IsConstrainedTypeVariable = (1u <<< 27)

/// Composite `ObjectFlags` values, computed from the cases above rather than written out.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module ObjectFlags =

    /// <summary><code>Class | Interface</code></summary><returns><c>3u</c></returns>
    [<Literal>]
    let ClassOrInterface = (ObjectFlags.Class ||| ObjectFlags.Interface)

    /// <summary><code>ContainsWideningType | ContainsObjectOrArrayLiteral</code></summary><returns><c>196608u</c></returns>
    [<Literal>]
    let RequiresWidening = (ObjectFlags.ContainsWideningType ||| ObjectFlags.ContainsObjectOrArrayLiteral)

    /// <summary><code>ContainsWideningType | ContainsObjectOrArrayLiteral | NonInferrableType</code></summary><returns><c>458752u</c></returns>
    [<Literal>]
    let PropagatingFlags = ((ObjectFlags.ContainsWideningType ||| ObjectFlags.ContainsObjectOrArrayLiteral) ||| ObjectFlags.NonInferrableType)

    /// <summary><code>Mapped | Instantiated</code></summary><returns><c>96u</c></returns>
    [<Literal>]
    let InstantiatedMapped = (ObjectFlags.Mapped ||| ObjectFlags.Instantiated)

    /// <summary><code>ClassOrInterface | Reference | Tuple | Anonymous | Mapped | ReverseMapped | EvolvingArray | InstantiationExpressionType | SingleSignatureType</code></summary><returns><c>50332991u</c></returns>
    [<Literal>]
    let ObjectTypeKindMask = ((((((((ClassOrInterface ||| ObjectFlags.Reference) ||| ObjectFlags.Tuple) ||| ObjectFlags.Anonymous) ||| ObjectFlags.Mapped) ||| ObjectFlags.ReverseMapped) ||| ObjectFlags.EvolvingArray) ||| ObjectFlags.InstantiationExpressionType) ||| ObjectFlags.SingleSignatureType)

    /// <summary><code>IsGenericObjectType | IsGenericIndexType</code></summary><returns><c>25165824u</c></returns>
    [<Literal>]
    let IsGenericType = (ObjectFlags.IsGenericObjectType ||| ObjectFlags.IsGenericIndexType)

/// `SignatureFlags`, from `tsc/internal/checker/types.go` upstream.
[<System.Flags>]
type SignatureFlags =
    | None = 0u
    | HasRestParameter = (1u <<< 0)
    | HasLiteralTypes = (1u <<< 1)
    | Construct = (1u <<< 2)
    | Abstract = (1u <<< 3)
    | IsInnerCallChain = (1u <<< 4)
    | IsOuterCallChain = (1u <<< 5)
    | IsUntypedSignatureInJSFile = (1u <<< 6)
    | IsNonInferrable = (1u <<< 7)
    | IsSignatureCandidateForOverloadFailure = (1u <<< 8)

/// Composite `SignatureFlags` values, computed from the cases above rather than written out.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module SignatureFlags =

    /// <summary><code>HasRestParameter | HasLiteralTypes | Construct | Abstract | IsUntypedSignatureInJSFile | IsSignatureCandidateForOverloadFailure</code></summary><returns><c>335u</c></returns>
    [<Literal>]
    let PropagatingFlags = (((((SignatureFlags.HasRestParameter ||| SignatureFlags.HasLiteralTypes) ||| SignatureFlags.Construct) ||| SignatureFlags.Abstract) ||| SignatureFlags.IsUntypedSignatureInJSFile) ||| SignatureFlags.IsSignatureCandidateForOverloadFailure)

    /// <summary><code>IsInnerCallChain | IsOuterCallChain</code></summary><returns><c>48u</c></returns>
    [<Literal>]
    let CallChainFlags = (SignatureFlags.IsInnerCallChain ||| SignatureFlags.IsOuterCallChain)

/// `ElementFlags`, from `tsc/internal/checker/types.go` upstream.
[<System.Flags>]
type ElementFlags =
    | None = 0u
    | Required = (1u <<< 0)
    | Optional = (1u <<< 1)
    | Rest = (1u <<< 2)
    | Variadic = (1u <<< 3)

/// Composite `ElementFlags` values, computed from the cases above rather than written out.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module ElementFlags =

    /// <summary><code>Required | Optional</code></summary><returns><c>3u</c></returns>
    [<Literal>]
    let Fixed = (ElementFlags.Required ||| ElementFlags.Optional)

    /// <summary><code>Rest | Variadic</code></summary><returns><c>12u</c></returns>
    [<Literal>]
    let Variable = (ElementFlags.Rest ||| ElementFlags.Variadic)

    /// <summary><code>Optional | Rest | Variadic</code></summary><returns><c>14u</c></returns>
    [<Literal>]
    let NonRequired = ((ElementFlags.Optional ||| ElementFlags.Rest) ||| ElementFlags.Variadic)

    /// <summary><code>Required | Optional | Variadic</code></summary><returns><c>11u</c></returns>
    [<Literal>]
    let NonRest = ((ElementFlags.Required ||| ElementFlags.Optional) ||| ElementFlags.Variadic)

/// `SignatureKind`, from `tsc/internal/checker/types.go` upstream.
type SignatureKind =
    | Call = 0u
    | Construct = 1u

/// `TypePredicateKind`, from `tsc/internal/checker/types.go` upstream.
type TypePredicateKind =
    | This = 0u
    | Identifier = 1u
    | AssertsThis = 2u
    | AssertsIdentifier = 3u

/// `NodeBuilderFlags`, from `tsc/internal/nodebuilder/types.go` upstream.
[<System.Flags>]
type NodeBuilderFlags =
    | None = 0u
    | NoTruncation = (1u <<< 0)
    | WriteArrayAsGenericType = (1u <<< 1)
    | GenerateNamesForShadowedTypeParams = (1u <<< 2)
    | UseStructuralFallback = (1u <<< 3)
    | ForbidIndexedAccessSymbolReferences = (1u <<< 4)
    | WriteTypeArgumentsOfSignature = (1u <<< 5)
    | UseFullyQualifiedType = (1u <<< 6)
    | UseOnlyExternalAliasing = (1u <<< 7)
    | SuppressAnyReturnType = (1u <<< 8)
    | WriteTypeParametersInQualifiedName = (1u <<< 9)
    | MultilineObjectLiterals = (1u <<< 10)
    | WriteClassExpressionAsTypeLiteral = (1u <<< 11)
    | UseTypeOfFunction = (1u <<< 12)
    | OmitParameterModifiers = (1u <<< 13)
    | UseAliasDefinedOutsideCurrentScope = (1u <<< 14)
    | UseSingleQuotesForStringLiteralType = (1u <<< 28)
    | NoTypeReduction = (1u <<< 29)
    | UseInstantiationExpressions = (1u <<< 30)
    | OmitThisParameter = (1u <<< 25)
    | WriteCallStyleSignature = (1u <<< 27)
    | AllowThisInObjectLiteral = (1u <<< 15)
    | AllowQualifiedNameInPlaceOfIdentifier = (1u <<< 16)
    | AllowAnonymousIdentifier = (1u <<< 17)
    | AllowEmptyUnionOrIntersection = (1u <<< 18)
    | AllowEmptyTuple = (1u <<< 19)
    | AllowUniqueESSymbolType = (1u <<< 20)
    | AllowEmptyIndexInfoType = (1u <<< 21)
    | AllowNodeModulesRelativePaths = (1u <<< 26)
    | InObjectTypeLiteral = (1u <<< 22)
    | InTypeAlias = (1u <<< 23)
    | InInitialEntityName = (1u <<< 24)

/// Composite `NodeBuilderFlags` values, computed from the cases above rather than written out.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module NodeBuilderFlags =

    /// <summary><code>AllowThisInObjectLiteral | AllowQualifiedNameInPlaceOfIdentifier | AllowAnonymousIdentifier | AllowEmptyUnionOrIntersection | AllowEmptyTuple | AllowEmptyIndexInfoType | AllowNodeModulesRelativePaths</code></summary><returns><c>70221824u</c></returns>
    [<Literal>]
    let IgnoreErrors = ((((((NodeBuilderFlags.AllowThisInObjectLiteral ||| NodeBuilderFlags.AllowQualifiedNameInPlaceOfIdentifier) ||| NodeBuilderFlags.AllowAnonymousIdentifier) ||| NodeBuilderFlags.AllowEmptyUnionOrIntersection) ||| NodeBuilderFlags.AllowEmptyTuple) ||| NodeBuilderFlags.AllowEmptyIndexInfoType) ||| NodeBuilderFlags.AllowNodeModulesRelativePaths)

/// `InternalSymbolName`, from `tsc/internal/ast/symbol.go` upstream.
[<RequireQualifiedAccess>]
module InternalSymbolName =

    [<Literal>]
    let Call = "__call"

    [<Literal>]
    let Constructor = "__constructor"

    [<Literal>]
    let New = "__new"

    [<Literal>]
    let Index = "__index"

    [<Literal>]
    let ExportStar = "__export"

    [<Literal>]
    let Global = "__global"

    [<Literal>]
    let Missing = "__missing"

    [<Literal>]
    let Type = "__type"

    [<Literal>]
    let Object = "__object"

    [<Literal>]
    let JSXAttributes = "__jsxAttributes"

    [<Literal>]
    let Class = "__class"

    [<Literal>]
    let Function = "__function"

    [<Literal>]
    let Computed = "__computed"

    [<Literal>]
    let AssignmentDeclaration = "__assignment"

    [<Literal>]
    let InstantiationExpression = "__instantiationExpression"

    [<Literal>]
    let ImportAttributes = "__importAttributes"

    [<Literal>]
    let ExportEquals = "export="

    [<Literal>]
    let Default = "default"

    [<Literal>]
    let This = "this"

    [<Literal>]
    let ModuleExports = "module.exports"

/// `NodeFlags`, from `tsc/internal/ast/nodeflags.go` upstream.
[<System.Flags>]
type NodeFlags =
    | None = 0u
    | Let = (1u <<< 0)
    | Const = (1u <<< 1)
    | Using = (1u <<< 2)
    | Reparsed = (1u <<< 3)
    | Synthesized = (1u <<< 4)
    | OptionalChain = (1u <<< 5)
    | ExportContext = (1u <<< 6)
    | ContainsThis = (1u <<< 7)
    | HasImplicitReturn = (1u <<< 8)
    | HasExplicitReturn = (1u <<< 9)
    | DisallowInContext = (1u <<< 10)
    | YieldContext = (1u <<< 11)
    | DecoratorContext = (1u <<< 12)
    | AwaitContext = (1u <<< 13)
    | DisallowConditionalTypesContext = (1u <<< 14)
    | ThisNodeHasError = (1u <<< 15)
    | JavaScriptFile = (1u <<< 16)
    | ThisNodeOrAnySubNodesHasError = (1u <<< 17)
    | HasAsyncFunctions = (1u <<< 18)
    | PossiblyContainsDynamicImport = (1u <<< 19)
    | PossiblyContainsImportMeta = (1u <<< 20)
    | HasJSDoc = (1u <<< 21)
    | JSDoc = (1u <<< 22)
    | Ambient = (1u <<< 23)
    | InWithStatement = (1u <<< 24)
    | JsonFile = (1u <<< 25)
    | PossiblyContainsDeprecatedTag = (1u <<< 26)
    | Unreachable = (1u <<< 27)
    | ReparserTransformedLiteral = (1u <<< 28)

/// Composite `NodeFlags` values, computed from the cases above rather than written out.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module NodeFlags =

    /// <summary><code>Let | Const | Using</code></summary><returns><c>7u</c></returns>
    [<Literal>]
    let BlockScoped = ((NodeFlags.Let ||| NodeFlags.Const) ||| NodeFlags.Using)

    /// <summary><code>Const | Using</code></summary><returns><c>6u</c></returns>
    [<Literal>]
    let Constant = (NodeFlags.Const ||| NodeFlags.Using)

    /// <summary><code>Const | Using</code></summary><returns><c>6u</c></returns>
    [<Literal>]
    let AwaitUsing = (NodeFlags.Const ||| NodeFlags.Using)

    /// <summary><code>HasImplicitReturn | HasExplicitReturn</code></summary><returns><c>768u</c></returns>
    [<Literal>]
    let ReachabilityCheckFlags = (NodeFlags.HasImplicitReturn ||| NodeFlags.HasExplicitReturn)

    /// <summary><code>ReachabilityCheckFlags | HasAsyncFunctions</code></summary><returns><c>262912u</c></returns>
    [<Literal>]
    let ReachabilityAndEmitFlags = (ReachabilityCheckFlags ||| NodeFlags.HasAsyncFunctions)

    /// <summary><code>DisallowInContext | DisallowConditionalTypesContext | YieldContext | DecoratorContext | AwaitContext | JavaScriptFile | InWithStatement | Ambient</code></summary><returns><c>25263104u</c></returns>
    [<Literal>]
    let ContextFlags = (((((((NodeFlags.DisallowInContext ||| NodeFlags.DisallowConditionalTypesContext) ||| NodeFlags.YieldContext) ||| NodeFlags.DecoratorContext) ||| NodeFlags.AwaitContext) ||| NodeFlags.JavaScriptFile) ||| NodeFlags.InWithStatement) ||| NodeFlags.Ambient)

    /// <summary><code>YieldContext | AwaitContext</code></summary><returns><c>10240u</c></returns>
    [<Literal>]
    let TypeExcludesFlags = (NodeFlags.YieldContext ||| NodeFlags.AwaitContext)

    /// <summary><code>PossiblyContainsDynamicImport | PossiblyContainsImportMeta</code></summary><returns><c>1572864u</c></returns>
    [<Literal>]
    let PermanentlySetIncrementalFlags = (NodeFlags.PossiblyContainsDynamicImport ||| NodeFlags.PossiblyContainsImportMeta)

    /// <summary><code>ContainsThis</code></summary><returns><c>128u</c></returns>
    [<Literal>]
    let IdentifierHasExtendedUnicodeEscape = NodeFlags.ContainsThis

    /// <summary><code>HasAsyncFunctions</code></summary><returns><c>262144u</c></returns>
    [<Literal>]
    let IdentifierIsInJSDocNamespace = NodeFlags.HasAsyncFunctions

    /// <summary><code>OptionalChain</code></summary><returns><c>32u</c></returns>
    [<Literal>]
    let NestedNamespace = NodeFlags.OptionalChain

/// `TokenFlags`, from `tsc/internal/ast/tokenflags.go` upstream.
[<System.Flags>]
type TokenFlags =
    | None = 0u
    | PrecedingLineBreak = (1u <<< 0)
    | PrecedingJSDocComment = (1u <<< 1)
    | Unterminated = (1u <<< 2)
    | ExtendedUnicodeEscape = (1u <<< 3)
    | Scientific = (1u <<< 4)
    | Octal = (1u <<< 5)
    | HexSpecifier = (1u <<< 6)
    | BinarySpecifier = (1u <<< 7)
    | OctalSpecifier = (1u <<< 8)
    | ContainsSeparator = (1u <<< 9)
    | UnicodeEscape = (1u <<< 10)
    | ContainsInvalidEscape = (1u <<< 11)
    | HexEscape = (1u <<< 12)
    | ContainsLeadingZero = (1u <<< 13)
    | ContainsInvalidSeparator = (1u <<< 14)
    | PrecedingJSDocLeadingAsterisks = (1u <<< 15)
    | SingleQuote = (1u <<< 16)
    | PrecedingJSDocWithDeprecated = (1u <<< 17)
    | PrecedingJSDocWithSeeOrLink = (1u <<< 18)

/// Composite `TokenFlags` values, computed from the cases above rather than written out.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module TokenFlags =

    /// <summary><code>BinarySpecifier | OctalSpecifier</code></summary><returns><c>384u</c></returns>
    [<Literal>]
    let BinaryOrOctalSpecifier = (TokenFlags.BinarySpecifier ||| TokenFlags.OctalSpecifier)

    /// <summary><code>HexSpecifier | BinaryOrOctalSpecifier</code></summary><returns><c>448u</c></returns>
    [<Literal>]
    let WithSpecifier = (TokenFlags.HexSpecifier ||| BinaryOrOctalSpecifier)

    /// <summary><code>Unterminated | HexEscape | UnicodeEscape | ExtendedUnicodeEscape | ContainsInvalidEscape | SingleQuote</code></summary><returns><c>72716u</c></returns>
    [<Literal>]
    let StringLiteralFlags = (((((TokenFlags.Unterminated ||| TokenFlags.HexEscape) ||| TokenFlags.UnicodeEscape) ||| TokenFlags.ExtendedUnicodeEscape) ||| TokenFlags.ContainsInvalidEscape) ||| TokenFlags.SingleQuote)

    /// <summary><code>Scientific | Octal | ContainsLeadingZero | WithSpecifier | ContainsSeparator | ContainsInvalidSeparator</code></summary><returns><c>25584u</c></returns>
    [<Literal>]
    let NumericLiteralFlags = (((((TokenFlags.Scientific ||| TokenFlags.Octal) ||| TokenFlags.ContainsLeadingZero) ||| WithSpecifier) ||| TokenFlags.ContainsSeparator) ||| TokenFlags.ContainsInvalidSeparator)

    /// <summary><code>Unterminated | HexEscape | UnicodeEscape | ExtendedUnicodeEscape | ContainsInvalidEscape</code></summary><returns><c>7180u</c></returns>
    [<Literal>]
    let TemplateLiteralLikeFlags = ((((TokenFlags.Unterminated ||| TokenFlags.HexEscape) ||| TokenFlags.UnicodeEscape) ||| TokenFlags.ExtendedUnicodeEscape) ||| TokenFlags.ContainsInvalidEscape)

    /// <summary><code>Unterminated</code></summary><returns><c>4u</c></returns>
    [<Literal>]
    let RegularExpressionLiteralFlags = TokenFlags.Unterminated

    /// <summary><code>Octal | ContainsLeadingZero | ContainsInvalidSeparator | ContainsInvalidEscape</code></summary><returns><c>26656u</c></returns>
    [<Literal>]
    let IsInvalid = (((TokenFlags.Octal ||| TokenFlags.ContainsLeadingZero) ||| TokenFlags.ContainsInvalidSeparator) ||| TokenFlags.ContainsInvalidEscape)

/// `ModifierFlags`, from `tsc/internal/ast/modifierflags.go` upstream.
[<System.Flags>]
type ModifierFlags =
    | None = 0u
    | Public = (1u <<< 0)
    | Private = (1u <<< 1)
    | Protected = (1u <<< 2)
    | Readonly = (1u <<< 3)
    | Override = (1u <<< 4)
    | Export = (1u <<< 5)
    | Abstract = (1u <<< 6)
    | Ambient = (1u <<< 7)
    | Static = (1u <<< 8)
    | Accessor = (1u <<< 9)
    | Async = (1u <<< 10)
    | Default = (1u <<< 11)
    | Const = (1u <<< 12)
    | In = (1u <<< 13)
    | Out = (1u <<< 14)
    | Decorator = (1u <<< 15)
    | Deprecated = (1u <<< 16)
    | JSDocPublic = (1u <<< 23)
    | JSDocPrivate = (1u <<< 24)
    | JSDocProtected = (1u <<< 25)
    | JSDocReadonly = (1u <<< 26)
    | JSDocOverride = (1u <<< 27)
    | HasComputedJSDocModifiers = (1u <<< 28)
    | HasComputedFlags = (1u <<< 29)

/// Composite `ModifierFlags` values, computed from the cases above rather than written out.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module ModifierFlags =

    /// <summary><code>Public | Private | Protected | Readonly | Override</code></summary><returns><c>31u</c></returns>
    [<Literal>]
    let SyntacticOrJSDocModifiers = ((((ModifierFlags.Public ||| ModifierFlags.Private) ||| ModifierFlags.Protected) ||| ModifierFlags.Readonly) ||| ModifierFlags.Override)

    /// <summary><code>Export | Ambient | Abstract | Static | Accessor | Async | Default | Const | In | Out | Decorator</code></summary><returns><c>65504u</c></returns>
    [<Literal>]
    let SyntacticOnlyModifiers = ((((((((((ModifierFlags.Export ||| ModifierFlags.Ambient) ||| ModifierFlags.Abstract) ||| ModifierFlags.Static) ||| ModifierFlags.Accessor) ||| ModifierFlags.Async) ||| ModifierFlags.Default) ||| ModifierFlags.Const) ||| ModifierFlags.In) ||| ModifierFlags.Out) ||| ModifierFlags.Decorator)

    /// <summary><code>SyntacticOrJSDocModifiers | SyntacticOnlyModifiers</code></summary><returns><c>65535u</c></returns>
    [<Literal>]
    let SyntacticModifiers = (SyntacticOrJSDocModifiers ||| SyntacticOnlyModifiers)

    /// <summary><code>JSDocPublic | JSDocPrivate | JSDocProtected | JSDocReadonly | JSDocOverride</code></summary><returns><c>260046848u</c></returns>
    [<Literal>]
    let JSDocCacheOnlyModifiers = ((((ModifierFlags.JSDocPublic ||| ModifierFlags.JSDocPrivate) ||| ModifierFlags.JSDocProtected) ||| ModifierFlags.JSDocReadonly) ||| ModifierFlags.JSDocOverride)

    /// <summary><code>Deprecated</code></summary><returns><c>65536u</c></returns>
    [<Literal>]
    let JSDocOnlyModifiers = ModifierFlags.Deprecated

    /// <summary><code>SyntacticOrJSDocModifiers | SyntacticOnlyModifiers | JSDocOnlyModifiers</code></summary><returns><c>131071u</c></returns>
    [<Literal>]
    let NonCacheOnlyModifiers = ((SyntacticOrJSDocModifiers ||| SyntacticOnlyModifiers) ||| JSDocOnlyModifiers)

    /// <summary><code>Public | Private | Protected</code></summary><returns><c>7u</c></returns>
    [<Literal>]
    let AccessibilityModifier = ((ModifierFlags.Public ||| ModifierFlags.Private) ||| ModifierFlags.Protected)

    /// <summary><code>AccessibilityModifier | Readonly | Override</code></summary><returns><c>31u</c></returns>
    [<Literal>]
    let ParameterPropertyModifier = ((AccessibilityModifier ||| ModifierFlags.Readonly) ||| ModifierFlags.Override)

    /// <summary><code>Private | Protected</code></summary><returns><c>6u</c></returns>
    [<Literal>]
    let NonPublicAccessibilityModifier = (ModifierFlags.Private ||| ModifierFlags.Protected)

    /// <summary><code>Ambient | Public | Private | Protected | Readonly | Abstract | Const | Override | In | Out</code></summary><returns><c>28895u</c></returns>
    [<Literal>]
    let TypeScriptModifier = (((((((((ModifierFlags.Ambient ||| ModifierFlags.Public) ||| ModifierFlags.Private) ||| ModifierFlags.Protected) ||| ModifierFlags.Readonly) ||| ModifierFlags.Abstract) ||| ModifierFlags.Const) ||| ModifierFlags.Override) ||| ModifierFlags.In) ||| ModifierFlags.Out)

    /// <summary><code>Export | Default</code></summary><returns><c>2080u</c></returns>
    [<Literal>]
    let ExportDefault = (ModifierFlags.Export ||| ModifierFlags.Default)

    /// <summary><code>Export | Ambient | Public | Private | Protected | Static | Readonly | Abstract | Accessor | Async | Default | Const | Deprecated | Override | In | Out | Decorator</code></summary><returns><c>131071u</c></returns>
    [<Literal>]
    let All = ((((((((((((((((ModifierFlags.Export ||| ModifierFlags.Ambient) ||| ModifierFlags.Public) ||| ModifierFlags.Private) ||| ModifierFlags.Protected) ||| ModifierFlags.Static) ||| ModifierFlags.Readonly) ||| ModifierFlags.Abstract) ||| ModifierFlags.Accessor) ||| ModifierFlags.Async) ||| ModifierFlags.Default) ||| ModifierFlags.Const) ||| ModifierFlags.Deprecated) ||| ModifierFlags.Override) ||| ModifierFlags.In) ||| ModifierFlags.Out) ||| ModifierFlags.Decorator)

    /// <summary><code>All &amp; ~Decorator</code></summary><returns><c>98303u</c></returns>
    [<Literal>]
    let Modifier = (All &&& (~~~ModifierFlags.Decorator))

    /// <summary><code>Export | Static | Accessor | Async | Default</code></summary><returns><c>3872u</c></returns>
    [<Literal>]
    let JavaScript = ((((ModifierFlags.Export ||| ModifierFlags.Static) ||| ModifierFlags.Accessor) ||| ModifierFlags.Async) ||| ModifierFlags.Default)

/// `ScriptKind`, from `tsc/internal/core/scriptkind.go` upstream.
type ScriptKind =
    | Unknown = 0u
    | JS = 1u
    | JSX = 2u
    | TS = 3u
    | TSX = 4u
    | JSON = 6u

/// `LanguageVariant`, from `unrecorded` upstream.
type LanguageVariant =
    | Standard = 0u
    | JSX = 1u

/// `SpanMapKind`, from `tsc/internal/spanmap/spanmap.go` upstream.
type SpanMapKind =
    | Verbatim = 0u
    | Atom = 1u
    | Alias = 2u

/// `SpanMapFeature`, from `tsc/internal/spanmap/spanmap.go` upstream.
[<System.Flags>]
type SpanMapFeature =
    | Hover = (1u <<< 0)
    | SignatureHelp = (1u <<< 1)
    | Completion = (1u <<< 2)
    | Definition = (1u <<< 3)
    | TypeDefinition = (1u <<< 4)
    | Implementation = (1u <<< 5)
    | References = (1u <<< 6)
    | DocumentHighlights = (1u <<< 7)
    | Rename = (1u <<< 8)
    | CallHierarchy = (1u <<< 9)
    | CodeActions = (1u <<< 10)
    | Formatting = (1u <<< 11)
    | InlayHints = (1u <<< 12)
    | SemanticTokens = (1u <<< 13)
    | FoldingRanges = (1u <<< 14)
    | SelectionRanges = (1u <<< 15)
    | LinkedEditing = (1u <<< 16)
    | AutoInsert = (1u <<< 17)
    | DocumentSymbols = (1u <<< 18)
    | CodeLens = (1u <<< 19)
    | None = 0u
    /// <summary><code>(CodeLens &lt;&lt; 1) - 1</code></summary>
    | All = 1048575u

/// `SpanMapFidelity`, from `tsc/internal/spanmap/spanmap.go` upstream.
type SpanMapFidelity =
    | Exact = 0u
    | Atom = 1u
    | Approximate = 2u
    | None = 3u

/// `DiagnosticDirectivePolicy`, from `tsc/internal/ast/ast.go` upstream.
type DiagnosticDirectivePolicy =
    | Ignore = 0u
    | Expect = 1u

/// `CommentDirectiveType`, from `unrecorded` upstream.
type CommentDirectiveType =
    | ExpectError = 0u
    | Ignore = 1u

