namespace Xantham.TypeScript.Wire

// <auto-generated>
//   Generated by tools/proto-gen/generate.mjs from the wire schema shipped in
//   typescript@7.1.0-dev.20260830.1 at dist/api/proto.generated.d.ts.
//   Do not edit by hand - re-run the generator when the compiler is upgraded.
// </auto-generated>

open System.Text.Json.Nodes
open Xantham.TypeScript.Wire.Proto

/// One function per server method, each taking the channel and the method's parameter record.
///
/// Naming follows the wire: `getSymbolAtPosition` is `Api.getSymbolAtPosition`. Results the
/// schema permits to be null are `voption`; the rest raise if the server sends nothing, since
/// a missing field on a request is otherwise indistinguishable from a legitimate empty answer.
[<RequireQualifiedAccess>]
module Api =

    let release (channel: TscChannel) (parameters: ReleaseParams) =
        ProtoJson.requestUnit channel Method.Release parameters

    let batchRequests (channel: TscChannel) (parameters: BatchRequestsParams) : BatchRequestsResponse =
        ProtoJson.request<BatchRequestsParams, BatchRequestsResponse> channel Method.BatchRequests parameters

    let initialize (channel: TscChannel) : InitializeResponse =
        match ProtoJson.requestNoParams<InitializeResponse> channel Method.Initialize with
        | ValueSome result -> result
        | ValueNone -> failwith "initialize returned no result, but the schema declares one"

    let updateSnapshot (channel: TscChannel) (parameters: UpdateSnapshotParams) : UpdateSnapshotResponse =
        ProtoJson.request<UpdateSnapshotParams, UpdateSnapshotResponse> channel Method.UpdateSnapshot parameters

    let updateTemporarySnapshot (channel: TscChannel) (parameters: UpdateTemporarySnapshotParams) : UpdateSnapshotResponse =
        ProtoJson.request<UpdateTemporarySnapshotParams, UpdateSnapshotResponse> channel Method.UpdateTemporarySnapshot parameters

    let createProgram (channel: TscChannel) (parameters: CreateProgramParams) : CreateProgramResponse =
        ProtoJson.request<CreateProgramParams, CreateProgramResponse> channel Method.CreateProgram parameters

    let parseCommandLine (channel: TscChannel) (parameters: ParseCommandLineParams) : ConfigFileResponse =
        ProtoJson.request<ParseCommandLineParams, ConfigFileResponse> channel Method.ParseCommandLine parameters

    let readConfigFile (channel: TscChannel) (parameters: ReadConfigFileParams) : ReadConfigFileResponse =
        ProtoJson.request<ReadConfigFileParams, ReadConfigFileResponse> channel Method.ReadConfigFile parameters

    let parseJsonConfigFileContent (channel: TscChannel) (parameters: ParseJsonConfigFileContentParams) : ConfigFileResponse =
        ProtoJson.request<ParseJsonConfigFileContentParams, ConfigFileResponse> channel Method.ParseJsonConfigFileContent parameters

    let parseConfigFile (channel: TscChannel) (parameters: ParseConfigFileParams) : ConfigFileResponse =
        ProtoJson.request<ParseConfigFileParams, ConfigFileResponse> channel Method.ParseConfigFile parameters

    let transpileModule (channel: TscChannel) (parameters: TranspileParams) : TranspileOutputResponse =
        ProtoJson.request<TranspileParams, TranspileOutputResponse> channel Method.TranspileModule parameters

    let transpileModuleFromFile (channel: TscChannel) (parameters: TranspileFromFileParams) : TranspileOutputResponse =
        ProtoJson.request<TranspileFromFileParams, TranspileOutputResponse> channel Method.TranspileModuleFromFile parameters

    let transpileDeclaration (channel: TscChannel) (parameters: TranspileParams) : TranspileOutputResponse =
        ProtoJson.request<TranspileParams, TranspileOutputResponse> channel Method.TranspileDeclaration parameters

    let transpileDeclarationFromFile (channel: TscChannel) (parameters: TranspileFromFileParams) : TranspileOutputResponse =
        ProtoJson.request<TranspileFromFileParams, TranspileOutputResponse> channel Method.TranspileDeclarationFromFile parameters

    let getDefaultProjectForFile (channel: TscChannel) (parameters: GetDefaultProjectForFileParams) : ProjectResponse voption =
        ProtoJson.requestOption<GetDefaultProjectForFileParams, ProjectResponse> channel Method.GetDefaultProjectForFile parameters

    let getSymbolAtPosition (channel: TscChannel) (parameters: GetSymbolAtPositionParams) : SymbolResponse voption =
        ProtoJson.requestOption<GetSymbolAtPositionParams, SymbolResponse> channel Method.GetSymbolAtPosition parameters

    let getSymbolsAtPositions (channel: TscChannel) (parameters: GetSymbolsAtPositionsParams) : SymbolResponse[] =
        ProtoJson.request<GetSymbolsAtPositionsParams, SymbolResponse[]> channel Method.GetSymbolsAtPositions parameters

    let getSymbolAtLocation (channel: TscChannel) (parameters: GetSymbolAtLocationParams) : SymbolResponse voption =
        ProtoJson.requestOption<GetSymbolAtLocationParams, SymbolResponse> channel Method.GetSymbolAtLocation parameters

    let getSymbolsAtLocations (channel: TscChannel) (parameters: GetSymbolsAtLocationsParams) : SymbolResponse[] =
        ProtoJson.request<GetSymbolsAtLocationsParams, SymbolResponse[]> channel Method.GetSymbolsAtLocations parameters

    let getSymbolOfSourceFile (channel: TscChannel) (parameters: GetSymbolOfSourceFileParams) : SymbolResponse voption =
        ProtoJson.requestOption<GetSymbolOfSourceFileParams, SymbolResponse> channel Method.GetSymbolOfSourceFile parameters

    let getSymbolsOfSourceFiles (channel: TscChannel) (parameters: GetSymbolsOfSourceFilesParams) : SymbolResponse[] =
        ProtoJson.request<GetSymbolsOfSourceFilesParams, SymbolResponse[]> channel Method.GetSymbolsOfSourceFiles parameters

    let getTypeOfSymbol (channel: TscChannel) (parameters: GetTypeOfSymbolParams) : TypeResponse =
        ProtoJson.request<GetTypeOfSymbolParams, TypeResponse> channel Method.GetTypeOfSymbol parameters

    let getTypesOfSymbols (channel: TscChannel) (parameters: GetTypesOfSymbolsParams) : TypeResponse[] =
        ProtoJson.request<GetTypesOfSymbolsParams, TypeResponse[]> channel Method.GetTypesOfSymbols parameters

    let getDeclaredTypeOfSymbol (channel: TscChannel) (parameters: GetTypeOfSymbolParams) : TypeResponse =
        ProtoJson.request<GetTypeOfSymbolParams, TypeResponse> channel Method.GetDeclaredTypeOfSymbol parameters

    let getNonMissingTypeOfSymbol (channel: TscChannel) (parameters: GetTypeOfSymbolParams) : TypeResponse =
        ProtoJson.request<GetTypeOfSymbolParams, TypeResponse> channel Method.GetNonMissingTypeOfSymbol parameters

    /// Returns the raw binary AST, not the schema's `SourceFileResponse` JSON envelope -
    /// see `ProtoJson.requestAst`.
    let getSourceFile (channel: TscChannel) (parameters: GetSourceFileParams) =
        ProtoJson.requestAst channel Method.GetSourceFile parameters

    let getSourceFileNames (channel: TscChannel) (parameters: GetSourceFileNamesParams) : string[] =
        ProtoJson.request<GetSourceFileNamesParams, string[]> channel Method.GetSourceFileNames parameters

    let getSourceFileMetadata (channel: TscChannel) (parameters: GetSourceFileParams) : SourceFileMetadata voption =
        ProtoJson.requestOption<GetSourceFileParams, SourceFileMetadata> channel Method.GetSourceFileMetadata parameters

    let getConfigFileNames (channel: TscChannel) (parameters: GetProjectDiagnosticsParams) : string[] voption =
        ProtoJson.requestOption<GetProjectDiagnosticsParams, string[]> channel Method.GetConfigFileNames parameters

    /// Returns the raw binary AST, not the schema's `SourceFileResponse` JSON envelope -
    /// see `ProtoJson.requestAst`.
    let getConfigSourceFile (channel: TscChannel) (parameters: GetSourceFileParams) =
        ProtoJson.requestAst channel Method.GetConfigSourceFile parameters

    let resolveName (channel: TscChannel) (parameters: ResolveNameParams) : SymbolResponse voption =
        ProtoJson.requestOption<ResolveNameParams, SymbolResponse> channel Method.ResolveName parameters

    let getSymbolsInScope (channel: TscChannel) (parameters: GetSymbolsInScopeParams) : SymbolResponse[] =
        ProtoJson.request<GetSymbolsInScopeParams, SymbolResponse[]> channel Method.GetSymbolsInScope parameters

    let getSignaturesOfType (channel: TscChannel) (parameters: GetSignaturesOfTypeParams) : SignatureResponse[] =
        ProtoJson.request<GetSignaturesOfTypeParams, SignatureResponse[]> channel Method.GetSignaturesOfType parameters

    let getResolvedSignature (channel: TscChannel) (parameters: GetResolvedSignatureParams) : SignatureResponse =
        ProtoJson.request<GetResolvedSignatureParams, SignatureResponse> channel Method.GetResolvedSignature parameters

    let getTypeAtLocation (channel: TscChannel) (parameters: GetTypeAtLocationParams) : TypeResponse =
        ProtoJson.request<GetTypeAtLocationParams, TypeResponse> channel Method.GetTypeAtLocation parameters

    let getTypeAtLocations (channel: TscChannel) (parameters: GetTypeAtLocationsParams) : TypeResponse[] =
        ProtoJson.request<GetTypeAtLocationsParams, TypeResponse[]> channel Method.GetTypeAtLocations parameters

    let getTypeAtPosition (channel: TscChannel) (parameters: GetTypeAtPositionParams) : TypeResponse voption =
        ProtoJson.requestOption<GetTypeAtPositionParams, TypeResponse> channel Method.GetTypeAtPosition parameters

    let getTypesAtPositions (channel: TscChannel) (parameters: GetTypesAtPositionsParams) : TypeResponse[] =
        ProtoJson.request<GetTypesAtPositionsParams, TypeResponse[]> channel Method.GetTypesAtPositions parameters

    let getParentOfSymbol (channel: TscChannel) (parameters: GetSymbolPropertyParams) : SymbolResponse voption =
        ProtoJson.requestOption<GetSymbolPropertyParams, SymbolResponse> channel Method.GetParentOfSymbol parameters

    let getMembersOfSymbol (channel: TscChannel) (parameters: GetSymbolPropertyParams) : SymbolResponse[] voption =
        ProtoJson.requestOption<GetSymbolPropertyParams, SymbolResponse[]> channel Method.GetMembersOfSymbol parameters

    let getExportsOfSymbol (channel: TscChannel) (parameters: GetSymbolPropertyParams) : SymbolResponse[] voption =
        ProtoJson.requestOption<GetSymbolPropertyParams, SymbolResponse[]> channel Method.GetExportsOfSymbol parameters

    let getExportSymbolOfSymbol (channel: TscChannel) (parameters: GetSymbolPropertyParams) : SymbolResponse voption =
        ProtoJson.requestOption<GetSymbolPropertyParams, SymbolResponse> channel Method.GetExportSymbolOfSymbol parameters

    let getSymbolOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : SymbolResponse voption =
        ProtoJson.requestOption<GetTypePropertyParams, SymbolResponse> channel Method.GetSymbolOfType parameters

    let getTargetOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse =
        ProtoJson.request<GetTypePropertyParams, TypeResponse> channel Method.GetTargetOfType parameters

    let getFreshTypeOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse voption =
        ProtoJson.requestOption<GetTypePropertyParams, TypeResponse> channel Method.GetFreshTypeOfType parameters

    let getRegularTypeOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse voption =
        ProtoJson.requestOption<GetTypePropertyParams, TypeResponse> channel Method.GetRegularTypeOfType parameters

    let getTypesOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse[] voption =
        ProtoJson.requestOption<GetTypePropertyParams, TypeResponse[]> channel Method.GetTypesOfType parameters

    let getTypeParametersOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse[] voption =
        ProtoJson.requestOption<GetTypePropertyParams, TypeResponse[]> channel Method.GetTypeParametersOfType parameters

    let getOuterTypeParametersOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse[] voption =
        ProtoJson.requestOption<GetTypePropertyParams, TypeResponse[]> channel Method.GetOuterTypeParametersOfType parameters

    let getLocalTypeParametersOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse[] voption =
        ProtoJson.requestOption<GetTypePropertyParams, TypeResponse[]> channel Method.GetLocalTypeParametersOfType parameters

    let getAliasTypeArgumentsOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse[] voption =
        ProtoJson.requestOption<GetTypePropertyParams, TypeResponse[]> channel Method.GetAliasTypeArgumentsOfType parameters

    let getAliasSymbolOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : SymbolResponse voption =
        ProtoJson.requestOption<GetTypePropertyParams, SymbolResponse> channel Method.GetAliasSymbolOfType parameters

    let getObjectTypeOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse =
        ProtoJson.request<GetTypePropertyParams, TypeResponse> channel Method.GetObjectTypeOfType parameters

    let getIndexTypeOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse =
        ProtoJson.request<GetTypePropertyParams, TypeResponse> channel Method.GetIndexTypeOfType parameters

    let getCheckTypeOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse =
        ProtoJson.request<GetTypePropertyParams, TypeResponse> channel Method.GetCheckTypeOfType parameters

    let getExtendsTypeOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse =
        ProtoJson.request<GetTypePropertyParams, TypeResponse> channel Method.GetExtendsTypeOfType parameters

    let getBaseTypeOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse =
        ProtoJson.request<GetTypePropertyParams, TypeResponse> channel Method.GetBaseTypeOfType parameters

    let getConstraintOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse =
        ProtoJson.request<GetTypePropertyParams, TypeResponse> channel Method.GetConstraintOfType parameters

    let getTypeParametersOfSignature (channel: TscChannel) (parameters: GetSignaturePropertyParams) : TypeResponse[] voption =
        ProtoJson.requestOption<GetSignaturePropertyParams, TypeResponse[]> channel Method.GetTypeParametersOfSignature parameters

    let getParametersOfSignature (channel: TscChannel) (parameters: GetSignaturePropertyParams) : SymbolResponse[] voption =
        ProtoJson.requestOption<GetSignaturePropertyParams, SymbolResponse[]> channel Method.GetParametersOfSignature parameters

    let getThisParameterOfSignature (channel: TscChannel) (parameters: GetSignaturePropertyParams) : SymbolResponse voption =
        ProtoJson.requestOption<GetSignaturePropertyParams, SymbolResponse> channel Method.GetThisParameterOfSignature parameters

    let getTargetOfSignature (channel: TscChannel) (parameters: GetSignaturePropertyParams) : SignatureResponse voption =
        ProtoJson.requestOption<GetSignaturePropertyParams, SignatureResponse> channel Method.GetTargetOfSignature parameters

    let getContextualType (channel: TscChannel) (parameters: GetContextualTypeParams) : TypeResponse voption =
        ProtoJson.requestOption<GetContextualTypeParams, TypeResponse> channel Method.GetContextualType parameters

    let getBaseTypeOfLiteralType (channel: TscChannel) (parameters: GetBaseTypeOfLiteralTypeParams) : TypeResponse =
        ProtoJson.request<GetBaseTypeOfLiteralTypeParams, TypeResponse> channel Method.GetBaseTypeOfLiteralType parameters

    let getNonNullableType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse =
        ProtoJson.request<GetTypePropertyParams, TypeResponse> channel Method.GetNonNullableType parameters

    let getTypeFromTypeNode (channel: TscChannel) (parameters: GetTypeFromTypeNodeParams) : TypeResponse =
        ProtoJson.request<GetTypeFromTypeNodeParams, TypeResponse> channel Method.GetTypeFromTypeNode parameters

    let getWidenedType (channel: TscChannel) (parameters: GetWidenedTypeParams) : TypeResponse =
        ProtoJson.request<GetWidenedTypeParams, TypeResponse> channel Method.GetWidenedType parameters

    let getParameterType (channel: TscChannel) (parameters: GetParameterTypeParams) : TypeResponse =
        ProtoJson.request<GetParameterTypeParams, TypeResponse> channel Method.GetParameterType parameters

    let getTypeParameterAtPosition (channel: TscChannel) (parameters: GetParameterTypeParams) : TypeResponse =
        ProtoJson.request<GetParameterTypeParams, TypeResponse> channel Method.GetTypeParameterAtPosition parameters

    let isArrayLikeType (channel: TscChannel) (parameters: IsArrayLikeTypeParams) : bool =
        ProtoJson.request<IsArrayLikeTypeParams, bool> channel Method.IsArrayLikeType parameters

    let isTypeAssignableTo (channel: TscChannel) (parameters: IsTypeAssignableToParams) : bool =
        ProtoJson.request<IsTypeAssignableToParams, bool> channel Method.IsTypeAssignableTo parameters

    let getShorthandAssignmentValueSymbol (channel: TscChannel) (parameters: GetTypeAtLocationParams) : SymbolResponse voption =
        ProtoJson.requestOption<GetTypeAtLocationParams, SymbolResponse> channel Method.GetShorthandAssignmentValueSymbol parameters

    let getTypeOfSymbolAtLocation (channel: TscChannel) (parameters: GetTypeOfSymbolAtLocationParams) : TypeResponse =
        ProtoJson.request<GetTypeOfSymbolAtLocationParams, TypeResponse> channel Method.GetTypeOfSymbolAtLocation parameters

    /// Returns the raw binary AST, not the schema's `SourceFileResponse` JSON envelope -
    /// see `ProtoJson.requestAst`.
    let typeToTypeNode (channel: TscChannel) (parameters: TypeToTypeNodeParams) =
        ProtoJson.requestAst channel Method.TypeToTypeNode parameters

    /// Returns the raw binary AST, not the schema's `SourceFileResponse` JSON envelope -
    /// see `ProtoJson.requestAst`.
    let signatureToSignatureDeclaration (channel: TscChannel) (parameters: SignatureToSignatureDeclarationParams) =
        ProtoJson.requestAst channel Method.SignatureToSignatureDeclaration parameters

    let typeToString (channel: TscChannel) (parameters: TypeToTypeNodeParams) : JsonNode voption =
        ProtoJson.requestOption<TypeToTypeNodeParams, JsonNode> channel Method.TypeToString parameters

    let isContextSensitive (channel: TscChannel) (parameters: GetContextualTypeParams) : bool =
        ProtoJson.request<GetContextualTypeParams, bool> channel Method.IsContextSensitive parameters

    let getReturnTypeOfSignature (channel: TscChannel) (parameters: GetSignaturePropertyParams) : TypeResponse =
        ProtoJson.request<GetSignaturePropertyParams, TypeResponse> channel Method.GetReturnTypeOfSignature parameters

    let getRestTypeOfSignature (channel: TscChannel) (parameters: CheckerSignatureParams) : TypeResponse =
        ProtoJson.request<CheckerSignatureParams, TypeResponse> channel Method.GetRestTypeOfSignature parameters

    let getTypePredicateOfSignature (channel: TscChannel) (parameters: CheckerSignatureParams) : TypePredicateResponse voption =
        ProtoJson.requestOption<CheckerSignatureParams, TypePredicateResponse> channel Method.GetTypePredicateOfSignature parameters

    let getBaseTypes (channel: TscChannel) (parameters: CheckerTypeParams) : TypeResponse[] voption =
        ProtoJson.requestOption<CheckerTypeParams, TypeResponse[]> channel Method.GetBaseTypes parameters

    let getPropertiesOfType (channel: TscChannel) (parameters: CheckerTypeParams) : SymbolResponse[] voption =
        ProtoJson.requestOption<CheckerTypeParams, SymbolResponse[]> channel Method.GetPropertiesOfType parameters

    let getApparentPropertiesOfType (channel: TscChannel) (parameters: GetTypePropertyParams) : SymbolResponse[] =
        ProtoJson.request<GetTypePropertyParams, SymbolResponse[]> channel Method.GetApparentPropertiesOfType parameters

    let getApparentType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse =
        ProtoJson.request<GetTypePropertyParams, TypeResponse> channel Method.GetApparentType parameters

    let getReducedType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse =
        ProtoJson.request<GetTypePropertyParams, TypeResponse> channel Method.GetReducedType parameters

    let getPropertyOfType (channel: TscChannel) (parameters: GetPropertyOfTypeParams) : SymbolResponse voption =
        ProtoJson.requestOption<GetPropertyOfTypeParams, SymbolResponse> channel Method.GetPropertyOfType parameters

    let getIndexInfosOfType (channel: TscChannel) (parameters: CheckerTypeParams) : IndexInfoResponse[] voption =
        ProtoJson.requestOption<CheckerTypeParams, IndexInfoResponse[]> channel Method.GetIndexInfosOfType parameters

    let getConstraintOfTypeParameter (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse voption =
        ProtoJson.requestOption<GetTypePropertyParams, TypeResponse> channel Method.GetConstraintOfTypeParameter parameters

    let getDefaultFromTypeParameter (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse voption =
        ProtoJson.requestOption<GetTypePropertyParams, TypeResponse> channel Method.GetDefaultFromTypeParameter parameters

    let getBaseConstraintOfType (channel: TscChannel) (parameters: CheckerTypeParams) : TypeResponse voption =
        ProtoJson.requestOption<CheckerTypeParams, TypeResponse> channel Method.GetBaseConstraintOfType parameters

    let getTypeArguments (channel: TscChannel) (parameters: CheckerTypeParams) : TypeResponse[] voption =
        ProtoJson.requestOption<CheckerTypeParams, TypeResponse[]> channel Method.GetTypeArguments parameters

    let getImportAdderEdits (channel: TscChannel) (parameters: GetImportAdderEditsParams) : TextEdit[] =
        ProtoJson.request<GetImportAdderEditsParams, TextEdit[]> channel Method.GetImportAdderEdits parameters

    let getTrueTypeOfConditionalType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse =
        ProtoJson.request<GetTypePropertyParams, TypeResponse> channel Method.GetTrueTypeOfConditionalType parameters

    let getFalseTypeOfConditionalType (channel: TscChannel) (parameters: GetTypePropertyParams) : TypeResponse =
        ProtoJson.request<GetTypePropertyParams, TypeResponse> channel Method.GetFalseTypeOfConditionalType parameters

    let getConstantValue (channel: TscChannel) (parameters: CheckerNodeParams) : JsonNode voption =
        ProtoJson.requestOption<CheckerNodeParams, JsonNode> channel Method.GetConstantValue parameters

    let getSignatureFromDeclaration (channel: TscChannel) (parameters: CheckerNodeParams) : SignatureResponse =
        ProtoJson.request<CheckerNodeParams, SignatureResponse> channel Method.GetSignatureFromDeclaration parameters

    let getExportSpecifierLocalTargetSymbol (channel: TscChannel) (parameters: CheckerNodeParams) : SymbolResponse voption =
        ProtoJson.requestOption<CheckerNodeParams, SymbolResponse> channel Method.GetExportSpecifierLocalTargetSymbol parameters

    let getAliasedSymbol (channel: TscChannel) (parameters: CheckerSymbolParams) : SymbolResponse =
        ProtoJson.request<CheckerSymbolParams, SymbolResponse> channel Method.GetAliasedSymbol parameters

    let getImmediateAliasedSymbol (channel: TscChannel) (parameters: CheckerSymbolParams) : SymbolResponse voption =
        ProtoJson.requestOption<CheckerSymbolParams, SymbolResponse> channel Method.GetImmediateAliasedSymbol parameters

    let getTargetSymbol (channel: TscChannel) (parameters: CheckerSymbolParams) : SymbolResponse =
        ProtoJson.request<CheckerSymbolParams, SymbolResponse> channel Method.GetTargetSymbol parameters

    let getFullyQualifiedName (channel: TscChannel) (parameters: CheckerSymbolParams) : string =
        ProtoJson.request<CheckerSymbolParams, string> channel Method.GetFullyQualifiedName parameters

    let getExportsOfModule (channel: TscChannel) (parameters: CheckerSymbolParams) : SymbolResponse[] voption =
        ProtoJson.requestOption<CheckerSymbolParams, SymbolResponse[]> channel Method.GetExportsOfModule parameters

    let getMemberInModuleExports (channel: TscChannel) (parameters: GetMemberInModuleExportsParams) : SymbolResponse voption =
        ProtoJson.requestOption<GetMemberInModuleExportsParams, SymbolResponse> channel Method.GetMemberInModuleExports parameters

    let getJsDocTags (channel: TscChannel) (parameters: CheckerSymbolParams) : JSDocTagInfo[] voption =
        ProtoJson.requestOption<CheckerSymbolParams, JSDocTagInfo[]> channel Method.GetJsDocTags parameters

    let getDocumentationComment (channel: TscChannel) (parameters: CheckerSymbolParams) : string =
        ProtoJson.request<CheckerSymbolParams, string> channel Method.GetDocumentationComment parameters

    let isArrayType (channel: TscChannel) (parameters: CheckerTypeParams) : bool =
        ProtoJson.request<CheckerTypeParams, bool> channel Method.IsArrayType parameters

    let isReadonlySymbol (channel: TscChannel) (parameters: CheckerSymbolParams) : bool =
        ProtoJson.request<CheckerSymbolParams, bool> channel Method.IsReadonlySymbol parameters

    let getReferencesToSymbolInFile (channel: TscChannel) (parameters: GetReferencesToSymbolInFileParams) : string[] =
        ProtoJson.request<GetReferencesToSymbolInFileParams, string[]> channel Method.GetReferencesToSymbolInFile parameters

    let getReferencedSymbolsForNode (channel: TscChannel) (parameters: GetReferencedSymbolsForNodeParams) : ReferencedSymbolEntry[] voption =
        ProtoJson.requestOption<GetReferencedSymbolsForNodeParams, ReferencedSymbolEntry[]> channel Method.GetReferencedSymbolsForNode parameters

    let getSignatureUsages (channel: TscChannel) (parameters: GetSignatureUsagesParams) : SignatureUsageResponse[] voption =
        ProtoJson.requestOption<GetSignatureUsagesParams, SignatureUsageResponse[]> channel Method.GetSignatureUsages parameters

    let getCompletionsAtPosition (channel: TscChannel) (parameters: GetCompletionsAtPositionParams) : CompletionInfoResponse voption =
        ProtoJson.requestOption<GetCompletionsAtPositionParams, CompletionInfoResponse> channel Method.GetCompletionsAtPosition parameters

    let getSyntacticDiagnostics (channel: TscChannel) (parameters: GetDiagnosticsParams) : DiagnosticResponse[] voption =
        ProtoJson.requestOption<GetDiagnosticsParams, DiagnosticResponse[]> channel Method.GetSyntacticDiagnostics parameters

    let getBindDiagnostics (channel: TscChannel) (parameters: GetDiagnosticsParams) : DiagnosticResponse[] voption =
        ProtoJson.requestOption<GetDiagnosticsParams, DiagnosticResponse[]> channel Method.GetBindDiagnostics parameters

    let getSemanticDiagnostics (channel: TscChannel) (parameters: GetDiagnosticsParams) : DiagnosticResponse[] voption =
        ProtoJson.requestOption<GetDiagnosticsParams, DiagnosticResponse[]> channel Method.GetSemanticDiagnostics parameters

    let getSuggestionDiagnostics (channel: TscChannel) (parameters: GetDiagnosticsParams) : DiagnosticResponse[] voption =
        ProtoJson.requestOption<GetDiagnosticsParams, DiagnosticResponse[]> channel Method.GetSuggestionDiagnostics parameters

    let getDeclarationDiagnostics (channel: TscChannel) (parameters: GetDiagnosticsParams) : DiagnosticResponse[] voption =
        ProtoJson.requestOption<GetDiagnosticsParams, DiagnosticResponse[]> channel Method.GetDeclarationDiagnostics parameters

    let getProgramDiagnostics (channel: TscChannel) (parameters: GetProjectDiagnosticsParams) : DiagnosticResponse[] voption =
        ProtoJson.requestOption<GetProjectDiagnosticsParams, DiagnosticResponse[]> channel Method.GetProgramDiagnostics parameters

    let getGlobalDiagnostics (channel: TscChannel) (parameters: GetProjectDiagnosticsParams) : DiagnosticResponse[] voption =
        ProtoJson.requestOption<GetProjectDiagnosticsParams, DiagnosticResponse[]> channel Method.GetGlobalDiagnostics parameters

    let getConfigFileParsingDiagnostics (channel: TscChannel) (parameters: GetProjectDiagnosticsParams) : DiagnosticResponse[] voption =
        ProtoJson.requestOption<GetProjectDiagnosticsParams, DiagnosticResponse[]> channel Method.GetConfigFileParsingDiagnostics parameters

    let printNode (channel: TscChannel) (parameters: PrintNodeParams) : string =
        ProtoJson.request<PrintNodeParams, string> channel Method.PrintNode parameters

    let formatNodeForInsertion (channel: TscChannel) (parameters: FormatNodeForInsertionParams) : string =
        ProtoJson.request<FormatNodeForInsertionParams, string> channel Method.FormatNodeForInsertion parameters

    let emit (channel: TscChannel) (parameters: EmitParams) : EmitResponse =
        ProtoJson.request<EmitParams, EmitResponse> channel Method.Emit parameters

    let emitToString (channel: TscChannel) (parameters: EmitParams) : EmitOutputResponse =
        ProtoJson.request<EmitParams, EmitOutputResponse> channel Method.EmitToString parameters

    let getJavaScriptEmit (channel: TscChannel) (parameters: SelectedFilesEmitParams) : EmitOutputResponse =
        ProtoJson.request<SelectedFilesEmitParams, EmitOutputResponse> channel Method.GetJavaScriptEmit parameters

    let getDeclarationEmit (channel: TscChannel) (parameters: SelectedFilesEmitParams) : EmitOutputResponse =
        ProtoJson.request<SelectedFilesEmitParams, EmitOutputResponse> channel Method.GetDeclarationEmit parameters

    let getAnyType (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : TypeResponse =
        ProtoJson.request<GetIntrinsicTypeParams, TypeResponse> channel Method.GetAnyType parameters

    let getStringType (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : TypeResponse =
        ProtoJson.request<GetIntrinsicTypeParams, TypeResponse> channel Method.GetStringType parameters

    let getNumberType (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : TypeResponse =
        ProtoJson.request<GetIntrinsicTypeParams, TypeResponse> channel Method.GetNumberType parameters

    let getBooleanType (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : TypeResponse =
        ProtoJson.request<GetIntrinsicTypeParams, TypeResponse> channel Method.GetBooleanType parameters

    let getVoidType (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : TypeResponse =
        ProtoJson.request<GetIntrinsicTypeParams, TypeResponse> channel Method.GetVoidType parameters

    let getUndefinedType (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : TypeResponse =
        ProtoJson.request<GetIntrinsicTypeParams, TypeResponse> channel Method.GetUndefinedType parameters

    let getNullType (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : TypeResponse =
        ProtoJson.request<GetIntrinsicTypeParams, TypeResponse> channel Method.GetNullType parameters

    let getNeverType (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : TypeResponse =
        ProtoJson.request<GetIntrinsicTypeParams, TypeResponse> channel Method.GetNeverType parameters

    let getUnknownType (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : TypeResponse =
        ProtoJson.request<GetIntrinsicTypeParams, TypeResponse> channel Method.GetUnknownType parameters

    let getBigIntType (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : TypeResponse =
        ProtoJson.request<GetIntrinsicTypeParams, TypeResponse> channel Method.GetBigIntType parameters

    let getESSymbolType (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : TypeResponse =
        ProtoJson.request<GetIntrinsicTypeParams, TypeResponse> channel Method.GetESSymbolType parameters

    let getNonPrimitiveType (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : TypeResponse =
        ProtoJson.request<GetIntrinsicTypeParams, TypeResponse> channel Method.GetNonPrimitiveType parameters

    let getWellKnownSymbols (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : WellKnownSymbolsResponse =
        ProtoJson.request<GetIntrinsicTypeParams, WellKnownSymbolsResponse> channel Method.GetWellKnownSymbols parameters

    let getWellKnownSignatures (channel: TscChannel) (parameters: GetIntrinsicTypeParams) : WellKnownSignaturesResponse =
        ProtoJson.request<GetIntrinsicTypeParams, WellKnownSignaturesResponse> channel Method.GetWellKnownSignatures parameters

    let startCPUProfile (channel: TscChannel) (parameters: ProfileParams) =
        ProtoJson.requestUnit channel Method.StartCPUProfile parameters

    let stopCPUProfile (channel: TscChannel) : ProfileResult =
        match ProtoJson.requestNoParams<ProfileResult> channel Method.StopCPUProfile with
        | ValueSome result -> result
        | ValueNone -> failwith "stopCPUProfile returned no result, but the schema declares one"

    let saveHeapProfile (channel: TscChannel) (parameters: ProfileParams) : ProfileResult =
        ProtoJson.request<ProfileParams, ProfileResult> channel Method.SaveHeapProfile parameters

