// <auto-generated>
//   Generated by Xantham.Generator from catalog-class-inheritance-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CatalogClassInheritanceLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Import("Actor", "class-lab:runtime"); AbstractClass>]
type Actor<'T> (seed: 'T) =
    member _.seed: 'T = jsNative

[<Interface>]
type Explicit<'T> =
    abstract seed: 'T
    abstract fetch: ('T -> 'T) option with get, set
    abstract send: value: 'T -> 'T
    [<ParamObject; Emit("$0")>]
    static member Create (seed: 'T, send: ('T -> 'T), ?fetch: ('T -> 'T)) : Explicit<'T> = jsNative

[<Interface>]
type Implicit<'T> =
    abstract send: value: 'T -> 'T
    abstract seed: 'T
    abstract fetch: ('T -> 'T) option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (send: ('T -> 'T), seed: 'T, ?fetch: ('T -> 'T)) : Implicit<'T> = jsNative

[<Interface>]
type Extension<'T> =
    abstract label: string with get, set
    abstract seed: 'T
    abstract fetch: ('T -> 'T) option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (label: string, seed: 'T, ?fetch: ('T -> 'T)) : Extension<'T> = jsNative

[<Interface>]
type Plain<'T> =
    abstract value: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T) : Plain<'T> = jsNative

[<Interface>]
type PlainDerived<'T> =
    inherit Plain<'T>
    abstract extra: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (extra: string, value: 'T) : PlainDerived<'T> = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("Explicit", "catalog-class-inheritance-lab"); EmitConstructor>]
    static member Explicit<'T> (seed: 'T) : Explicit<'T> = jsNative
    [<Import("Implicit", "catalog-class-inheritance-lab"); EmitConstructor>]
    static member Implicit<'T> (seed: 'T) : Implicit<'T> = jsNative

module Actor =
    [<Interface>]
    type IFetchHandler<'T> =
        abstract fetch: value: 'T -> 'T
        [<ParamObject; Emit("$0")>]
        static member Create (fetch: ('T -> 'T)) : IFetchHandler<'T> = jsNative
