// <auto-generated>
//   Generated by Xantham.Generator from instantiation-operand-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec InstantiationOperandLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS

[<Interface>]
type Ok<'T> =
    abstract kind: string with get, set
    abstract value: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, value: 'T) : Ok<'T> = jsNative

[<Interface>]
type Err =
    abstract kind: string with get, set
    abstract message: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, message: string) : Err = jsNative

[<RequireQualifiedAccess; TypeScriptTaggedUnion("kind", CaseRules.None)>]
type Outcome =
    | [<CompiledName("err")>] Err of message: string
    | [<CompiledName("ok")>] Ok of value: string

[<Interface>]
type Api =
    abstract last: Ok<string> with get, set
    abstract run: unit -> Outcome
    [<ParamObject; Emit("$0")>]
    static member Create (last: Ok<string>, run: (unit -> Outcome)) : Api = jsNative
