// <auto-generated>
//   Generated by Xantham.Generator from uninhabited-intersection-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec UninhabitedIntersectionLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// The positive: a method's own class collides with a <c>{ then: null }</c> marker on itself.
/// </summary>
[<Interface>]
type Timer =
    abstract ``then``: ?callback: (Timer -> obj) -> JS.Promise<obj>
    [<ParamObject; Emit("$0")>]
    static member Create (``then``: ((Timer -> obj) option -> JS.Promise<obj>)) : Timer = jsNative

/// <summary>
/// The same reduction spelled as an alias, at both the alias's own declaration and a use.
/// </summary>
[<Interface>]
type Named =
    abstract ``then``: unit -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (``then``: (unit -> unit)) : Named = jsNative

type Reduced = Named

/// <summary>
/// No name collision: the marker names a property <c>Ticking</c> does not declare.
/// </summary>
[<Interface>]
type Ticking =
    abstract ``then``: ?callback: (Ticking.Then.Callback.Self -> obj) -> JS.Promise<obj>
    [<ParamObject; Emit("$0")>]
    static member Create (``then``: ((Ticking.Then.Callback.Self -> obj) option -> JS.Promise<obj>)) : Ticking = jsNative

module Ticking =
    module Then =
        module Callback =
            [<Interface>]
            type Self =
                inherit Ticking
                abstract ``then``: ?callback: (Ticking.Then.Callback.Self -> obj) -> JS.Promise<obj>
                abstract paused: bool with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (``then``: ((Ticking.Then.Callback.Self -> obj) option -> JS.Promise<obj>), paused: bool) : Self = jsNative

/// <summary>
/// The collided name is not a member of the operand it is intersected against.
/// </summary>
[<Interface>]
type Player =
    abstract play: ?callback: (Player.Play.Callback.Self -> obj) -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (play: ((Player.Play.Callback.Self -> obj) option -> unit)) : Player = jsNative

module Player =
    module Play =
        module Callback =
            [<Interface>]
            type Self =
                inherit Player
                abstract play: ?callback: (Player.Play.Callback.Self -> obj) -> unit
                abstract ``then``: obj with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (play: ((Player.Play.Callback.Self -> obj) option -> unit), ``then``: obj) : Self = jsNative

/// <summary>
/// The collision is not unit-typed: TypeScript does not empty the whole intersection, so the
/// loss (if any) belongs to the <c>then</c> member itself, not to <c>Chained</c>'s own declaration.
/// </summary>
[<Interface>]
type Chained =
    abstract ``then``: ?callback: (Chained.Then.Callback.Self -> obj) -> JS.Promise<obj>
    [<ParamObject; Emit("$0")>]
    static member Create (``then``: ((Chained.Then.Callback.Self -> obj) option -> JS.Promise<obj>)) : Chained = jsNative

module Chained =
    module Then =
        module Callback =
            [<Interface>]
            type Self =
                inherit Chained
                abstract ``then``: obj with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (``then``: obj) : Self = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// The positive: a method's own class collides with a <c>{ then: null }</c> marker on itself.
    /// </summary>
    [<Import("Timer", "uninhabited-intersection-lab"); EmitConstructor>]
    static member Timer () : Timer = jsNative
    [<Import("reduced", "uninhabited-intersection-lab")>]
    static member reduced: Named = jsNative
    /// <summary>
    /// No name collision: the marker names a property <c>Ticking</c> does not declare.
    /// </summary>
    [<Import("Ticking", "uninhabited-intersection-lab"); EmitConstructor>]
    static member Ticking () : Ticking = jsNative
    /// <summary>
    /// The collided name is not a member of the operand it is intersected against.
    /// </summary>
    [<Import("Player", "uninhabited-intersection-lab"); EmitConstructor>]
    static member Player () : Player = jsNative
    /// <summary>
    /// The collision is not unit-typed: TypeScript does not empty the whole intersection, so the
    /// loss (if any) belongs to the <c>then</c> member itself, not to <c>Chained</c>'s own declaration.
    /// </summary>
    [<Import("Chained", "uninhabited-intersection-lab"); EmitConstructor>]
    static member Chained () : Chained = jsNative
