// <auto-generated>
//   Generated by Xantham.Generator from shared-tag-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec SharedTagLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<RequireQualifiedAccess; TypeScriptTaggedUnion("kind", CaseRules.None)>]
type Distinct =
    | [<CompiledName("circle")>] Circle of radius: float
    | [<CompiledName("square")>] Square of side: float
    | [<CompiledName("point")>] Point

[<Interface>]
type Distinct2 =
    abstract kind: string
    abstract radius: float
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, radius: float) : Distinct2 = jsNative

[<Interface>]
type Distinct3 =
    abstract kind: string
    abstract side: float
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, side: float) : Distinct3 = jsNative

[<Interface>]
type Distinct4 =
    abstract kind: string
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string) : Distinct4 = jsNative

[<RequireQualifiedAccess; TypeScriptTaggedUnion("verb", CaseRules.None)>]
type Signal =
    | [<CompiledName("start")>] Start of channel: string * at: float
    | [<CompiledName("stop")>] Stop of channel: string * reason: string

[<Interface>]
type Signal2 =
    abstract channel: string
    abstract verb: string
    abstract at: float
    [<ParamObject; Emit("$0")>]
    static member Create (channel: string, verb: string, at: float) : Signal2 = jsNative

[<Interface>]
type Signal3 =
    abstract channel: string
    abstract verb: string
    abstract reason: string
    [<ParamObject; Emit("$0")>]
    static member Create (channel: string, verb: string, reason: string) : Signal3 = jsNative

[<RequireQualifiedAccess; TypeScriptTaggedUnion("state", CaseRules.None)>]
type Terminal =
    | [<CompiledName("done")>] Done
    | [<CompiledName("pending")>] Pending

[<Interface>]
type Terminal2 =
    abstract state: string
    abstract value: float
    [<ParamObject; Emit("$0")>]
    static member Create (state: string, value: float) : Terminal2 = jsNative

[<Interface>]
type Terminal3 =
    abstract state: string
    abstract error: string
    [<ParamObject; Emit("$0")>]
    static member Create (state: string, error: string) : Terminal3 = jsNative

[<Interface>]
type Terminal4 =
    abstract state: string
    [<ParamObject; Emit("$0")>]
    static member Create (state: string) : Terminal4 = jsNative

type Onset = U2<Onset2, Onset3>

[<Interface>]
type Onset2 =
    abstract ``type``: string
    abstract level: string
    abstract message: obj
    abstract truncated: bool option
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, level: string, message: obj, ?truncated: bool) : Onset2 = jsNative

[<Interface>]
type Onset3 =
    abstract ``type``: string
    abstract level: string
    abstract message: string
    abstract truncated: bool
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, level: string, message: string, truncated: bool) : Onset3 = jsNative

type Log = U2<Log2, Log3>

[<Interface>]
type Log2 =
    abstract ``type``: string
    abstract level: string
    abstract message: obj
    abstract truncated: bool option
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, level: string, message: obj, ?truncated: bool) : Log2 = jsNative

[<Interface>]
type Log3 =
    abstract ``type``: string
    abstract level: string
    abstract message: string
    abstract truncated: bool
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, level: string, message: string, truncated: bool) : Log3 = jsNative

type Loose = U2<Loose2, Loose3>

[<Interface>]
type Loose2 =
    abstract kind: string
    abstract a: float
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, a: float) : Loose2 = jsNative

[<Interface>]
type Loose3 =
    abstract kind: string
    abstract b: float
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, b: float) : Loose3 = jsNative

[<Interface>]
type FetchInfo =
    abstract ``type``: string
    abstract url: string
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, url: string) : FetchInfo = jsNative

[<Interface>]
type AlarmInfo =
    abstract ``type``: string
    abstract scheduledTime: float
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, scheduledTime: float) : AlarmInfo = jsNative

[<Interface>]
type JsRpcInfo =
    abstract ``type``: string
    abstract methodName: string
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, methodName: string) : JsRpcInfo = jsNative

[<Interface>]
type ScheduledInfo =
    abstract ``type``: string
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string) : ScheduledInfo = jsNative

[<Interface>]
type QueueInfo =
    abstract ``type``: string
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string) : QueueInfo = jsNative

[<Interface>]
type EmailInfo =
    abstract ``type``: string
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string) : EmailInfo = jsNative

[<Interface>]
type TraceInfo =
    abstract ``type``: string
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string) : TraceInfo = jsNative

[<Interface>]
type SocketInfo =
    abstract ``type``: string
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string) : SocketInfo = jsNative

[<Interface>]
type CustomInfo =
    abstract ``type``: string
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string) : CustomInfo = jsNative

[<Interface>]
type ConnectInfo =
    abstract ``type``: string
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string) : ConnectInfo = jsNative

[<Interface>]
type Wide =
    abstract ``event``: Wide.Event
    [<ParamObject; Emit("$0")>]
    static member Create (``event``: Wide.Event) : Wide = jsNative

type OnWide = (Wide.Event -> unit)

[<RequireQualifiedAccess; TypeScriptTaggedUnion("type", CaseRules.None)>]
type Named =
    | [<CompiledName("alarm")>] Alarm of scheduledTime: float
    | [<CompiledName("fetch")>] Fetch of url: string
    | [<CompiledName("jsrpc")>] Jsrpc of methodName: string

[<Interface>]
type Alias =
    abstract ``event``: Named
    [<ParamObject; Emit("$0")>]
    static member Create (``event``: Named) : Alias = jsNative

[<Interface>]
type Narrow =
    abstract ``event``: Narrow.Event
    [<ParamObject; Emit("$0")>]
    static member Create (``event``: Narrow.Event) : Narrow = jsNative

type OnEvent = (OnEvent.Event -> unit)

module Narrow =
    [<RequireQualifiedAccess; TypeScriptTaggedUnion("type", CaseRules.None)>]
    type Event =
        | [<CompiledName("email")>] Email
        | [<CompiledName("queue")>] Queue
        | [<CompiledName("scheduled")>] Scheduled

module OnEvent =
    [<RequireQualifiedAccess; TypeScriptTaggedUnion("type", CaseRules.None)>]
    type Event =
        | [<CompiledName("alarm")>] Alarm of scheduledTime: float
        | [<CompiledName("custom")>] Custom
        | [<CompiledName("email")>] Email
        | [<CompiledName("fetch")>] Fetch of url: string
        | [<CompiledName("jsrpc")>] Jsrpc of methodName: string
        | [<CompiledName("queue")>] Queue
        | [<CompiledName("scheduled")>] Scheduled
        | [<CompiledName("socket")>] Socket
        | [<CompiledName("trace")>] Trace
        | [<CompiledName("log")>] Log of level: string

module Wide =
    [<RequireQualifiedAccess; TypeScriptTaggedUnion("type", CaseRules.None)>]
    type Event =
        | [<CompiledName("alarm")>] Alarm of scheduledTime: float
        | [<CompiledName("connect")>] Connect
        | [<CompiledName("custom")>] Custom
        | [<CompiledName("email")>] Email
        | [<CompiledName("fetch")>] Fetch of url: string
        | [<CompiledName("jsrpc")>] Jsrpc of methodName: string
        | [<CompiledName("queue")>] Queue
        | [<CompiledName("scheduled")>] Scheduled
        | [<CompiledName("socket")>] Socket
        | [<CompiledName("trace")>] Trace
