// <auto-generated>
//   Generated by Xantham.Generator from nested-dep-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec NestedDepLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// A reading the entry package declares over a dependency's type.
/// </summary>
[<Interface>]
type Reading =
    abstract signal: OuterLab.Signal with get, set
    abstract taken: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (signal: OuterLab.Signal, taken: string) : Reading = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("read", "nested-dep-lab")>]
    static member read (signal: OuterLab.Signal) : Reading = jsNative
