// <auto-generated>
//   Generated by Xantham.Generator from brand-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec BrandLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// The common hand-rolled brand: a primitive and a literal-typed marker property.
/// </summary>
/// <remarks>A brand over <c>string</c>.</remarks>
[<Measure>]
type UserId

/// <summary>
/// A second brand over the same primitive - distinct from the first, and that is the point.
/// </summary>
/// <remarks>A brand over <c>string</c>.</remarks>
[<Measure>]
type SessionId

/// <summary>
/// The type-fest style: the marker is keyed by a unique symbol, so nothing can name it.
/// </summary>
/// <remarks>A brand over <c>string</c>.</remarks>
[<Measure>]
type OrderId

/// <summary>
/// A branded number. Measures apply to numbers natively, with no support package at all.
/// </summary>
/// <remarks>A brand over <c>float</c>.</remarks>
[<Measure>]
type Millis

/// <summary>
/// A branded boolean.
/// </summary>
/// <remarks>A brand over <c>bool</c>.</remarks>
[<Measure>]
type Verified

/// <summary>
/// A brand whose marker carries `never` - the marker is unconstructible, not just unnamed.
/// </summary>
/// <remarks>A brand over <c>string</c>.</remarks>
[<Measure>]
type Nonce

/// <summary>
/// A brand over a literal union rather than a bare primitive.
/// </summary>
/// <remarks>A brand over <c>string</c>.</remarks>
[<Measure>]
type Mode

type Store =
    /// <summary>
    /// A brand in a parameter and a plain primitive as the return.
    /// </summary>
    abstract get: id: string<UserId> -> string
    /// <summary>
    /// Two different brands over two different primitives in one signature.
    /// </summary>
    abstract put: id: string<UserId> * at: float<Millis> -> unit
    /// <summary>
    /// A brand under an array.
    /// </summary>
    abstract ids: unit -> string<UserId>[]
    /// <summary>
    /// A brand under an optional.
    /// </summary>
    abstract find: ?id: string<SessionId> -> string<UserId> option
    /// <summary>
    /// A branded property.
    /// </summary>
    abstract owner: string<UserId>

/// <summary>
/// An intersection of two object types: a real shape, not a brand.
/// </summary>
type Merged = obj

/// <summary>
/// A primitive intersected with an object that has a *real* member - not a brand.
/// </summary>
type Counted = obj

/// <summary>
/// An object intersected with a branded primitive: still not a branded object.
/// </summary>
type Wrapped = obj

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// The marker a unique symbol keys, exported so that the brand can be spelled elsewhere.
    /// </summary>
    [<Import("orderIdTag", "brand-lab")>]
    static member orderIdTag: obj = jsNative
    /// <summary>
    /// A brand as a bare exported function's parameter and return.
    /// </summary>
    [<Import("mint", "brand-lab")>]
    static member mint (seed: string) : string<UserId> = jsNative
