// <auto-generated>
//   Generated by Xantham.Generator from type-only-export-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec TypeOnlyExportLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS

[<Interface>]
type Payload =
    abstract text: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (text: string) : Payload = jsNative

type Message = Payload

[<Interface>]
type Client =
    abstract send: payload: Payload -> Payload
    [<ParamObject; Emit("$0")>]
    static member Create (send: (Payload -> Payload)) : Client = jsNative

type HiddenFunction = (Payload -> Payload)

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("visible", "type-only-export-lab")>]
    static member visible (payload: Payload) : Client = jsNative
