// <auto-generated>
//   Generated by Xantham.Generator from auto-open-exports-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec AutoOpenExportsLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("greet", "auto-open-exports-lab")>]
    static member greet (name: string) : string = jsNative
    [<Import("version", "auto-open-exports-lab")>]
    static member version: string = jsNative
