// <auto-generated>
//   Generated by Xantham.Generator from inherited-members-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec InheritedMembersLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Attr =
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string) : Attr = jsNative

/// <summary>
/// Root of the chain.
/// </summary>
[<Interface>]
type Node =
    abstract nodeName: string with get, set
    abstract cloneNode: ?deep: bool -> Node
    [<ParamObject; Emit("$0")>]
    static member Create (nodeName: string, cloneNode: (bool option -> Node)) : Node = jsNative

/// <summary>
/// Second level: inherits <c>Node</c>, narrows <c>cloneNode</c>, adds its own.
/// </summary>
[<Interface>]
type Element =
    inherit Node
    abstract getAttributeNode: name: string -> Attr option
    abstract cloneNode: ?deep: bool -> Element
    [<ParamObject; Emit("$0")>]
    static member Create (getAttributeNode: (string -> Attr option), cloneNode: (bool option -> Element), nodeName: string) : Element = jsNative

/// <summary>
/// Third level: inherits <c>Element</c>, narrows <c>cloneNode</c> again.
/// </summary>
[<Interface>]
type HTMLElement =
    inherit Element
    abstract hidden: bool with get, set
    abstract cloneNode: ?deep: bool -> HTMLElement
    [<ParamObject; Emit("$0")>]
    static member Create (hidden: bool, cloneNode: (bool option -> HTMLElement), nodeName: string, getAttributeNode: (string -> Attr option)) : HTMLElement = jsNative

/// <summary>
/// Leaf: everything above is inherited; only <c>align</c> and the narrowed <c>cloneNode</c> are its own.
/// </summary>
[<Interface>]
type HTMLDivElement =
    inherit HTMLElement
    abstract align: string with get, set
    abstract cloneNode: ?deep: bool -> HTMLDivElement
    [<ParamObject; Emit("$0")>]
    static member Create (align: string, cloneNode: (bool option -> HTMLDivElement), nodeName: string, getAttributeNode: (string -> Attr option), hidden: bool) : HTMLDivElement = jsNative

/// <summary>
/// A diamond: both arms carry <c>volume</c> from <c>Loud</c>.
/// </summary>
[<Interface>]
type Loud =
    abstract volume: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (volume: float) : Loud = jsNative

[<Interface>]
type Pitched =
    inherit Loud
    abstract pitch: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (pitch: float, volume: float) : Pitched = jsNative

[<Interface>]
type Both =
    inherit Loud
    inherit Pitched
    abstract both: bool with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (both: bool, volume: float, pitch: float) : Both = jsNative
