// <auto-generated>
//   Generated by Xantham.Generator from catalog-library-entry-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec Library.Consumer

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type GlobalThis =
    abstract ActiveXObject: TypeScript.Lib.Dom.ActiveXObject with get, set
    abstract WScript: TypeScript.Lib.Dom.WScript with get, set
    /// <summary>
    /// WSH is an alias for WScript under Windows Script Host
    /// </summary>
    abstract WSH: TypeScript.Lib.Dom.WScript with get, set
    /// <summary>
    /// Allows enumerating over a COM collection, which may not have indexed item access.
    /// </summary>
    abstract Enumerator: TypeScript.Lib.Dom.EnumeratorConstructor with get, set
    /// <summary>
    /// Enables reading from a COM safe array, which might have an alternate lower bound, or multiple dimensions.
    /// </summary>
    abstract VBArray: TypeScript.Lib.Dom.VBArrayConstructor with get, set
    abstract globalThis: GlobalThis
    abstract undefined: unit
    [<ParamObject; Emit("$0")>]
    static member Create (ActiveXObject: TypeScript.Lib.Dom.ActiveXObject, WScript: TypeScript.Lib.Dom.WScript, WSH: TypeScript.Lib.Dom.WScript, Enumerator: TypeScript.Lib.Dom.EnumeratorConstructor, VBArray: TypeScript.Lib.Dom.VBArrayConstructor, globalThis: GlobalThis) : GlobalThis = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("accept", "catalog-library-entry-lab")>]
    static member accept (value: TypeScript.Lib.Dom.TextStreamReader) : TypeScript.Lib.Dom.TextStreamReader = jsNative

module Globals =
    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    [<Global("globalThis")>]
    type Exports =
        static member ActiveXObject
            with get (): TypeScript.Lib.Dom.ActiveXObject = jsNative
            and set (_: TypeScript.Lib.Dom.ActiveXObject): unit = jsNative
        static member WScript
            with get (): TypeScript.Lib.Dom.WScript = jsNative
            and set (_: TypeScript.Lib.Dom.WScript): unit = jsNative
        /// <summary>
        /// WSH is an alias for WScript under Windows Script Host
        /// </summary>
        static member WSH
            with get (): TypeScript.Lib.Dom.WScript = jsNative
            and set (_: TypeScript.Lib.Dom.WScript): unit = jsNative
        /// <summary>
        /// Represents an Automation SAFEARRAY
        /// </summary>
        [<Global("SafeArray"); EmitConstructor>]
        static member SafeArray<'T> () : TypeScript.Lib.Dom.SafeArray<'T> = jsNative
        /// <summary>
        /// Allows enumerating over a COM collection, which may not have indexed item access.
        /// </summary>
        static member Enumerator
            with get (): TypeScript.Lib.Dom.EnumeratorConstructor = jsNative
            and set (_: TypeScript.Lib.Dom.EnumeratorConstructor): unit = jsNative
        /// <summary>
        /// Enables reading from a COM safe array, which might have an alternate lower bound, or multiple dimensions.
        /// </summary>
        static member VBArray
            with get (): TypeScript.Lib.Dom.VBArrayConstructor = jsNative
            and set (_: TypeScript.Lib.Dom.VBArrayConstructor): unit = jsNative
        /// <summary>
        /// Automation date (VT_DATE)
        /// </summary>
        [<Global("VarDate"); EmitConstructor>]
        static member VarDate () : TypeScript.Lib.Dom.VarDate = jsNative
        [<Global("globalThis")>]
        static member globalThis: GlobalThis = jsNative
