// <auto-generated>
//   Generated by Xantham.Generator from record-index-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec RecordIndexLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

/// <summary>
/// An inline string-keyed index signature, in property position.
/// </summary>
[<Interface>]
type Cache =
    abstract entries: JS.Record<string, float> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (entries: JS.Record<string, float>) : Cache = jsNative

/// <summary>
/// An inline numeric-keyed index signature, in property position.
/// </summary>
[<Interface>]
type Grid =
    abstract rows: JS.Record<float, string> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (rows: JS.Record<float, string>) : Grid = jsNative

/// <summary>
/// An inline readonly index signature, in property position - <c>ReadonlyRecord</c>.
/// </summary>
[<Interface>]
type Frozen =
    abstract values: ReadonlyRecord<string, bool> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (values: ReadonlyRecord<string, bool>) : Frozen = jsNative

/// <summary>
/// A pure index signature declared under its own name.
/// </summary>
type Bag =
    [<EmitIndexer>]
    abstract Item: string -> float with get, set

/// <summary>
/// An index signature beside a real member.
/// </summary>
type Config =
    abstract name: string with get, set
    [<EmitIndexer>]
    abstract Item: string -> string with get, set

/// <summary>
/// The package's own <c>Record</c>, unrelated to the support package's.
/// </summary>
[<Interface>]
type Record =
    abstract id: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (id: string) : Record = jsNative

/// <summary>
/// An inline index signature alongside the package's own <c>Record</c>.
/// </summary>
[<Interface>]
type Ledger =
    abstract entries: JS.Record<string, float> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (entries: JS.Record<string, float>) : Ledger = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// An inline index signature keyed by a generic function's own type parameter.
    /// </summary>
    [<Import("tag", "record-index-lab")>]
    static member tag<'T> (value: JS.Record<string, 'T>) : unit = jsNative
