// <auto-generated>
//   Generated by Xantham.Generator from hoist-conditional-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec HoistConditionalLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Interface>]
type CondExtensions<'TNodeType> =
    abstract toVar: Func<string option, obj> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (toVar: Func<string option, obj>) : CondExtensions<'TNodeType> = jsNative

[<Erase>]
type CondNode<'TNodeType> = private CondNode__ of obj

[<Interface>]
type CondVarNodeInterface<'TNode> =
    abstract node: 'TNode with get, set
    abstract isVarNode: bool
    [<ParamObject; Emit("$0")>]
    static member Create (node: 'TNode, isVarNode: bool) : CondVarNodeInterface<'TNode> = jsNative

[<Erase>]
type CondVarNode<'TNodeType, 'TNode> = private CondVarNode__ of obj

[<Interface>]
type DirectExtensions<'TNodeType> =
    abstract toVar: Func<string option, DirectVarNode<'TNodeType, DirectExtensions<'TNodeType>>> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (toVar: Func<string option, DirectVarNode<'TNodeType, DirectExtensions<'TNodeType>>>) : DirectExtensions<'TNodeType> = jsNative

[<Interface>]
type DirectNode<'TNodeType> =
    inherit DirectExtensions<'TNodeType>
    abstract isNode: bool
    abstract toVar: Func<string option, DirectVarNode<'TNodeType, DirectNode<'TNodeType>>> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (isNode: bool, toVar: Func<string option, DirectVarNode<'TNodeType, DirectNode<'TNodeType>>>) : DirectNode<'TNodeType> = jsNative

[<Interface>]
type DirectVarNodeInterface<'TNode> =
    abstract node: 'TNode with get, set
    abstract isVarNode: bool
    [<ParamObject; Emit("$0")>]
    static member Create (node: 'TNode, isVarNode: bool) : DirectVarNodeInterface<'TNode> = jsNative

[<Interface>]
type DirectVarNode<'TNodeType, 'TNode> =
    inherit DirectExtensions<'TNodeType>
    inherit DirectVarNodeInterface<'TNode>
    abstract isNode: bool
    abstract toVar: Func<string option, DirectVarNode<'TNodeType, DirectVarNode<'TNodeType, 'TNode>>> with get, set
    abstract node: 'TNode with get, set
    abstract isVarNode: bool
    [<ParamObject; Emit("$0")>]
    static member Create (isNode: bool, toVar: Func<string option, DirectVarNode<'TNodeType, DirectVarNode<'TNodeType, 'TNode>>>, node: 'TNode, isVarNode: bool) : DirectVarNode<'TNodeType, 'TNode> = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("condSeed", "hoist-conditional-lab")>]
    static member condSeed: obj = jsNative
    [<Import("directSeed", "hoist-conditional-lab")>]
    static member directSeed: DirectNode<float> = jsNative
