// <auto-generated>
//   Generated by Xantham.Generator from callback-overload-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CallbackOverloadLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

type Formatter = (float -> string)

type Holder =
    /// <summary>
    /// A required member, written with property syntax around an object type rather than TS's
    /// method syntax, whose two signatures differ in arity: F# admits both as an overload pair
    /// under this member's own name, so nothing is dropped and no name is minted.
    /// </summary>
    abstract round: value: float -> float
    /// <summary>
    /// A required member, written with property syntax around an object type rather than TS's
    /// method syntax, whose two signatures differ in arity: F# admits both as an overload pair
    /// under this member's own name, so nothing is dropped and no name is minted.
    /// </summary>
    abstract round: value: float * precision: float -> float
    /// <summary>
    /// A required member whose two signatures share arity and parameter types, differing only in
    /// return type - .NET overload resolution never consults a return type, so the set is not
    /// separable and <c>TR062</c> reports it rather than <c>TR031</c>.
    /// </summary>
    abstract parse: (string -> float) with get, set
    /// <summary>
    /// An optional member with two otherwise-separable signatures: F#'s method form has no way to
    /// carry the option <c>?</c> demands, so this stays on the floor <c>TR031</c> describes.
    /// </summary>
    abstract measure: (float -> float) option with get, set
    /// <summary>
    /// Reference position for <c>Formatter</c>, exercising the named declaration's own floor from a
    /// member.
    /// </summary>
    abstract formatter: value: float -> string
    /// <summary>
    /// Reference position for <c>Formatter</c>, exercising the named declaration's own floor from a
    /// member.
    /// </summary>
    abstract formatter: value: float * radix: float -> string
