// <auto-generated>
//   Generated by Xantham.Generator from declaration-identity-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec DeclarationIdentityLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type PublicClient =
    abstract send: message: string -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (send: (string -> unit)) : PublicClient = jsNative

[<Interface>]
type Item =
    abstract id: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (id: string) : Item = jsNative

[<Interface>]
type PublicBox<'T when 'T :> Item> =
    abstract value: 'T with get, set
    abstract options: PublicBox.Options with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T, options: PublicBox.Options) : PublicBox<'T> = jsNative

[<Interface>]
type Config<'T> =
    abstract value: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T) : Config<'T> = jsNative

[<Interface>]
type TextConfig =
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string) : TextConfig = jsNative

[<Interface>]
type Holder =
    abstract config: Holder.Config with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (config: Holder.Config) : Holder = jsNative

[<Interface>]
type GenericClient<'T> =
    abstract value: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T) : GenericClient<'T> = jsNative

type StringConstructor =
    [<EmitConstructor>]
    abstract Create: value: string -> GenericClient<string>

[<Interface>]
type Left =
    abstract left: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (left: string) : Left = jsNative

[<Interface>]
type Right =
    abstract right: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (right: float) : Right = jsNative

[<Interface>]
type LeftCallback =
    abstract run<'U when 'U :> Left>: value: 'U -> 'U
    [<ParamObject; Emit("$0")>]
    static member Create (run: ('U -> 'U)) : LeftCallback = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("PublicClient", "declaration-identity-lab"); EmitConstructor>]
    static member PublicClient () : PublicClient = jsNative
    [<Import("GenericClient", "declaration-identity-lab"); EmitConstructor>]
    static member GenericClient<'T> (value: 'T) : GenericClient<'T> = jsNative

module Holder =
    [<Interface>]
    type Config =
        abstract value: string with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (value: string) : Config = jsNative

module PublicBox =
    [<Interface>]
    type Options =
        abstract retry: bool with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (retry: bool) : Options = jsNative
