// <auto-generated>
//   Generated by Xantham.Generator from worker-augmentation-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec GroupedDomAliases.WorkerAugmentationLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Request =
    /// <summary>
    /// The <b><c>cache</c></b> read-only property of the Request interface contains the cache mode of the request. It controls how the request will interact with the browser's HTTP cache.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/cache">MDN Reference</a>
    /// </summary>
    abstract cache: Request.Cache
    /// <summary>
    /// The <b><c>credentials</c></b> read-only property of the Request interface reflects the value given to the Request() constructor in the credentials option. It determines whether or not the browser sends credentials with the request, as well as whether any Set-Cookie response headers are respected.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/credentials">MDN Reference</a>
    /// </summary>
    abstract credentials: Request.Credentials
    /// <summary>
    /// The <b><c>destination</c></b> read-only property of the Request interface returns a string describing the type of content being requested.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/destination">MDN Reference</a>
    /// </summary>
    abstract destination: Request.Destination
    /// <summary>
    /// The <b><c>headers</c></b> read-only property of the Request interface contains the Headers object associated with the request.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/headers">MDN Reference</a>
    /// </summary>
    abstract headers: Fable.Core.TS.Dom.Headers
    /// <summary>
    /// The <b><c>integrity</c></b> read-only property of the Request interface contains the subresource integrity value of the request.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/integrity">MDN Reference</a>
    /// </summary>
    abstract integrity: string
    /// <summary>
    /// The <b><c>keepalive</c></b> read-only property of the Request interface contains the request's keepalive setting (true or false), which indicates whether the browser will keep the associated request alive if the page that initiated it is unloaded before the request is complete.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/keepalive">MDN Reference</a>
    /// </summary>
    abstract keepalive: bool
    /// <summary>
    /// The <b><c>method</c></b> read-only property of the Request interface contains the request's method (GET, POST, etc.)
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/method">MDN Reference</a>
    /// </summary>
    abstract ``method``: string
    /// <summary>
    /// The <b><c>mode</c></b> read-only property of the Request interface contains the mode of the request (e.g., cors, no-cors, same-origin, or navigate.) This is used to determine if cross-origin requests lead to valid responses, and which properties of the response are readable.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/mode">MDN Reference</a>
    /// </summary>
    abstract mode: Request.Mode
    /// <summary>
    /// The <b><c>redirect</c></b> read-only property of the Request interface contains the mode for how redirects are handled.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/redirect">MDN Reference</a>
    /// </summary>
    abstract redirect: Request.Redirect
    /// <summary>
    /// The <b><c>referrer</c></b> read-only property of the Request interface is set by the user agent to be the referrer of the Request. (e.g., client, no-referrer, or a URL.)
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/referrer">MDN Reference</a>
    /// </summary>
    abstract referrer: string
    /// <summary>
    /// The <b><c>referrerPolicy</c></b> read-only property of the Request interface returns the referrer policy, which governs what referrer information, sent in the Referer header, should be included with the request.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/referrerPolicy">MDN Reference</a>
    /// </summary>
    abstract referrerPolicy: Request.ReferrerPolicy
    /// <summary>
    /// The read-only <b><c>signal</c></b> property of the Request interface returns the AbortSignal associated with the request.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/signal">MDN Reference</a>
    /// </summary>
    abstract signal: Fable.Core.TS.Dom.AbortSignal
    /// <summary>
    /// The <b><c>url</c></b> read-only property of the Request interface contains the URL of the request.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/url">MDN Reference</a>
    /// </summary>
    abstract url: string
    /// <summary>
    /// The <b><c>clone()</c></b> method of the Request interface creates a copy of the current Request object.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/clone">MDN Reference</a>
    /// </summary>
    abstract clone: unit -> Request
    abstract cf: string
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/body">MDN Reference</a>
    /// </summary>
    abstract body: Fable.Core.TS.Dom.ReadableStream<JS.Uint8Array> option
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/bodyUsed">MDN Reference</a>
    /// </summary>
    abstract bodyUsed: bool
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/arrayBuffer">MDN Reference</a>
    /// </summary>
    abstract arrayBuffer: unit -> JS.Promise<JS.ArrayBuffer>
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/blob">MDN Reference</a>
    /// </summary>
    abstract blob: unit -> JS.Promise<Fable.Core.TS.Dom.Blob>
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/bytes">MDN Reference</a>
    /// </summary>
    abstract bytes: unit -> JS.Promise<JS.Uint8Array>
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/formData">MDN Reference</a>
    /// </summary>
    abstract formData: unit -> JS.Promise<Fable.Core.TS.Dom.FormData>
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/json">MDN Reference</a>
    /// </summary>
    abstract json: unit -> JS.Promise<obj>
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/text">MDN Reference</a>
    /// </summary>
    abstract text: unit -> JS.Promise<string>
    [<ParamObject; Emit("$0")>]
    static member Create (cache: Request.Cache, credentials: Request.Credentials, destination: Request.Destination, headers: Fable.Core.TS.Dom.Headers, integrity: string, keepalive: bool, ``method``: string, mode: Request.Mode, redirect: Request.Redirect, referrer: string, referrerPolicy: Request.ReferrerPolicy, signal: Fable.Core.TS.Dom.AbortSignal, url: string, clone: (unit -> Request), cf: string, bodyUsed: bool, arrayBuffer: (unit -> JS.Promise<JS.ArrayBuffer>), blob: (unit -> JS.Promise<Fable.Core.TS.Dom.Blob>), bytes: (unit -> JS.Promise<JS.Uint8Array>), formData: (unit -> JS.Promise<Fable.Core.TS.Dom.FormData>), json: (unit -> JS.Promise<obj>), text: (unit -> JS.Promise<string>), ?body: Fable.Core.TS.Dom.ReadableStream<JS.Uint8Array>) : Request = jsNative

module Request =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Cache =
        | [<CompiledName("default")>] Default
        | [<CompiledName("force-cache")>] ForceCache
        | [<CompiledName("no-cache")>] NoCache
        | [<CompiledName("no-store")>] NoStore
        | [<CompiledName("only-if-cached")>] OnlyIfCached
        | [<CompiledName("reload")>] Reload

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Credentials =
        | [<CompiledName("include")>] Include
        | [<CompiledName("omit")>] Omit
        | [<CompiledName("same-origin")>] SameOrigin

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Destination =
        | [<CompiledName("")>] Empty
        | [<CompiledName("audio")>] Audio
        | [<CompiledName("audioworklet")>] Audioworklet
        | [<CompiledName("document")>] Document
        | [<CompiledName("embed")>] Embed
        | [<CompiledName("font")>] Font
        | [<CompiledName("frame")>] Frame
        | [<CompiledName("iframe")>] Iframe
        | [<CompiledName("image")>] Image
        | [<CompiledName("manifest")>] Manifest
        | [<CompiledName("object")>] Object
        | [<CompiledName("paintworklet")>] Paintworklet
        | [<CompiledName("report")>] Report
        | [<CompiledName("script")>] Script
        | [<CompiledName("sharedworker")>] Sharedworker
        | [<CompiledName("style")>] Style
        | [<CompiledName("track")>] Track
        | [<CompiledName("video")>] Video
        | [<CompiledName("worker")>] Worker
        | [<CompiledName("xslt")>] Xslt

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Mode =
        | [<CompiledName("cors")>] Cors
        | [<CompiledName("navigate")>] Navigate
        | [<CompiledName("no-cors")>] NoCors
        | [<CompiledName("same-origin")>] SameOrigin

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Redirect =
        | [<CompiledName("error")>] Error
        | [<CompiledName("follow")>] Follow
        | [<CompiledName("manual")>] Manual

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type ReferrerPolicy =
        | [<CompiledName("")>] Empty
        | [<CompiledName("no-referrer")>] NoReferrer
        | [<CompiledName("no-referrer-when-downgrade")>] NoReferrerWhenDowngrade
        | [<CompiledName("origin")>] Origin
        | [<CompiledName("origin-when-cross-origin")>] OriginWhenCrossOrigin
        | [<CompiledName("same-origin")>] SameOrigin
        | [<CompiledName("strict-origin")>] StrictOrigin
        | [<CompiledName("strict-origin-when-cross-origin")>] StrictOriginWhenCrossOrigin
        | [<CompiledName("unsafe-url")>] UnsafeUrl
