#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Xantham STATUS REPORT — generates docs/STATUS.md and gates Phase-0 L0 signals.
#
# Signals (docs/GOALS.md "Per-layer definitions of done"):
#   L0: every reached package has a declared role (bound lib | dependency policy);
#       MISSING-POLICY count gates non-zero exit. Per-entry provenance counts.
#   L1: whole-artifact legacy numbers until Phase-1 partitioned emission lands
#       (per-area gates replace them; see docs/PLAN.md Phase 1).
#   Coverage: test-case counts per module (owner parity rule, PLAN standing rules).
#
# Run:  scripts/status-report.sh [path/to/ir.json]     (default: committed IR)
# Exit: non-zero if any reached package lacks a declared role/policy.
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IR="${1:-$REPO/src/Xantham.Fable/output.json}"
RECIPE="$REPO/cloudflare.pilot.toml"
OUT="$REPO/docs/STATUS.md"

python3 - "$IR" "$RECIPE" "$OUT" "$REPO" <<'PY'
import json, re, sys, tomllib, subprocess, hashlib
from collections import defaultdict
from datetime import date

ir_path, recipe_path, out_path, repo = sys.argv[1:5]
data = json.load(open(ir_path))
with open(recipe_path, 'rb') as f:
    recipe = tomllib.load(f)

# ── recipe roles: package -> (role, detail) ──────────────────────────────────
roles = {}
for e in recipe.get('entry', []):
    lib = e.get('lib', '?')
    crawl = e.get('crawl', True)
    roles[e['package']] = ('bound-lib' if crawl else 'policy-holder', lib if crawl else f"{lib} ({e.get('policy','?')})")
for pkg, dep in recipe.get('dependencies', {}).items():
    roles.setdefault(pkg, ('dependency', dep.get('policy', '?')))

# ── IR inventory (per-package export counts via FQN provenance) ──────────────
def provenance(fqn):
    if not isinstance(fqn, list) or not fqn:
        return None
    part = next((p for p in fqn if isinstance(p, str) and 'node_modules' in p), None)
    if part is None:
        part = fqn[0] if fqn and isinstance(fqn[0], str) else None
    if not isinstance(part, str):
        return None
    s = part.strip('"')
    m = re.search(r'node_modules/((?:@[^/]+/)?[^/]+)', s)
    return m.group(1) if m else '<entry/global>'

entry_exports = data.get("EntryExports") or {}

# PRIMARY attribution: EntryExports (entry file -> owning package -> its export keys).
# FALLBACK: FQN provenance, for declarations reached transitively (dependencies).
def entry_package(file):
    m = re.search(r'node_modules/((?:@[^/]+/)?[^/]+)', file)
    return m.group(1) if m else '<local-entry>'

pkg_exports = defaultdict(int)
attributed_keys = set()
for file, keys in entry_exports.items():
    pkg_exports[entry_package(file)] += len(keys)
    attributed_keys.update(keys)

def walk(o):
    if isinstance(o, dict):
        if "FullyQualifiedName" in o and "Name" in o:
            pkg = provenance(o["FullyQualifiedName"])
            if pkg: pkg_exports[pkg] += 1
        for v in o.values(): walk(v)
    elif isinstance(o, list):
        for v in o: walk(v)
# ExportedDeclarations is a Map encoded as {key: decl}; walk only entries whose key
# is NOT already attributed to an entry package.
exported = data.get("ExportedDeclarations") or {}
if isinstance(exported, dict):
    for key, decl in exported.items():
        try: k = int(key)
        except ValueError: k = key
        if k not in attributed_keys:
            walk(decl)
else:
    walk(exported)

total_types = len(data.get("Types", []))
ir_sha = hashlib.sha256(open(ir_path,'rb').read()).hexdigest()[:12]

# ── L0 gate: reached packages without a declared role ────────────────────────
reached = {p for p in pkg_exports if not p.startswith('<')}
missing = sorted(p for p in reached if p not in roles)

# ── coverage counts (owner parity rule): test cases per module ───────────────
def count(pattern, path):
    r = subprocess.run(['grep','-rc','--include=*.fs',pattern,path], capture_output=True, text=True)
    return {l.rsplit(':',1)[0].split('/')[-1]: int(l.rsplit(':',1)[1]) for l in r.stdout.splitlines() if int(l.rsplit(':',1)[1] or 0) > 0}
coverage = {}
for suite in ['tests/Xantham.Fable.Tests','tests/Xantham.Decoder.Tests','tests/Xantham.Generator.Tests']:
    coverage[suite.split('/')[-1]] = count('testCase', f'{repo}/{suite}')

# ── emit STATUS.md ───────────────────────────────────────────────────────────
lines = []
w = lines.append
w(f"# Xantham Status — GENERATED by scripts/status-report.sh ({date.today().isoformat()})")
w("")
w(f"*Do not edit by hand. IR: `{ir_path.replace(repo+'/','')}` (sha256 {ir_sha}, {total_types} types, {len(entry_exports)} crawl roots). Goals: [GOALS.md](GOALS.md). Steps: [PLAN.md](PLAN.md).*")
w("")
w("## L0 — declared surface (per package)")
w("")
w("| package | exports in IR | role | detail |")
w("|---|---:|---|---|")
for pkg, n in sorted(pkg_exports.items(), key=lambda kv: -kv[1]):
    role, detail = roles.get(pkg, ('**MISSING-POLICY**', '—')) if not pkg.startswith('<') else ('entry/ambient', '—')
    w(f"| {pkg} | {n} | {role} | {detail} |")
for pkg, (role, detail) in sorted(roles.items()):
    if pkg not in pkg_exports:
        w(f"| {pkg} | 0 | {role} | {detail} (declared, not reached) |")
w("")
w(f"**L0 gate: {len(missing)} reached package(s) without declared policy.**" + (f" Missing: {', '.join(missing)}" if missing else " PASS."))
w("")
w("## Per-entry provenance (crawl roots)")
w("")
w("| entry (node_modules-relative) | top-level exports |")
w("|---|---:|")
for file, keys in sorted(entry_exports.items(), key=lambda kv: -len(kv[1])):
    rel = re.search(r'node_modules/(.+)$', file)
    w(f"| {rel.group(1) if rel else file} | {len(keys)} |")
w("")
w("## L1 — raw binding (whole-artifact until Phase 1 partitions)")
w("")
w("Per-unit L1 signal: `partition-gate.sh` (own-file error counts per unit, baselines in `partition-gate.baseline`). Whole-surface signals over the SAME units: `ir-sentinel.sh` (IR identity), `arity-gate.sh` (decl/ref arity), `golden-gate.sh` (semantic budgets + determinism). The monolith and its Fable-transpile conformance gate retired 2026-07-03; Fable conformance returns as consumption (HelloWorker, Phase 2).")
w("")
w("## Coverage (test cases per module — parity rule in PLAN.md)")
w("")
w("| suite | module | test cases |")
w("|---|---|---:|")
for suite, mods in coverage.items():
    for mod, n in sorted(mods.items(), key=lambda kv: -kv[1]):
        w(f"| {suite} | {mod} | {n} |")
    w(f"| **{suite}** | **total** | **{sum(mods.values())}** |")
w("")
w("## L2 / L3")
w("")
w("L2 (conventions layer): not started — fragments welded into L1 renderer (Phase 3). L3 (consumption proof): not started — first signal is HelloWorker under miniflare (Phase 2).")
open(out_path, 'w').write('\n'.join(lines) + '\n')
print(f"wrote {out_path}")
print(f"L0 gate: {len(missing)} missing-policy package(s)" + (f": {', '.join(missing)}" if missing else " — PASS"))
sys.exit(1 if missing else 0)
PY
