// <auto-generated>
//   Generated by Xantham.Generator from absence-alphabet-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec AbsenceAlphabetLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Interface>]
type Absence =
    /// <summary>
    /// <c>x?: T</c>. The <c>?</c> marker alone.
    /// </summary>
    abstract optionalOnly: string option with get, set
    /// <summary>
    /// <c>x: T | undefined</c>. Required, and the type admits <c>undefined</c>.
    /// </summary>
    abstract unionUndefined: string option with get, set
    /// <summary>
    /// <c>x: T | null</c>. Required, and the type admits <c>null</c> - the KV <c>get</c> miss.
    /// </summary>
    abstract unionNull: string option with get, set
    /// <summary>
    /// <c>x?: T | null</c>. Both facts on one member.
    /// </summary>
    abstract optionalNull: string option with get, set
    /// <summary>
    /// <c>x: T | null | undefined</c>. Both spellings in the union, and no <c>?</c> marker.
    /// </summary>
    abstract unionBoth: string option with get, set
    /// <summary>
    /// A <c>void</c>-returning method. <c>void</c> sits in a return position, not in a union.
    /// </summary>
    abstract returnsVoid: unit -> unit
    /// <summary>
    /// <c>x: null</c>. A bare absence rather than a union, so it widens to <c>obj</c> and TR033
    /// stays silent. The negative for the two members below.
    /// </summary>
    abstract onlyNull: obj with get, set
    /// <summary>
    /// <c>x: null | undefined</c>. Two absences, and nothing remains beside them.
    /// </summary>
    abstract onlyNullUndefined: unit
    /// <summary>
    /// <c>x: void | null</c>. <c>void</c> in a union, with nothing remaining.
    /// </summary>
    abstract onlyVoidNull: unit
    [<ParamObject; Emit("$0")>]
    static member Create (returnsVoid: Action, onlyNull: obj, ?optionalOnly: string, ?unionUndefined: string, ?unionNull: string, ?optionalNull: string, ?unionBoth: string) : Absence = jsNative

[<Interface>]
type Present =
    /// <summary>
    /// Required and non-nullable.
    /// </summary>
    abstract always: string with get, set
    /// <summary>
    /// A method returning a required value.
    /// </summary>
    abstract read: unit -> string
    [<ParamObject; Emit("$0")>]
    static member Create (always: string, read: Func<string>) : Present = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A <c>void</c> return on a bare exported function.
    /// </summary>
    [<Import("fireAndForget", "absence-alphabet-lab")>]
    static member fireAndForget (topic: string) : unit = jsNative
    /// <summary>
    /// A <c>null</c> return: the KV miss, at a call boundary.
    /// </summary>
    [<Import("getOrNull", "absence-alphabet-lab")>]
    static member getOrNull (key: string) : string option = jsNative
    /// <summary>
    /// An <c>undefined</c> return: the Durable Object storage miss.
    /// </summary>
    [<Import("getOrUndefined", "absence-alphabet-lab")>]
    static member getOrUndefined (key: string) : string option = jsNative
    /// <summary>
    /// An optional parameter - the <c>?</c> fact at a parameter position.
    /// </summary>
    [<Import("withOptional", "absence-alphabet-lab")>]
    static member withOptional (key: string, ?fallback: string) : string = jsNative
    /// <summary>
    /// A parameter typed <c>T | null</c> - required, and the type admits <c>null</c>.
    /// </summary>
    [<Import("withNullable", "absence-alphabet-lab")>]
    static member withNullable (key: string, ?fallback: string) : string = jsNative
    /// <summary>
    /// A union carrying <c>void</c> beside a real member, so the third flag has a live site.
    /// </summary>
    [<Import("voidOrValue", "absence-alphabet-lab")>]
    static member voidOrValue (key: string) : string option = jsNative
