// <auto-generated>
//   Generated by Xantham.Generator from ctor-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CtorLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// The instance side, written as an interface, of the <c>declare const</c> spelling.
/// The <c>interface</c> + <c>declare const</c> spelling of a class - the shape every DOM class has in
/// <c>lib.dom.d.ts</c>. The checker calls this anonymous object <c>__type</c>, so its name has to come
/// from somewhere else: here, from the export it is the value of. <c>prototype</c> is the instance
/// side, which is a declaration of its own and must not be repeated as a member.
/// </summary>
[<Interface>]
type Widget =
    abstract label: string
    abstract resize: by: float -> Widget
    [<ParamObject; Emit("$0")>]
    static member Create (label: string, resize: (float -> Widget)) : Widget = jsNative

type WidgetConstructor =
    /// <summary>
    /// A property of the constructor object is a static of the class.
    /// </summary>
    abstract DEFAULT_LABEL: string
    [<EmitConstructor>]
    abstract Create: label: string -> Widget

/// <summary>
/// The <c>declare class</c> spelling. Its static side is reached only through <c>typeof Gauge</c> below.
/// </summary>
[<Interface>]
type Gauge =
    abstract size: float
    [<ParamObject; Emit("$0")>]
    static member Create (size: float) : Gauge = jsNative
    [<Import("Gauge.UNIT", "ctor-lab")>]
    static member UNIT: string = jsNative

type GaugeConstructor =
    abstract UNIT: string
    [<EmitConstructor>]
    abstract Create: size: float -> Gauge

/// <summary>
/// <c>typeof Gauge</c> at a member position - the construct the whole <c>ServiceWorkerGlobalScope</c>
/// constructor table is made of.
/// </summary>
[<Interface>]
type Scope =
    abstract Gauge: GaugeConstructor
    [<ParamObject; Emit("$0")>]
    static member Create (Gauge: GaugeConstructor) : Scope = jsNative

/// <summary>
/// An interface whose only members are construct signatures, generic and overloaded. Without a
/// mapping for them it has nothing to declare and abbreviates to <c>obj</c>.
/// </summary>
type ParcelFactory =
    [<EmitConstructor>]
    abstract Create<'T>: value: 'T -> Parcel<'T>
    [<EmitConstructor>]
    abstract Create: unit -> Parcel<string>

[<Interface>]
type Parcel<'T> =
    abstract value: 'T
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T) : Parcel<'T> = jsNative

/// <summary>
/// A negative: a class no <c>typeof</c> ever names. Its static side is <c>shape-classes</c>'s work, and
/// a second interface for it would be referenced by nothing.
/// </summary>
[<Interface>]
type Solo =
    abstract tag: unit -> string
    [<ParamObject; Emit("$0")>]
    static member Create (tag: (unit -> string)) : Solo = jsNative

/// <summary>
/// A negative: <c>typeof</c> over a plain value is that value's type, not a constructor object.
/// </summary>
[<Interface>]
type Meta =
    abstract version: string
    [<ParamObject; Emit("$0")>]
    static member Create (version: string) : Meta = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// The instance side, written as an interface, of the <c>declare const</c> spelling.
    /// The <c>interface</c> + <c>declare const</c> spelling of a class - the shape every DOM class has in
    /// <c>lib.dom.d.ts</c>. The checker calls this anonymous object <c>__type</c>, so its name has to come
    /// from somewhere else: here, from the export it is the value of. <c>prototype</c> is the instance
    /// side, which is a declaration of its own and must not be repeated as a member.
    /// </summary>
    [<Import("Widget", "ctor-lab")>]
    static member Widget: WidgetConstructor = jsNative
    /// <summary>
    /// The <c>declare class</c> spelling. Its static side is reached only through <c>typeof Gauge</c> below.
    /// </summary>
    [<Import("Gauge", "ctor-lab"); EmitConstructor>]
    static member Gauge (size: float) : Gauge = jsNative
    [<Import("scope", "ctor-lab")>]
    static member scope: Scope = jsNative
    [<Import("parcels", "ctor-lab")>]
    static member parcels: ParcelFactory = jsNative
    /// <summary>
    /// A negative: a class no <c>typeof</c> ever names. Its static side is <c>shape-classes</c>'s work, and
    /// a second interface for it would be referenced by nothing.
    /// </summary>
    [<Import("Solo", "ctor-lab"); EmitConstructor>]
    static member Solo () : Solo = jsNative
    [<Import("VERSION", "ctor-lab")>]
    static member VERSION: string = jsNative
