// <auto-generated>
//   Generated by Xantham.Generator from conditional-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec ConditionalLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Interface>]
type Marker =
    abstract id: string
    [<ParamObject; Emit("$0")>]
    static member Create (id: string) : Marker = jsNative

[<Interface>]
type Tagged =
    inherit Marker
    abstract tag: string
    abstract id: string
    [<ParamObject; Emit("$0")>]
    static member Create (tag: string, id: string) : Tagged = jsNative

type Proven<'T when 'T :> Tagged> = 'T

type Inhabited<'T> = 'T

[<Erase>]
type Divergent<'T> = private Divergent__ of obj

[<Erase>]
type OrUndefined<'T> = private OrUndefined__ of obj

type Decided = float

[<Interface>]
type Box<'T> =
    abstract value: 'T with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: 'T) : Box<'T> = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("proven", "conditional-lab")>]
    static member proven<'T when 'T :> Tagged> (value: 'T) : unit = jsNative
    [<Import("inhabited", "conditional-lab")>]
    static member inhabited<'T> (value: 'T) : unit = jsNative
    [<Import("divergent", "conditional-lab")>]
    static member divergent (value: obj) : unit = jsNative
