// <auto-generated>
//   Generated by Xantham.Generator from layout-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec LayoutLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type LayoutPayload =
    abstract value: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (value: string) : LayoutPayload = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
[<Global("globalThis")>]
type Exports =
    static member sharedFlag
        with get (): bool = jsNative
        and set (_: bool): unit = jsNative
    [<Import("check", "layout-lab")>]
    static member check (value: string) : string = jsNative
    [<Import("renamedCheck", "layout-lab/aliases")>]
    static member renamedCheck (value: string) : string = jsNative
    [<Import("mode", "layout-lab")>]
    static member mode: string = jsNative
    [<Import("echo", "layout-lab")>]
    static member echo (value: LayoutPayload) : LayoutPayload = jsNative
    [<Import("convert", "layout-lab")>]
    static member convert (value: string) : string = jsNative
    [<Import("convert", "layout-lab")>]
    static member convert (value: float) : float = jsNative
    [<Import("pick", "layout-lab")>]
    static member pick (value: string) : string = jsNative
    [<Import("mode", "layout-lab/strict")>]
    static member mode: string = jsNative
