// <auto-generated>
//   Generated by Xantham.Generator from catalog-subpath-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CatalogSubpathLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Root =
    abstract name: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (name: string) : Root = jsNative

/// <summary>catalog-subpath-lab/chat</summary>
module Chat =
    [<Interface>]
    type LegacyOptions =
        abstract title: string with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (title: string) : LegacyOptions = jsNative

    type Options = LegacyOptions

    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        [<Import("create", "catalog-subpath-lab/chat")>]
        static member create () : Record<string, U4<Chat.Create.Result.Item, Chat.Create.Result.Item2, Chat.Create.Result.Item3, Chat.Create.Result.Item4>> = jsNative

    module Create =
        module Result =
            [<Interface>]
            type Item =
                abstract execute: (obj -> obj) option with get, set
                abstract title: string option with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (?execute: (obj -> obj), ?title: string) : Item = jsNative

            [<Interface>]
            type Item2 =
                abstract execute: (obj -> unit) option with get, set
                abstract title: string option with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (?execute: (obj -> unit), ?title: string) : Item2 = jsNative

            [<Interface>]
            type Item3 =
                abstract execute: (unit -> obj) option with get, set
                abstract title: string option with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (?execute: (unit -> obj), ?title: string) : Item3 = jsNative

            [<Interface>]
            type Item4 =
                abstract execute: (unit -> unit) option with get, set
                abstract title: string option with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (?execute: (unit -> unit), ?title: string) : Item4 = jsNative
