// <auto-generated>
//   Generated by Xantham.Generator from recursive-json-owner-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec Identity.Support.RecursiveJsonOwnerLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

module Accept =
    [<Interface>]
    type Output2 =
        abstract kind: string with get, set
        abstract text: string with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (kind: string, text: string) : Output2 = jsNative

    [<Interface>]
    type Output3 =
        abstract kind: string with get, set
        abstract result: U3<string, float, obj option[]> with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (kind: string, result: U3<string, float, obj option[]>) : Output3 = jsNative
