<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Xantham.Fable</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Misc.fs" />
        <Compile Include="Logging.fs" />
        <Compile Include="Signals.fs" />
        <Compile Include="Symbol.fs" />
        <Compile Include="Tracer.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Fable.Core" Version="5.0.0" />
        <PackageReference Include="Fable.FSharp.Logf" Version="1.2.2" />
        <PackageReference Include="Fable.Node" Version="1.6.0" />
        <PackageReference Include="FsToolkit.ErrorHandling" Version="5.2.0" />
    </ItemGroup>
</Project>
