// <auto-generated>
//   Generated by Xantham.Generator from phantom-arity-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec PhantomArityLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Erase>]
type SurplusParameter<'T, 'Reserved> = private SurplusParameter__ of ('T -> unit)

type EveryParameter<'T, 'Reserved> = ('T -> 'Reserved)

/// <summary>
/// Both aliases at a reference position.
/// </summary>
[<Interface>]
type Holder =
    abstract surplus: (string -> unit) with get, set
    abstract every: (string -> float) with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (surplus: (string -> unit), every: (string -> float)) : Holder = jsNative
