// <auto-generated>
//   Generated by Xantham.Generator from inherited-name-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec InheritedNameLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Message =
    abstract text: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (text: string) : Message = jsNative

[<Interface>]
type View =
    abstract message: View.Message with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (message: View.Message) : View = jsNative

module View =
    [<Interface>]
    type Message =
        inherit InheritedNameLab.Message
        abstract renderedId: string option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (text: string, ?renderedId: string) : Message = jsNative
