// <auto-generated>
//   Generated by Xantham.Generator from lib-reference-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec LibReferenceLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom


