// <auto-generated>
//   Generated by Xantham.Generator from recursive-groups-lab, recursive-peer-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
namespace rec RecursiveGroupsLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

module Entry =
    [<Interface>]
    type Root =
        abstract peer: RecursiveGroupsLab.RecursivePeerLab.Peer with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (peer: RecursiveGroupsLab.RecursivePeerLab.Peer) : Root = jsNative

    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        [<Import("identity", "recursive-groups-lab")>]
        static member identity (value: Root) : Root = jsNative

    module Collision =
        /// <summary>recursive-groups-lab/collision/api</summary>
        module Api =
            /// <summary>The package's value exports, each bound to its import.</summary>
            [<Erase>]
            type Exports =
                [<Import("status", "recursive-groups-lab/collision/api")>]
                static member status (value: RecursiveGroupsLab.RecursivePeerLab.Collision) : string = jsNative

module RecursivePeerLab =
    [<Interface>]
    type Collision =
        abstract label: string with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (label: string) : Collision = jsNative

    [<Interface>]
    type Peer =
        abstract root: RecursiveGroupsLab.Entry.Root with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (root: RecursiveGroupsLab.Entry.Root) : Peer = jsNative
