<!--    
This is a dummy project to make tools easier to automatically identify in the solution.
.slnx does not accept wild cards. This is a work around.
    -->
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <None Include="**/*" Exclude="bin/**/*;obj/**/*" />
    </ItemGroup>
</Project>
