// <auto-generated>
//   Generated by Xantham.Generator from union-arm-overload-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec UnionArmOverloadLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// Expands: two distinct arms, under the cap.
    /// </summary>
    [<Import("label", "union-arm-overload-lab")>]
    static member label (value: U2<string, float>) : string = jsNative
    /// <summary>
    /// Expands: two distinct arms, under the cap.
    /// </summary>
    [<Import("label", "union-arm-overload-lab")>]
    static member label (value: string) : string = jsNative
    /// <summary>
    /// Expands: two distinct arms, under the cap.
    /// </summary>
    [<Import("label", "union-arm-overload-lab")>]
    static member label (value: float) : string = jsNative
    /// <summary>
    /// Expands, and is the load-bearing case: inside the union a bare lambda has no target type to
    /// infer against, so <c>!^ (fun a b -&gt; "x")</c> is FS0002. The arm overload gives it one.
    /// </summary>
    [<Import("apply", "union-arm-overload-lab")>]
    static member apply (handler: U2<string, Apply.Handler>) : string = jsNative
    /// <summary>
    /// Expands, and is the load-bearing case: inside the union a bare lambda has no target type to
    /// infer against, so <c>!^ (fun a b -&gt; "x")</c> is FS0002. The arm overload gives it one.
    /// </summary>
    [<Import("apply", "union-arm-overload-lab")>]
    static member apply (handler: string) : string = jsNative
    /// <summary>
    /// Expands, and is the load-bearing case: inside the union a bare lambda has no target type to
    /// infer against, so <c>!^ (fun a b -&gt; "x")</c> is FS0002. The arm overload gives it one.
    /// </summary>
    [<Import("apply", "union-arm-overload-lab")>]
    static member apply (handler: Apply.Handler) : string = jsNative
    /// <summary>
    /// Not a candidate by the time the pass runs: <c>number[]</c> and <c>ReadonlyArray&lt;number&gt;</c> are one F#
    /// type, so the arms are already deduped to a single <c>float[]</c> and there is no union left. The
    /// arms-collapse guard is exercised in Shape.test.fs, on a model TypeScript cannot express.
    /// </summary>
    [<Import("collapse", "union-arm-overload-lab")>]
    static member collapse (items: float[]) : string = jsNative
    /// <summary>
    /// Declines: the second declared overload already occupies <c>(value: string)</c>, which is what
    /// expanding the first would synthesize.
    /// </summary>
    [<Import("tint", "union-arm-overload-lab")>]
    static member tint (value: U2<string, float>) : string = jsNative
    /// <summary>
    /// Declines: the second declared overload already occupies <c>(value: string)</c>, which is what
    /// expanding the first would synthesize.
    /// </summary>
    [<Import("tint", "union-arm-overload-lab")>]
    static member tint (value: string) : string = jsNative
    /// <summary>
    /// Declines: five arms against a cap of four.
    /// </summary>
    [<Import("wide", "union-arm-overload-lab")>]
    static member wide (value: U5<string, float, bool, string[], float[]>) : string = jsNative
    /// <summary>
    /// Not a candidate: two union parameters is what <c>policy: "linear"</c> is for.
    /// </summary>
    [<Import("pair", "union-arm-overload-lab")>]
    static member pair (left: U2<string, float>, right: U2<string, bool>) : string = jsNative
    /// <summary>
    /// Not a candidate: an optional union parameter.
    /// </summary>
    [<Import("maybe", "union-arm-overload-lab")>]
    static member maybe (?value: U2<string, float>) : string = jsNative

module Apply =
    type Handler = delegate of a: float * b: float -> string
