// <auto-generated>
//   Generated by Xantham.Generator from projection-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec ProjectionLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

type Choice = U2<float, string> option

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type EqualA =
    | [<CompiledName("auto")>] Auto
    | [<CompiledName("manual")>] Manual

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type EqualB =
    | [<CompiledName("auto")>] Auto
    | [<CompiledName("manual")>] Manual

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type OverlapC =
    | [<CompiledName("auto")>] Auto
    | [<CompiledName("off")>] Off

type Weird = U2<float, string> option

[<Interface>]
type TextContent =
    abstract ``type``: string with get, set
    abstract text: string with get, set
    abstract textSignature: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, text: string, ?textSignature: string) : TextContent = jsNative

[<Interface>]
type ImageContent =
    abstract ``type``: string with get, set
    abstract data: string with get, set
    abstract mimeType: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, data: string, mimeType: string) : ImageContent = jsNative

type Input = U2<string, Input.Item[]>

[<Interface>]
type Session =
    abstract id: string
    abstract submit: input: Input * ?options: Session.Submit.Options -> Input
    abstract configure: change: Session.Configure.Change * context: string -> Choice
    abstract inspect: input: Session.Inspect.Input -> string
    [<ParamObject; Emit("$0")>]
    static member Create (id: string, submit: Func<Input, Session.Submit.Options option, Input>, configure: Func<Session.Configure.Change, string, Choice>, inspect: (Session.Inspect.Input -> string)) : Session = jsNative

[<Interface>]
type OtherSession =
    abstract submit: input: float * ?options: OtherSession.Submit.Options -> float
    [<ParamObject; Emit("$0")>]
    static member Create (submit: Func<float, OtherSession.Submit.Options option, float>) : OtherSession = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("echo", "projection-lab")>]
    static member echo (value: Choice) : Choice = jsNative
    [<Import("session", "projection-lab")>]
    static member session () : Session = jsNative

module Input =
    [<RequireQualifiedAccess; TypeScriptTaggedUnion("type", CaseRules.None)>]
    type Item =
        | [<CompiledName("image")>] Image of data: string * mimeType: string
        | [<CompiledName("text")>] Text of text: string * textSignature: string option

module OtherSession =
    module Submit =
        [<Interface>]
        type Options =
            abstract whenBusy: Session.Submit.Options.WhenBusy option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?whenBusy: Session.Submit.Options.WhenBusy) : Options = jsNative

module Session =
    module Configure =
        [<Interface>]
        type Change =
            abstract thinkingLevel: Choice option with get, set
            abstract note: string option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?thinkingLevel: Choice, ?note: string) : Change = jsNative

    module Inspect =
        [<Interface>]
        type Input =
            abstract __proto__: string with get, set
            abstract ``constructor``: string with get, set
            abstract optional: string option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (__proto__: string, ``constructor``: string, ?optional: string) : Input = jsNative

    module Submit =
        [<Interface>]
        type Options =
            abstract whenBusy: Session.Submit.Options.WhenBusy option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?whenBusy: Session.Submit.Options.WhenBusy) : Options = jsNative

        module Options =
            [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
            type WhenBusy =
                | [<CompiledName("followUp")>] FollowUp
                | [<CompiledName("steer")>] Steer
