// <auto-generated>
//   Generated by Xantham.Generator from projection-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec ProjectionLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

type Choice = U2<float, string> option

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type EqualA =
    | [<CompiledName("auto")>] Auto
    | [<CompiledName("manual")>] Manual

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type EqualB =
    | [<CompiledName("auto")>] Auto
    | [<CompiledName("manual")>] Manual

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type OverlapC =
    | [<CompiledName("auto")>] Auto
    | [<CompiledName("off")>] Off

type Weird = U2<float, string> option

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("echo", "projection-lab")>]
    static member echo (value: Choice) : Choice = jsNative
