// <auto-generated>
//   Generated by Xantham.Generator from dom-shadow-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec DomShadowLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS


