// <auto-generated>
//   Generated by Xantham.Generator from lib-ship-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec LibShipLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
[<Global("globalThis")>]
type Exports =
    static member ActiveXObject
        with get (): TypeScript.Lib.Dom.ActiveXObject = jsNative
        and set (_: TypeScript.Lib.Dom.ActiveXObject): unit = jsNative
    static member WScript
        with get (): TypeScript.Lib.Dom.WScript = jsNative
        and set (_: TypeScript.Lib.Dom.WScript): unit = jsNative
    /// <summary>
    /// WSH is an alias for WScript under Windows Script Host
    /// </summary>
    static member WSH
        with get (): TypeScript.Lib.Dom.WScript = jsNative
        and set (_: TypeScript.Lib.Dom.WScript): unit = jsNative
    /// <summary>
    /// Represents an Automation SAFEARRAY
    /// </summary>
    [<Global("SafeArray"); EmitConstructor>]
    static member SafeArray<'T> () : TypeScript.Lib.Dom.SafeArray<'T> = jsNative
    /// <summary>
    /// Allows enumerating over a COM collection, which may not have indexed item access.
    /// </summary>
    static member Enumerator
        with get (): TypeScript.Lib.Dom.EnumeratorConstructor = jsNative
        and set (_: TypeScript.Lib.Dom.EnumeratorConstructor): unit = jsNative
    /// <summary>
    /// Enables reading from a COM safe array, which might have an alternate lower bound, or multiple dimensions.
    /// </summary>
    static member VBArray
        with get (): TypeScript.Lib.Dom.VBArrayConstructor = jsNative
        and set (_: TypeScript.Lib.Dom.VBArrayConstructor): unit = jsNative
    /// <summary>
    /// Automation date (VT_DATE)
    /// </summary>
    [<Global("VarDate"); EmitConstructor>]
    static member VarDate () : TypeScript.Lib.Dom.VarDate = jsNative
    [<Global("globalThis")>]
    static member globalThis: TypeScript.Lib.Es.GlobalThis = jsNative
