// <auto-generated>
//   Generated by Xantham.Generator from callable-overloads-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec CallableOverloadsLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

/// <summary>
/// Two call signatures under the same name, <c>U</c>, bound differently to <c>string</c> and to <c>number</c>,
/// and separated by arity: each reaches its own <c>Invoke</c> overload.
/// </summary>
type Coalesce =
    [<Emit("$0($1...)")>]
    abstract Invoke<'U>: value: 'U -> 'U
    [<Emit("$0($1...)")>]
    abstract Invoke<'U>: value: 'U * fallback: 'U -> 'U

[<Erase>]
type OneShot<'T, 'U> = private OneShot__ of ('U -> 'U)

type Multiplex = (float -> float)

/// <summary>
/// Negative: a member beside the call signature routes through the existing hybrid path (§4.4),
/// regardless of the call signature's own shape.
/// </summary>
[<Interface>]
type Ledger =
    abstract count: float with get, set
    [<Emit("$0($1...)")>]
    abstract Invoke: id: float -> string
    [<ParamObject; Emit("$0")>]
    static member Create (count: float) : Ledger = jsNative

/// <summary>
/// <c>Coalesce</c> at a member position: both call signatures recover as separable overloads under
/// the member's own name (§4.2 extended to callbacks), reachable through <c>holder.coalesce</c>.
/// </summary>
type Holder =
    abstract coalesce<'U>: value: 'U -> 'U
    abstract coalesce<'U>: value: 'U * fallback: 'U -> 'U

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// <c>Coalesce</c> at a tuple return position, mirroring <c>solid-js</c>'s <c>createStore</c> returning
    /// <c>[Store&lt;T&gt;, SetStoreFunction&lt;T&gt;]</c>: the reference keeps its name, and each call signature
    /// reaches its own <c>Invoke</c> overload.
    /// </summary>
    [<Import("makeCoalescer", "callable-overloads-lab")>]
    static member makeCoalescer () : string * Coalesce = jsNative
    [<Import("coalesce", "callable-overloads-lab")>]
    static member coalesce<'U> (value: 'U) : 'U = jsNative
    [<Import("coalesce", "callable-overloads-lab")>]
    static member coalesce<'U> (value: 'U, fallback: 'U) : 'U = jsNative
    [<Import("oneShot", "callable-overloads-lab")>]
    static member oneShot<'U> (value: 'U) : 'U = jsNative
    [<Import("multiplex", "callable-overloads-lab")>]
    static member multiplex (value: float) : float = jsNative
    [<Import("multiplex", "callable-overloads-lab")>]
    static member multiplex (value: float, extra: float) : float = jsNative
    [<Import("ledger", "callable-overloads-lab")>]
    static member ledger (id: float) : string = jsNative
    [<Import("holder", "callable-overloads-lab")>]
    static member holder: Holder = jsNative
