// <auto-generated>
//   Generated by Xantham.Generator from entry-selection-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec EntrySelectionLab.Adapter

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type AdapterOptions =
    abstract label: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (label: string) : AdapterOptions = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("adapterValue", "entry-selection-lab/adapter")>]
    static member adapterValue (options: AdapterOptions) : float = jsNative
