// <auto-generated>
//   Generated by Xantham.Generator from globals-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec GlobalsLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// A global type. A type reads the same wherever its name lives.
/// </summary>
[<Interface>]
type Widget =
    /// <summary>
    /// The widget's label.
    /// </summary>
    abstract label: string with get, set
    abstract size: float option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (label: string, ?size: float) : Widget = jsNative

/// <summary>
/// A global class: <c>[&lt;Global&gt;]</c> plus <c>[&lt;EmitConstructor&gt;]</c>.
/// </summary>
[<Interface>]
type Gadget =
    abstract widget: Widget
    abstract spin: turns: float -> Gadget
    [<ParamObject; Emit("$0")>]
    static member Create (widget: Widget, spin: (float -> Gadget)) : Gadget = jsNative
    /// <summary>
    /// A static on a global class: the selector is dotted off the global name, not imported.
    /// </summary>
    [<Global("Gadget.SPEED")>]
    static member SPEED: float = jsNative

/// <summary>
/// A nominal brand: the property can never hold a value, so F# gives it no setter.
/// </summary>
[<Interface>]
type Branded =
    abstract __brand: unit
    abstract id: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (id: string) : Branded = jsNative

/// <summary>
/// A generic alias whose target never mentions its parameter - F# has no such abbreviation.
/// </summary>
type Loose<'P> =
    [<EmitIndexer>]
    abstract Item: string -> string with get, set

/// <summary>
/// A user of that alias: the reference has to widen when the alias goes.
/// </summary>
[<Interface>]
type Bag =
    abstract loose: Bag.Loose with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (loose: Bag.Loose) : Bag = jsNative

module Bag =
    type Loose =
        [<EmitIndexer>]
        abstract Item: string -> string with get, set

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
[<Global("globalThis")>]
type Exports =
    /// <summary>
    /// A global value: already on <c>globalThis</c>, so it binds with <c>[&lt;Global&gt;]</c>, not <c>[&lt;Import&gt;]</c>.
    /// </summary>
    [<Global("registry")>]
    static member registry: Widget = jsNative
    /// <summary>
    /// A mutable global.
    /// </summary>
    static member counter
        with get (): float = jsNative
        and set (_: float): unit = jsNative
    /// <summary>
    /// A global function.
    /// </summary>
    [<Global("ping")>]
    static member ping (target: string, ?retries: float) : bool = jsNative
    /// <summary>
    /// A global class: <c>[&lt;Global&gt;]</c> plus <c>[&lt;EmitConstructor&gt;]</c>.
    /// </summary>
    [<Global("Gadget"); EmitConstructor>]
    static member Gadget (widget: Widget) : Gadget = jsNative
    [<Import("extra", "globals-lab:extra")>]
    static member extra: float = jsNative
