// <auto-generated>
//   Generated by Xantham.Generator from key-sanitise-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec KeySanitiseLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

/// <summary>
/// The owner of members whose JavaScript keys are not F# declaration names.
/// </summary>
[<Interface>]
type Registry =
    /// <summary>
    /// Names <c>RegistryCfMeta</c>, and the member keeps the key.
    /// </summary>
    abstract ``@cf/meta``: RegistryCfMeta with get, set
    /// <summary>
    /// Two keys reduce to two names, so the reduction separates rather than collides.
    /// </summary>
    abstract ``@cf/meta/llama-3``: RegistryCfMetaLlama3 with get, set
    /// <summary>
    /// A leading <c>$</c>, which is legal in JavaScript and not in a declaration name.
    /// </summary>
    abstract ``$ref``: RegistryRef with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``@cf/meta``: RegistryCfMeta, ``@cf/meta/llama-3``: RegistryCfMetaLlama3, ``$ref``: RegistryRef) : Registry = jsNative

[<Interface>]
type RegistryCfMeta =
    abstract model: string with get, set
    /// <summary>
    /// The sanitised name opens a module of its own: <c>RegistryCfMeta.Limits</c>.
    /// </summary>
    abstract limits: RegistryCfMeta.Limits with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (model: string, limits: RegistryCfMeta.Limits) : RegistryCfMeta = jsNative

module RegistryCfMeta =
    [<Interface>]
    type Limits =
        abstract tokens: float with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (tokens: float) : Limits = jsNative

[<Interface>]
type RegistryCfMetaLlama3 =
    abstract model: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (model: string) : RegistryCfMetaLlama3 = jsNative

[<Interface>]
type RegistryRef =
    abstract target: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (target: string) : RegistryRef = jsNative

/// <summary>
/// The owner of keys that need no reduction.
/// </summary>
[<Interface>]
type Settings =
    /// <summary>
    /// Not nestable - it opens with a digit - but <c>Settings2fa</c> is a legal name, so it stands.
    /// </summary>
    abstract ``2fa``: Settings2fa with get, set
    /// <summary>
    /// Identifier-shaped, so it opens <c>Settings.Timeouts</c> the way any member key does.
    /// </summary>
    abstract timeouts: Settings.Timeouts with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``2fa``: Settings2fa, timeouts: Settings.Timeouts) : Settings = jsNative

module Settings =
    [<Interface>]
    type Timeouts =
        abstract connectMs: float with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (connectMs: float) : Timeouts = jsNative

[<Interface>]
type Settings2fa =
    abstract enabled: bool with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (enabled: bool) : Settings2fa = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// Reads the sanitised shape back, so the reference position is gated too.
    /// </summary>
    [<Import("modelOf", "key-sanitise-lab")>]
    static member modelOf (entry: RegistryCfMeta) : string = jsNative
