// <auto-generated>
//   Generated by Xantham.Generator from augmented-dom-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec AugmentedDomLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Request<'T> =
    /// <summary>
    /// The <b><c>cache</c></b> read-only property of the Request interface contains the cache mode of the request. It controls how the request will interact with the browser's HTTP cache.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/cache">MDN Reference</a>
    /// </summary>
    abstract cache: Request.Cache
    /// <summary>
    /// The <b><c>credentials</c></b> read-only property of the Request interface reflects the value given to the Request() constructor in the credentials option. It determines whether or not the browser sends credentials with the request, as well as whether any Set-Cookie response headers are respected.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/credentials">MDN Reference</a>
    /// </summary>
    abstract credentials: Request.Credentials
    /// <summary>
    /// The <b><c>destination</c></b> read-only property of the Request interface returns a string describing the type of content being requested.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/destination">MDN Reference</a>
    /// </summary>
    abstract destination: Request.Destination
    /// <summary>
    /// The <b><c>headers</c></b> read-only property of the Request interface contains the Headers object associated with the request.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/headers">MDN Reference</a>
    /// </summary>
    abstract headers: Fable.Core.TS.Dom.Headers
    /// <summary>
    /// The <b><c>integrity</c></b> read-only property of the Request interface contains the subresource integrity value of the request.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/integrity">MDN Reference</a>
    /// </summary>
    abstract integrity: string
    /// <summary>
    /// The <b><c>keepalive</c></b> read-only property of the Request interface contains the request's keepalive setting (true or false), which indicates whether the browser will keep the associated request alive if the page that initiated it is unloaded before the request is complete.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/keepalive">MDN Reference</a>
    /// </summary>
    abstract keepalive: bool
    /// <summary>
    /// The <b><c>method</c></b> read-only property of the Request interface contains the request's method (GET, POST, etc.)
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/method">MDN Reference</a>
    /// </summary>
    abstract ``method``: string
    /// <summary>
    /// The <b><c>mode</c></b> read-only property of the Request interface contains the mode of the request (e.g., cors, no-cors, same-origin, or navigate.) This is used to determine if cross-origin requests lead to valid responses, and which properties of the response are readable.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/mode">MDN Reference</a>
    /// </summary>
    abstract mode: Request.Mode
    /// <summary>
    /// The <b><c>redirect</c></b> read-only property of the Request interface contains the mode for how redirects are handled.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/redirect">MDN Reference</a>
    /// </summary>
    abstract redirect: Request.Redirect
    /// <summary>
    /// The <b><c>referrer</c></b> read-only property of the Request interface is set by the user agent to be the referrer of the Request. (e.g., client, no-referrer, or a URL.)
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/referrer">MDN Reference</a>
    /// </summary>
    abstract referrer: string
    /// <summary>
    /// The <b><c>referrerPolicy</c></b> read-only property of the Request interface returns the referrer policy, which governs what referrer information, sent in the Referer header, should be included with the request.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/referrerPolicy">MDN Reference</a>
    /// </summary>
    abstract referrerPolicy: Request.ReferrerPolicy
    /// <summary>
    /// The read-only <b><c>signal</c></b> property of the Request interface returns the AbortSignal associated with the request.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/signal">MDN Reference</a>
    /// </summary>
    abstract signal: Fable.Core.TS.Dom.AbortSignal
    /// <summary>
    /// The <b><c>url</c></b> read-only property of the Request interface contains the URL of the request.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/url">MDN Reference</a>
    /// </summary>
    abstract url: string
    /// <summary>
    /// The <b><c>clone()</c></b> method of the Request interface creates a copy of the current Request object.
    /// <br /><br />
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/clone">MDN Reference</a>
    /// </summary>
    abstract clone: unit -> Request<obj>
    abstract cf: 'T option with get, set
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/body">MDN Reference</a>
    /// </summary>
    abstract body: Fable.Core.TS.Dom.ReadableStream<JS.Uint8Array> option
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/bodyUsed">MDN Reference</a>
    /// </summary>
    abstract bodyUsed: bool
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/arrayBuffer">MDN Reference</a>
    /// </summary>
    abstract arrayBuffer: unit -> JS.Promise<JS.ArrayBuffer>
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/blob">MDN Reference</a>
    /// </summary>
    abstract blob: unit -> JS.Promise<Fable.Core.TS.Dom.Blob>
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/bytes">MDN Reference</a>
    /// </summary>
    abstract bytes: unit -> JS.Promise<JS.Uint8Array>
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/formData">MDN Reference</a>
    /// </summary>
    abstract formData: unit -> JS.Promise<Fable.Core.TS.Dom.FormData>
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/json">MDN Reference</a>
    /// </summary>
    abstract json: unit -> JS.Promise<obj>
    /// <summary>
    /// <a href="https://developer.mozilla.org/docs/Web/API/Request/text">MDN Reference</a>
    /// </summary>
    abstract text: unit -> JS.Promise<string>
    [<ParamObject; Emit("$0")>]
    static member Create (cache: Request.Cache, credentials: Request.Credentials, destination: Request.Destination, headers: Fable.Core.TS.Dom.Headers, integrity: string, keepalive: bool, ``method``: string, mode: Request.Mode, redirect: Request.Redirect, referrer: string, referrerPolicy: Request.ReferrerPolicy, signal: Fable.Core.TS.Dom.AbortSignal, url: string, clone: (unit -> Request<obj>), bodyUsed: bool, arrayBuffer: (unit -> JS.Promise<JS.ArrayBuffer>), blob: (unit -> JS.Promise<Fable.Core.TS.Dom.Blob>), bytes: (unit -> JS.Promise<JS.Uint8Array>), formData: (unit -> JS.Promise<Fable.Core.TS.Dom.FormData>), json: (unit -> JS.Promise<obj>), text: (unit -> JS.Promise<string>), ?cf: 'T, ?body: Fable.Core.TS.Dom.ReadableStream<JS.Uint8Array>) : Request<'T> = jsNative

[<Interface>]
type RequestInit<'T> =
    /// <summary>
    /// A BodyInit object or null to set request's body.
    /// </summary>
    abstract body: U7<string, JS.ArrayBuffer, JS.ArrayBufferView, Fable.Core.TS.Dom.Blob, Fable.Core.TS.Dom.FormData, Fable.Core.TS.Dom.ReadableStream<obj>, Fable.Core.TS.Dom.URLSearchParams> option with get, set
    /// <summary>
    /// A string indicating how the request will interact with the browser's cache to set request's cache.
    /// </summary>
    abstract cache: Request.Cache option with get, set
    /// <summary>
    /// A string indicating whether credentials will be sent with the request always, never, or only when sent to a same-origin URL. Sets request's credentials.
    /// </summary>
    abstract credentials: Request.Credentials option with get, set
    /// <summary>
    /// A Headers object, an object literal, or an array of two-item arrays to set request's headers.
    /// </summary>
    abstract headers: U3<(string * string)[], Fable.Core.TS.Dom.Headers, Record<string, string>> option with get, set
    /// <summary>
    /// A cryptographic hash of the resource to be fetched by request. Sets request's integrity.
    /// </summary>
    abstract integrity: string option with get, set
    /// <summary>
    /// A boolean to set request's keepalive.
    /// </summary>
    abstract keepalive: bool option with get, set
    /// <summary>
    /// A string to set request's method.
    /// </summary>
    abstract ``method``: string option with get, set
    /// <summary>
    /// A string to indicate whether the request will use CORS, or will be restricted to same-origin URLs. Sets request's mode.
    /// </summary>
    abstract mode: Request.Mode option with get, set
    abstract priority: RequestInit.Priority option with get, set
    /// <summary>
    /// A string indicating whether request follows redirects, results in an error upon encountering a redirect, or returns the redirect (in an opaque fashion). Sets request's redirect.
    /// </summary>
    abstract redirect: Request.Redirect option with get, set
    /// <summary>
    /// A string whose value is a same-origin URL, "about:client", or the empty string, to set request's referrer.
    /// </summary>
    abstract referrer: string option with get, set
    /// <summary>
    /// A referrer policy to set request's referrerPolicy.
    /// </summary>
    abstract referrerPolicy: Request.ReferrerPolicy option with get, set
    /// <summary>
    /// An AbortSignal to set request's signal.
    /// </summary>
    abstract signal: Fable.Core.TS.Dom.AbortSignal option with get, set
    /// <summary>
    /// Can only be null. Used to disassociate request from any Window.
    /// </summary>
    abstract window: unit option with get, set
    abstract cf: 'T option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?body: U7<string, JS.ArrayBuffer, JS.ArrayBufferView, Fable.Core.TS.Dom.Blob, Fable.Core.TS.Dom.FormData, Fable.Core.TS.Dom.ReadableStream<obj>, Fable.Core.TS.Dom.URLSearchParams>, ?cache: Request.Cache, ?credentials: Request.Credentials, ?headers: U3<(string * string)[], Fable.Core.TS.Dom.Headers, Record<string, string>>, ?integrity: string, ?keepalive: bool, ?``method``: string, ?mode: Request.Mode, ?priority: RequestInit.Priority, ?redirect: Request.Redirect, ?referrer: string, ?referrerPolicy: Request.ReferrerPolicy, ?signal: Fable.Core.TS.Dom.AbortSignal, ?window: unit, ?cf: 'T) : RequestInit<'T> = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("request", "augmented-dom-lab")>]
    static member request (value: Request<Request.Value.Item>, init: RequestInit<Request.Init.Item>) : Func<U3<string, Request<obj>, Fable.Core.TS.Dom.URL>, RequestInit<obj> option, JS.Promise<Fable.Core.TS.Dom.Response>> = jsNative
    [<Import("plain", "augmented-dom-lab")>]
    static member plain () : Fable.Core.TS.Dom.Response = jsNative

module Request =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Cache =
        | [<CompiledName("default")>] Default
        | [<CompiledName("force-cache")>] ForceCache
        | [<CompiledName("no-cache")>] NoCache
        | [<CompiledName("no-store")>] NoStore
        | [<CompiledName("only-if-cached")>] OnlyIfCached
        | [<CompiledName("reload")>] Reload

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Credentials =
        | [<CompiledName("include")>] Include
        | [<CompiledName("omit")>] Omit
        | [<CompiledName("same-origin")>] SameOrigin

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Destination =
        | [<CompiledName("")>] Empty
        | [<CompiledName("audio")>] Audio
        | [<CompiledName("audioworklet")>] Audioworklet
        | [<CompiledName("document")>] Document
        | [<CompiledName("embed")>] Embed
        | [<CompiledName("font")>] Font
        | [<CompiledName("frame")>] Frame
        | [<CompiledName("iframe")>] Iframe
        | [<CompiledName("image")>] Image
        | [<CompiledName("manifest")>] Manifest
        | [<CompiledName("object")>] Object
        | [<CompiledName("paintworklet")>] Paintworklet
        | [<CompiledName("report")>] Report
        | [<CompiledName("script")>] Script
        | [<CompiledName("sharedworker")>] Sharedworker
        | [<CompiledName("style")>] Style
        | [<CompiledName("track")>] Track
        | [<CompiledName("video")>] Video
        | [<CompiledName("worker")>] Worker
        | [<CompiledName("xslt")>] Xslt

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Mode =
        | [<CompiledName("cors")>] Cors
        | [<CompiledName("navigate")>] Navigate
        | [<CompiledName("no-cors")>] NoCors
        | [<CompiledName("same-origin")>] SameOrigin

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Redirect =
        | [<CompiledName("error")>] Error
        | [<CompiledName("follow")>] Follow
        | [<CompiledName("manual")>] Manual

    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type ReferrerPolicy =
        | [<CompiledName("")>] Empty
        | [<CompiledName("no-referrer")>] NoReferrer
        | [<CompiledName("no-referrer-when-downgrade")>] NoReferrerWhenDowngrade
        | [<CompiledName("origin")>] Origin
        | [<CompiledName("origin-when-cross-origin")>] OriginWhenCrossOrigin
        | [<CompiledName("same-origin")>] SameOrigin
        | [<CompiledName("strict-origin")>] StrictOrigin
        | [<CompiledName("strict-origin-when-cross-origin")>] StrictOriginWhenCrossOrigin
        | [<CompiledName("unsafe-url")>] UnsafeUrl

    module Init =
        [<Interface>]
        type Item =
            abstract bar: string with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (bar: string) : Item = jsNative

    module Value =
        [<Interface>]
        type Item =
            abstract foo: string with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (foo: string) : Item = jsNative

module RequestInit =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Priority =
        | [<CompiledName("auto")>] Auto
        | [<CompiledName("high")>] High
        | [<CompiledName("low")>] Low
