// <auto-generated>
//   Generated by Xantham.Generator from chain-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec ChainLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Xantham.Fable.Core

[<Interface>]
type NodeExtensions<'TNodeType> =
    abstract toVar: Func<string option, VarNode<'TNodeType, NodeExtensions<'TNodeType>>> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (toVar: Func<string option, VarNode<'TNodeType, NodeExtensions<'TNodeType>>>) : NodeExtensions<'TNodeType> = jsNative

[<Interface>]
type Node<'TNodeType> =
    inherit NodeExtensions<'TNodeType>
    abstract isNode: bool
    abstract toVar: Func<string option, VarNode<'TNodeType, Node<'TNodeType>>> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (isNode: bool, toVar: Func<string option, VarNode<'TNodeType, Node<'TNodeType>>>) : Node<'TNodeType> = jsNative

[<Interface>]
type VarNodeInterface<'TNode> =
    abstract node: 'TNode with get, set
    abstract isVarNode: bool
    [<ParamObject; Emit("$0")>]
    static member Create (node: 'TNode, isVarNode: bool) : VarNodeInterface<'TNode> = jsNative

[<Interface>]
type VarNode<'TNodeType, 'TNode> =
    inherit NodeExtensions<'TNodeType>
    inherit VarNodeInterface<'TNode>
    abstract isNode: bool
    abstract toVar: Func<string option, VarNode<'TNodeType, VarNode<'TNodeType, 'TNode>>> with get, set
    abstract node: 'TNode with get, set
    abstract isVarNode: bool
    [<ParamObject; Emit("$0")>]
    static member Create (isNode: bool, toVar: Func<string option, VarNode<'TNodeType, VarNode<'TNodeType, 'TNode>>>, node: 'TNode, isVarNode: bool) : VarNode<'TNodeType, 'TNode> = jsNative

type Plain<'TValue> =
    abstract wrap: value: 'TValue -> VarNodeInterface<'TValue>
    abstract self: unit -> Plain<'TValue>

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("seed", "chain-lab")>]
    static member seed: Node<float> = jsNative
