// <auto-generated>
//   Generated by Xantham.Generator from keyof-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec KeyofLab

open System
open Fable.Core
open Fable.Core.JsInterop

/// <summary>
/// The operand every keyof in this fixture is taken over.
/// </summary>
[<Interface>]
type Options =
    /// <summary>
    /// How long, in milliseconds.
    /// </summary>
    abstract duration: float with get, set
    /// <summary>
    /// What to call it.
    /// </summary>
    abstract label: string with get, set
    /// <summary>
    /// Whether to loop.
    /// </summary>
    abstract loop: bool with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (duration: float, label: string, loop: bool) : Options = jsNative

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type OptionKey =
    | [<CompiledName("duration")>] Duration
    | [<CompiledName("label")>] Label
    | [<CompiledName("loop")>] Loop

/// <summary>
/// Concrete indexed access - the checker resolves this to `number`.
/// </summary>
type Duration = float

/// <summary>
/// Concrete indexed access over a union of keys - resolves to `number | string`.
/// </summary>
type DurationOrLabel = U2<string, float>

/// <summary>
/// A closed keyof in member position.
/// </summary>
[<Interface>]
type Selection =
    abstract key: OptionKey with get, set
    abstract value: U3<string, float, bool> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (key: OptionKey, value: U3<string, float, bool>) : Selection = jsNative

/// <summary>
/// A generic accessor carried as a member rather than a function.
/// </summary>
type Accessor<'T> =
    abstract read: key: obj -> obj
    abstract all: unit -> obj[]

/// <summary>
/// A string index signature.
/// </summary>
type Bag =
    [<EmitIndexer>]
    abstract Item: string -> float with get, set

/// <summary>
/// A numeric index signature.
/// </summary>
type Slots =
    [<EmitIndexer>]
    abstract Item: float -> string with get, set

/// <summary>
/// `Record` over concrete operands.
/// </summary>
type Registry =
    [<EmitIndexer>]
    abstract Item: string -> float with get, set

/// <summary>
/// A readonly string index signature.
/// </summary>
type FrozenBag =
    [<EmitIndexer>]
    abstract Item: string -> string

/// <summary>
/// A mapped type over a concrete operand - the checker expands it (D6).
/// </summary>
[<Interface>]
type PartialOptions =
    /// <summary>
    /// How long, in milliseconds.
    /// </summary>
    abstract duration: float option with get, set
    /// <summary>
    /// What to call it.
    /// </summary>
    abstract label: string option with get, set
    /// <summary>
    /// Whether to loop.
    /// </summary>
    abstract loop: bool option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?duration: float, ?label: string, ?loop: bool) : PartialOptions = jsNative

/// <summary>
/// Another concrete expansion, over a chosen key set.
/// </summary>
[<Interface>]
type OptionsHead =
    /// <summary>
    /// How long, in milliseconds.
    /// </summary>
    abstract duration: float with get, set
    /// <summary>
    /// What to call it.
    /// </summary>
    abstract label: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (duration: float, label: string) : OptionsHead = jsNative

/// <summary>
/// A concrete omission.
/// </summary>
[<Interface>]
type OptionsTail =
    /// <summary>
    /// What to call it.
    /// </summary>
    abstract label: string with get, set
    /// <summary>
    /// Whether to loop.
    /// </summary>
    abstract loop: bool with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (label: string, loop: bool) : OptionsTail = jsNative

/// <summary>
/// Readonly over a concrete operand.
/// </summary>
[<Interface>]
type FrozenOptions =
    /// <summary>
    /// How long, in milliseconds.
    /// </summary>
    abstract duration: float
    /// <summary>
    /// What to call it.
    /// </summary>
    abstract label: string
    /// <summary>
    /// Whether to loop.
    /// </summary>
    abstract loop: bool
    [<ParamObject; Emit("$0")>]
    static member Create (duration: float, label: string, loop: bool) : FrozenOptions = jsNative

/// <summary>
/// A conditional over a concrete operand - already resolved by the checker.
/// </summary>
type ConcreteBranch = string

/// <summary>
/// A conditional in a generic signature - unresolved.
/// </summary>
type Unwrap = obj

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type EventName =
    | [<CompiledName("onEnd")>] OnEnd
    | [<CompiledName("onStart")>] OnStart

/// <summary>
/// A template literal in a generic signature - unresolved.
/// </summary>
type Prefixed = obj

/// <summary>
/// Uppercase over a concrete operand: an intrinsic string mapping.
/// </summary>
type ShoutedKey = string

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// A closed keyof in parameter and return position.
    /// </summary>
    [<Import("pick", "keyof-lab")>]
    static member pick (key: OptionKey) : U3<string, float, bool> = jsNative
    /// <summary>
    /// `K extends keyof T` plus `T[K]` - the canonical typed accessor.
    /// </summary>
    [<Import("get", "keyof-lab")>]
    static member get (source: obj, key: obj) : obj = jsNative
    /// <summary>
    /// A bare `keyof T` parameter over an unresolved operand.
    /// </summary>
    [<Import("keys", "keyof-lab")>]
    static member keys (source: obj) : obj[] = jsNative
    /// <summary>
    /// `T[keyof T]` - the value-of idiom.
    /// </summary>
    [<Import("values", "keyof-lab")>]
    static member values (source: obj) : obj[] = jsNative
