module internal Xantham.Generator.Customization.Output

open System
open System.Text.Json
open Xantham.Generator

let private name (text: string) =
    if String.IsNullOrWhiteSpace text || text.Split('.') |> Array.exists (fun part -> not (System.Text.RegularExpressions.Regex.IsMatch(part, "^[A-Za-z_][A-Za-z0-9_]*$"))) then
        invalidOp $"customization/invalid-name: {text}"
    text

let rec private variables = function
    | FsTypeVar variable -> [variable]
    | FsOption inner | FsArray inner | FsBranded(inner, _) -> variables inner
    | FsTuple values | FsErasedUnion values | FsApp(_, values) -> List.collect variables values
    | FsFunc(a,b) -> variables a @ variables b
    | FsDelegate(args, result) -> List.collect variables (args @ [result])
    | _ -> []

let render foreign snapshot specs =
    specs |> List.map (fun spec ->
        let ns, marker, source, members, bases, mode = ContractData.companionInfo spec
        let ns, marker = name ns, name marker
        if marker.Contains '.' then invalidOp "customization/invalid-marker: marker must be one identifier"
        let properties = members |> List.map (fun m -> ContractData.memberInfo m snapshot) |> List.distinctBy _.Name
        let receiver = ContractData.typeInfo source snapshot
        if properties |> List.exists (fun p -> p.Receiver <> receiver.Key) then
            invalidOp $"customization/foreign-property: {ns}.{marker}"
        let refs = (properties |> List.map _.Type) @ (bases |> List.map ContractData.typeRef)
        let parameters = refs |> List.collect variables |> List.distinct
        let head = if parameters.IsEmpty then marker else marker + "<" + (parameters |> List.map (fun p -> "'" + Naming.typeVariable p) |> String.concat ", ") + ">"
        let propertyType (property: SemanticMemberInfo) = property.Type |> Render.qualifyType foreign |> Render.printType
        let getter (property: SemanticMemberInfo) = "$0[" + JsonSerializer.Serialize(property.Name) + "]"
        let lines = [
            yield "// <auto-generated>"
            yield "// Generated by Xantham customization."
            yield "// </auto-generated>"
            yield "namespace " + ns
            yield ""
            yield "open System"
            yield "open Fable.Core"
            yield "open Fable.Core.JsInterop"
            yield "open Fable.Core.JS"
            yield "open Fable.Core.TS.Dom"
            yield ""
            yield "[<Interface>]"
            if bases.IsEmpty then yield $"type {head} = interface end"
            else
                yield $"type {head} ="
                for baseType in bases do yield "    inherit " + (ContractData.typeRef baseType |> Render.qualifyType foreign |> Render.printType)
            yield ""
            yield "[<AutoOpen>]"
            yield $"module {marker}Extensions ="
            yield $"    type {head} with"
            if properties.IsEmpty then invalidOp $"customization/empty-companion: {ns}.{marker}"
            for property in properties do
                let typ = propertyType property
                let prop = Render.ident property.Name
                if mode = "erase" then yield "        [<Erase>]"
                if property.ReadOnly then
                    if mode = "direct" then yield "        [<Emit(" + Render.stringLit (getter property) + ")>]"
                    yield $"        member _.{prop}: {typ} = jsNative"
                else
                    yield $"        member _.{prop}"
                    let getAttribute = if mode = "direct" then "[<Emit(" + Render.stringLit (getter property) + ")>] " else ""
                    let setAttribute = if mode = "direct" then "[<Emit(" + Render.stringLit (getter property + " = $1") + ")>] " else ""
                    yield $"            with {getAttribute}get (): {typ} = jsNative"
                    let body = if mode = "direct" then "jsNative" else "()"
                    yield $"            and {setAttribute}set (value: {typ}) = {body}"
                yield ""
        ]
        $"customizations/{ns}.{marker}.fs", String.concat "\n" lines + "\n")
