name: CI
on:
  push:
    branches:
      - master
    paths:
      - '**.fs'
      - 'src/**/**.fsproj'
      - '!**/*.fsx'
      - '!build.fsx'
  workflow_dispatch: 

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Run CI
        run: dotnet fsi build.fsx -- test
