// <auto-generated>
//   Generated by Xantham.Generator from indexed-callback-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec IndexedCallbackLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Erase>]
type Context<'P> = private Context__ of obj

type Handler<'E, 'P> = delegate of env: 'E * ctx: obj -> unit

type BivarianceHack<'E> = delegate of env: 'E * ctx: obj -> unit

type Handlers<'Params, 'E> =
    [<EmitIndexer>]
    abstract Item: string -> BivarianceHack<'E> option with get, set
