// <auto-generated>
//   Generated by Xantham.Generator from exclusive-arms-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec ExclusiveArmsLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS

[<Interface>]
type SeparableOptions =
    abstract shared: float with get, set
    abstract messages: string[] option with get, set
    abstract query: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (shared: float, messages: string[]) : SeparableOptions = jsNative
    [<ParamObject; Emit("$0")>]
    static member Create (shared: float, query: string) : SeparableOptions = jsNative

[<Interface>]
type AnchoredOptions =
    abstract enableInternet: bool with get, set
    abstract image: string option with get, set
    abstract snapshot: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (enableInternet: bool, image: string) : AnchoredOptions = jsNative
    [<ParamObject; Emit("$0")>]
    static member Create (enableInternet: bool, ?snapshot: string) : AnchoredOptions = jsNative

[<Interface>]
type WidgetArm =
    abstract kind: string with get, set
    abstract label: string with get, set
    abstract count: unit option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (kind: string, label: string, ?count: unit) : WidgetArm = jsNative

[<Interface>]
type GadgetArm =
    abstract kind: float with get, set
    abstract label: unit option with get, set
    abstract count: float with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (kind: float, count: float, ?label: unit) : GadgetArm = jsNative

type DisagreeingOptions = U2<GadgetArm, WidgetArm>

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("search", "exclusive-arms-lab")>]
    static member search (options: SeparableOptions) : unit = jsNative
    [<Import("start", "exclusive-arms-lab")>]
    static member start (options: AnchoredOptions) : unit = jsNative
    [<Import("build", "exclusive-arms-lab")>]
    static member build (options: DisagreeingOptions) : unit = jsNative
