// <auto-generated>
//   Generated by Xantham.Generator from primitive-argument-identity-lab.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec PrimitiveArgumentIdentityLab

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("use", "primitive-argument-identity-lab")>]
    static member ``use`` (value: Identity.Support.IntrinsicOwnerLab.Item) : Identity.Support.IntrinsicOwnerLab.Item = jsNative
